### ISSUE TITLE
JS Macro Enhancements

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#104]
The ability to load external JS files into MapTool into a system global area rather than attached to a token.

**Comment by Darinth** [comment]
Because it's related to JS which is what I'm hoping to start focusing on once I get a proper dev environment setup and get a bit more comfortable with MT's codebase, would it be better to create an area in campaign files that generically allows for the storage of chunks of text not related to tokens? This would in theory play quite well then with a simple function that allows chunks of text to be loaded into the javascript engine.

Is this really necessary, or might a reasonable alternative be to allow viewing of token fields as multi-line documents through some fashion and then storing of the necessary javascript functions on tokens? Historically almost all data has been stored on tokens and it has a lot of benefits over trying to store said data directly in the campaign file in some fashion. Library tokens allow you to effectively store a token with all of the necessary data for all of it's tasks on the token itself as an example.

**Comment by thelsing** [comment]
JS can now be stored in AddOns. So I'll close this one.
