### ISSUE TITLE
Autosave Failure - Possibly while editing token

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1069]
**Describe the bug**
User reports autosave failures.

Also, the text for the Autosave failed message (`AutoSaveManager.failed_badState`) has bad formatting.

**To Reproduce**
Unknown - reported on Discord.  May be because Edit Token dialog is open during save?
Log file attached below.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/34379254/71728528-8bdfdf00-2dfa-11ea-89fe-55801968cc69.png)

**MapTool Info**
- Version: 1.5.8
- Install: Upgrade

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
[maptool.log](https://github.com/RPTools/maptool/files/4019429/maptool.log)

**Comment by Azhrei** [comment]
The NPE from Zone.java:406 is in reference to copying the initiative list over to a new Zone before saving the campaign.  Having the token editor dialog open shouldn't be a problem.  (The token editor dialog copies all of the values out of the token to display them in the dialog and only copies them back when the **OK** button is clicked.)  However, there could be an issue if the token were being saved at _exactly_ the instant that the initiative list was being copied.

My inclination is to change the error handling so that the user is notified there is a problem, but to otherwise ignore this transient error.

(Should the `INFO` messages from `model.Grid` be put into a separate issue?)

(We shouldn't try to retrieve external repo data more frequently than once per _time_unit_.  And our error checking should notice that the file doesn't exist rather than reporting that the file isn't in GZIP format.  In both cases, we likely don't need a full stack trace either, just an appropriate message.)

(I also see at Dec 20th 19:47:59 an `ERROR` message, "Server has disconnected."  It happens again on Dec 21st at 4:30:24.  Something else to look into...)
