### ISSUE TITLE
Can't open MapTools on Linux

### ISSUE THREAD

**Issue by juan0286** [RPTools/maptool#1187]
**Describe the bug**
After starting the maptools 1.5.11 beta, I found a bug with getTokenNames, it does not recognize the search property layer: "TOKEN". I was sure that in maptools 1.5.9 it was working.
Close Maptools 1.5.11 beta. and When trying to open maptools 1.5.9 it no longer started.
Maptools 1.5.11 beta neither opens.

**To Reproduce**
1. open mapTools 1.5.11
2. close mapTools 1.5.11
3. open mapTools 1.5.9

**Expected behavior**
Open Maptools

**Screenshots**
better log

**MapTool Info**
- Version: 1.5.11 , 1.5.10, 1.5.9 
- Install:  Upgrade [1.5.9]

**Desktop (please complete the following information):**
 - OS: Linux [Ubuntu]
 - Version [ 18.04]

**Additional context**

[hs_err_pid10099.log](https://github.com/RPTools/maptool/files/4105963/hs_err_pid10099.log)
[log error maptool.txt](https://github.com/RPTools/maptool/files/4105968/log.error.maptool.txt)

**Comment by Merudo** [comment]
I tried in 1.5.11 beta 1 with 

```
[getTokenNames(",", json.set("{}", "layer", "token"))]
```
and got the error:

```java.lang.IllegalArgumentException: No enum constant net.rptools.maptool.model.Zone.Layer."TOKEN" error executing expression getTokenNames(",", json.set("{}", "layer", "token")).```

However, it appears fixed in develop.

**Comment by Azhrei** [comment]
The error dump references `MapTool-1.5.10.jar` in multiple places.  Did you mean 1.5.10 instead of 1.5.11?  Or are you providing the error dump of 1.5.10 and saying that it was substantially similar to the error dumps for 1.5.9 and 1.5.11?

Since 1.5.9 worked before and doesn't now, that seems to indicate that something changed in the mean time.  Did you do an OS update, perhaps?  Or any permission changes or other modifications to the directory hierarchy where MapTool is stored?

(The crash itself actually occurred inside `libfontconfig.so.1`, which isn't a Java library but is written in C.  it's one of the libs that comes with Ubuntu...  That's why I asked about OS updates.)

The stack trace shows that during the creation of the `MapToolEventQueue` object, there was an object being created and that's where the crash occurred (inside `JideOptionPane`).  The problem being reported is in regards to finding/loading a font resource.  However, the problem could be different (such as running out of memory), but the issue was only _detected_ while fonts were being loaded.  (I don't believe there's a memory issue as you appear to have 20G dedicated to Java.)

Do you have any other information you could provide about what might've changed on your system during these executions of MapTool?

**Comment by Phergus** [comment]
We need to know what language/locale he is running in but it appears to be Spanish language.

Also, as Merudo already said, the initial error has already been fixed and is in the 1.5.11-rc.1 release.  No reason to be using the 1.5.11 beta release.

**Comment by juan0286** [comment]
The language of the operating system and in the use of Maptools is Spanish.

Sure enough, I had an Ubuntu update, near the moment maptools started to fail. Initially do not relate.
Maptools did not open, and before checking logs, restart the pc hoping that the problem did not continue. Then the update happened.

And Yes, After 1.5.11 and 1.5.9 do not work, use 1.5.10 and from there take out the log.

**Comment by Azhrei** [comment]
Okay.  We’ll wait a couple days to hear if you have issues with the latest release, otherwise we’ll close the issue...

**Comment by juan0286** [comment]
1.5.11 rc  open and work! Thanks!

**Comment by Phergus** [comment]
That's great!   I suspect the issue was some bad translations in the Spanish language file that had been fixed for the RC.1 release.

**Comment by Phergus** [comment]
Closing.
