### ISSUE TITLE
getBarImage(barName[,value]): assetIds

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#1234]
**Is your feature request related to a problem? Please describe.**
Unable to get the assetId of images from Bars.

**Describe the solution you'd like**
Create a function like getStateImage, but for bars; getBarImage(barName[,value]) where value is the value of bar that returns a specific image. So, 0 is empty bar, 1 is full bar and values in between would be the increments. Not specifying the value (or -1) will return all the assetIds in an array.

**Describe alternatives you've considered**
Not all bars are image or multi-image types, so return "" if invalid or "[]" if no value is specified.

I use multi-image bars a lot and I was designing a user input to set the values and realized I would need to put the images in a table of something if I wanted to use them in the input rather than accessing them directly from the bar.

**Comment by adyoungblood** [comment]
If you don't mind, I'm going to use this issue as a way to wrap my mind around the existing codebase (first time touching it)!

This issue should be relatively easy to resolve by itself, but I have already found another interesting problem that leads me to believe it will be necessary to refactor a little (probably in a different and larger issue). If you put a bar on a token, then change the opacity of the token, the bar's opacity will remain unchanged. However, if the token has a state (image or otherwise) currently applied to it, the bar's opacity _will_ change along with the token. This has to do with how the variable value is passed down the inheritance tree from AbstractTokenOverlay. BooleanTokenOverlay assumes value is a boolean that determines whether alpha composition will be used when drawing the token. BarTokenOverlay interprets value as the current fill of the bar, from 0 to 1.

**Comment by adyoungblood** [comment]
See #2401 .

**Comment by aliasmask** [comment]
I'm thinking size isn't a very important attribute since it just adds -## to the end of the asset id and I wouldn't want that if I'm creating my own forms and using html. It's more of a hassle to remove than to add. But if I can use "" or 0 in it's place so the size isn't added to the assetId, then it's a non-issue.

**Comment by adyoungblood** [comment]
I've changed both getBarImage and getStateImage to accept size arguments of zero. getBarImage("Something", 0, <some_value>) will now return the asset ID without the size appended on the end, as will getStateImage("Something", 0). Anything that can't be cast to a BigDecimal would've worked before (empty strings, like you mentioned), and this change works with that.

**Comment by adyoungblood** [comment]
With my newfound documentation powers, see [https://wiki.rptools.info/index.php/getBarImage](https://wiki.rptools.info/index.php/getBarImage).

**Comment by Phergus** [comment]
Tested `getStateImage()` and `getBarImage()`.  Both functions working as described and as documented on the wiki.
