### ISSUE TITLE
Campaign Auto Saving does not happen in a thread safe way.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#1264]
**Describe the bug**
Details to follow (need the issue number)

**Comment by Azhrei** [comment]
From #1267 

> multithreading issues/bugs are not just limited to concurrent access issues but also encompass state visibility.

Are you saying the state of the new Campaign object might be accessed before the copy constructor completes?  Or are you referring to something else?  (It's not clear from your statement.)

**Comment by cwisniew** [comment]
> Are you saying the state of the new Campaign object might be accessed before the copy constructor completes? Or are you referring to something else? (It's not clear from your statement.)

From the perspective of the second thread yes before the copy constructor has completed. But this is all detailed in the discord discussion you said you read.

**Comment by Azhrei** [comment]
Since Discord isn’t searchable in a reasonable way, and since your typos prevent me from searching for relevant phrases anyway (see, we can both be snarky!), I’ll just point out that an object’s state should not be accessed/accessible prior to construction.  To do so violates the basic rules of object creation.  If there’s a way for a second thread to access such state before construction is complete, that seems like the bigger issue.  (Since you apparently know how that can happen, it would be wise to document it such that other contributors will know as well.)

**Comment by Azhrei** [comment]
Ah, I see you’re not talking about the object being created, not the one being copied.  That clears things up.  (Your statement about “from the perspective of the other thread” had me thinking you were talking about the other thread being able to see the new object and it can’t.)

For anyone coming here looking for info, the comment referred to in the OP is Trevor’s statement about how the Campaign object was “safe” because the copy constructor was being executed on the EDT.  As Craig rightly points out, that doesn’t help with regards to the object being copied, since the network thread can be moving or modifying tokens in a Zone at the time the copy constructor is invoked.  Since the network code was there from the beginning, Trevor likely just missed the fact that the copied object could be modified from that other thread.

As Craig has also pointed out in a separate forum, this will be a pain to correct.  One possible solution is an RCU-type approach, where a flag is set in the zone when the copy begins, indicating that the Zone is quiescent, then the flag is reset whenever a token is modified on that Zone.  This allows the copy constructor to set the flag, copy the Zone, then check the flag again and copy the Zone again if changes have occurred.

(Logging shows the copy constructor takes tens of ms to complete, so this probably won’t happen often.)

The Campaign also contains references to macros.  Something similar might work there.  The macro editor copies the metadata and content to separate fields, edits those fields, then stores the result back.  If the copy were performed at the instant of saving the macro back, the copy could be messed up.

**Comment by cwisniew** [comment]
Ok, again for the record 

Its possible for the second thread to see and access the object before is "sees" that the Constructor (in the case the copy constructor) has completed. This is not about if the constructor has completed or not but what is visible across threads/ So it is absolutely possible for that thread to pick up values as they were mid constructor (but more likely before the constructor has started).

I am not talking about modification after copy (hence the statement in the issue you commented on even though your comment is here 
*"While there is a larger issue of how exactly state persistence should work in a threaded environment where state can change during the saving process to be had (I have created issues #1263 and #1264 for this). A shorter term solution is also required to address the **null pointer/incomplete object initialization problem**"*.)

To address the "it violates object creation" assertion, no it doesn't
https://docs.oracle.com/javase/specs/jls/se7/html/jls-17.html#jls-17.4.5

The only "happens before" event on the edge of a constructor for another thread is it "happens before" the object is finalized, apart from the thread it is created in there are no guarantees about state set from constructor for a non thread safe object (unless you are in the finalizer).

If you continue reading further to 17.5. final Field Semantics
*An object is considered to be completely initialized when its constructor finishes. A thread that can only see a reference to an object after that object has been completely initialized is guaranteed to see the correctly initialized values for that object's final fields.*

Final fields are explicitly called out for this behaviour as the "happens before" rules does not guarantee this for values set in the constructor.

**Comment by nmeier** [comment]
I believe this pr fixes the existing load- /adds the missing save- SwingWorker 
https://github.com/RPTools/maptool/pull/1668

**Comment by Phergus** [comment]
@cwisniew  from the comments in the PR, it sounds like this is complete.  Is that correct?

**Comment by cwisniew** [comment]
@Phergus yes this is complete (for now, we can look at improving when we "break" current campaign format)

**Comment by Phergus** [comment]
No issues seen when saving campaigns.  Appears to be working as expected.
