### ISSUE TITLE
Endlessly "loading map'

### ISSUE THREAD

**Issue by mjmeans** [RPTools/maptool#128]
GM PC is running v1.4.0.5 with several downloaded token sets automatically added through the add resource library menu. GM PC loads campaign. Campaign is 77 MB and has 8 maps. Some have VBL, others do not. Some maps have Bag of Tricks InterPads and some do not. GM PC starts server as LAN. Second PC loads v1.4.0.5 (same version), connects to LAN server as 'Player'. This Player PC displays a default world map. On Player PC I click full screen. On GM PC I click "center players on current view continuous". Two maps will not display on the Player PC. One says "Loading Map 'map1' - 3/5 Loaded 3/5 Cached" and the other says "Loading Map 'map1' - 13/15 Loaded 13/15 Cached". After waiting over 10 minutes, still no map shows on Player PC. One of the two maps that fail to display use tokens from Bag of Tricks, one does not. All the maps that display correctly have a single background image. Both the maps that do not display correctly use two images in the background, one that is "Visible to Players" and one above it that is NOT visible to players. Both PC's are running Windows 10 Pro 1607. GM PC is running Java 1.8.0_66. Player PC in running Java 1.8.0_31.

Hopefully that's enough information to identify the problem.

**Comment by Azhrei** [comment]
Thanks for the bug report!

Please describe the following:

How are you starting each MapTool session?  What is the command line being used (you can copy/paste it from the Launcher screen if you're using the Launcher)?  If you execute MapTool from the Launcher and turn on the console, are any errors reported there?  If so, please copy/paste the console messages into a reply here.  (You'll need to use the Window menu's **Edit** option to copy and paste text from the console window.)

If you export the map(s) that don't work, can the Player instance of MapTool import them or does that also hang?  You can attempt the import with or without being connected to the server.

We may need to load the campaign within a debugging environment to isolate where the hang is occurring.  Do you have someplace where you can make the campaign file available for download?  (For example, a Dropbox account or other shareable web site.)  If it turns out that the exported map can not be imported, then we would only need the map, not the entire campaign.

I have some ideas of what the problem might be, but I don't want to taint your reporting of the issue until we have more information.

Thanks again!

**Comment by mjmeans** [comment]
The campaign files are in preparation of running Pathfinder Rise o the Runelords. They are all copyrighted images, so I can't make them available to anyone who doesn't have this product, otherwise it would be a copyright problem.

I start maptool by double clicking the launcher jar file. Then I click the 'Launch MapTool' button. No changes are made in the launcher's tabs. I'm new to maptool and I have no idea what you mean when you say 'console'. I don't see any reference to 'console' in any of the maptool menus or launcher tabs.

**Comment by mjmeans** [comment]
New information. I made a copy of the campaign file and started deleting various things to see if they make a difference. If I delete both background images, while leaving the VBL and leaving the tokens on the tokens layer, The Player PC now finished loading, but it doesn't display any tokens at all. All the tokens are set as player visible and so is the map. Some of the tokens we made by dropping in png images, some are from Devin Night's Tokens\Townsfolk.

**Comment by mjmeans** [comment]
New information. If I create a new blank map (while center players on current view is enabled) the PLayer PC displays the blank map. If I copy the tokens form the map that doesn't display to the new blank map, the blank map updates on the player PC. If I copy one of the background images form the not-working map to the blank map with tokens already copied, both GM and Player show a large ? for a while; then the GM shows the background image; but the Player still shows the ?. If I navigate to another map and then back again to the new map, I get the message about loading map and it never displays.

**Comment by Azhrei** [comment]
I understand about RotRL images.  I have those modules but it's best to not upload them anywhere. :)

I was referring to the **Advanced** tab, specifically the **Launch with console** checkbox.  But it doesn't matter so don't worry about it.

If you delete the images and it loads, then there's likely a memory shortage on the Player system.

And if the Player computer has less physical memory than the GM machine, there's no way to guarantee that the Player will be able to load the same maps that the GM can load, since you're creating the maps on a machine with more RAM to begin with.  You'll need to drop the resolution of the images you're importing in order to reduce memory consumption.

Check out the forums at http://forums.rptools.net/ and you'll find a lot of discussion about memory usage in MapTool (check out the "MapTool" subforum, since memory issues are the same between versions 1.3 and 1.4, so most of the discussion happened on the older version).

**Comment by mjmeans** [comment]
New information: One of the maps had backgrounds named "Untitled" and "Untitled 1". I changed those to meaningful names and that map now loads. The other map that didn't load also had background images titled "Untitled" and "Untitled 1", and I changed those names, but that map still doesn't load. The Player PC memory indicator on the bottom right corner shows 105M/256M. Remember that the entire campaign file is only 77 MB. I've also checked the size of the two background PNG image files. Only 5 MB each.

**Comment by wolph42** [comment]
Have you tried clearing the cache on the pcs where the maps don't download.  It should be in the .maptool dir.

**Comment by Azhrei** [comment]
> Remember that the entire campaign file is only 77 MB. I've also checked the size of the two background PNG image files. Only 5 MB each.

And this is why I pointed you to the forums.  File size is irrelevant regarding the memory consumption of an image, but since the forums describe why I won't be doing that here.

**Comment by mjmeans** [comment]
Thanks. That did it. I guess I have to be careful to have background images with the same names between multiple maps. It would be nice if MT would pop up a warning about which maps have background with the same name when starting the server.

**Comment by Azhrei** [comment]
Image names are not important.  MT internally calculates checksums for every image and then puts the image into the campaign using the checksum as the filename.  (If you rename the campaign file to end with .ZIP, you'll be able to look inside and you'll see the images are named by their checksum.)  We use checksums because it's possible to have an image named **chair.png** in one directory and **chair.png** in another directory, yet both can be added to a map.

More likely there was something else being cached in your `.maptool` directory that was causing a problem, but since clearing the cache worked it probably doesn't matter now. :)

Glad to hear you got it solved!
