### ISSUE TITLE
AI Movement Bug - Too restrictive when moving next to VBL masked areas.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1299]
**Describe the bug**
Movement next to VBL or in between two areas of VBL can cause the pathfinding algorithm to block access to an otherwise open grid cell.

**To Reproduce**
1. Load attached campaign.
2. With AI enabled, try to move Hero token through passage.
3. Observe that Movement counter is stuck at 0.
4. Turn off AI and movement works normally.

**Expected behavior**
Expect movement to work normally.

**MapTool Info**
- Version: 1.5.12
- Install: Any

**Desktop:**
 - OS: Windows
 - Version: 10

**Additional context**
Remove ".zip" from name.
[AI Movement Bug.cmpgn.zip](https://github.com/RPTools/maptool/files/4225665/AI.Movement.Bug.cmpgn.zip)

Drawing the VBL for the map with snap-to-grid did not produce the error.  I had to draw a section of VBL at the top of the passage that slightly overlapped the passage.

Map with similar problem.
[AI Movement Bug 2.rpmap.zip](https://github.com/RPTools/maptool/files/4228590/AI.Movement.Bug.2.rpmap.zip)

Map with interesting variation of problem.  Attempt to move Hero token directly down 1 cell.
[AI Movement Bug 3.rpmap.zip](https://github.com/RPTools/maptool/files/4228596/AI.Movement.Bug.3.rpmap.zip)

**Comment by JamzTheMan** [comment]
Another example map...

[Hallods_Hideout.zip](https://github.com/RPTools/maptool/files/4264790/Hallods_Hideout.zip)

**Comment by Phergus** [comment]
That's the same map as AI Movement Bug 2.  I took out a bunch of the extraneous tokens and such to cut the file size down.

**Comment by Merudo** [comment]
I did some sleuthing, and my conclusion is that MapTool deals incorrectly with VBL when it takes an hollow shape, such as a hollow rectangle.

The problematic line is `vblGeometry.intersects(centerRay)` used in `AbstractAStarWalker`,

The issue is that hollow VBLs are considered solid, and so `vblGeometry.intersects(centerRay)` will return true for any movement inside the hollow shape.

The bug is bypassed by making any hole in the VBL so it is no longer hollow. For example, in AI Movement Bug making a very thin hole anywhere in the VBL of the room makes movement possible again.

This is a huge bug and can creates all kind of issues when using hollow shaped VBL. The reason the bug has not manifested itself more is the earlier check

```java
    // If there is no vbl within the footprints, we're good!
    if (!vbl.intersects(startBounds) && !vbl.intersects(goalBounds)) {
      return false;
    }
```
which uses the `vbl` shape (instead of `vblGeometry`) to preemptively allow movement if no VBL exists within the bounds of the start and end cells.

If you comment out the `return false` line, the bug manifests itself fully; in `AI Movement Bug`, it becomes impossible for the token to make any movement, for example.

**Comment by Phergus** [comment]
Nice sleuthing.   There does seem to be something more however.

I took AI Movement Bug 2 map and cut 2 holes in the VBL so that it is broken up in multiple shapes and the issue is still present.

[AI Movement Bug 2a.rpmap.zip](https://github.com/RPTools/maptool/files/4387438/AI.Movement.Bug.2a.rpmap.zip)

**Comment by Merudo** [comment]
I checked the map. Interestingly, the VBL is checked from the bottom of the token instead of the center.

I reduced the VBL to a single point. The movement to the left of the Dwarf remains impossible:

![VBLbug](https://user-images.githubusercontent.com/7371085/77682129-69c2ac80-6f64-11ea-9baa-a9d85a336275.png)

Yet, the Dwarf can move to the left even with this VBL:

![VBLbug2](https://user-images.githubusercontent.com/7371085/77682284-b3ab9280-6f64-11ea-8f7b-88b96a94c6d9.png)

**Comment by Phergus** [comment]
Wow.  That's curious.

**Comment by Merudo** [comment]
I found out what's going on. There seems to be an invisible -18 pixel yOffset on the grid.

**Comment by Phergus** [comment]
So maps with a grid offset have the issue.  Wow.

**Comment by Merudo** [comment]
PR #1416 fixes the offset issue.

**Comment by Phergus** [comment]
Testing fix.  Issues seen on AI Movement Bug 2 & 3 maps are resolved.

As noted, issues with hollow geometry still present.

**Comment by Merudo** [comment]
I accidentally introduced some offsets issues for the isometric, hex and gridless grids with PR #1416.

Pr #1417 fixes these problems.

**Comment by Phergus** [comment]
Testing with #1417.   Hex movement seems to be fine on maps with offset grid and without offest.  Tested AI movement within a cave map with offset grid and matching VBL with no issues.  No issues seen with movement on gridless and iso maps.

**Comment by JamzTheMan** [comment]
Gah, grid offsets. Good work!

Makes me wonder now what happens with tokens that have anchor offsets (and what should happen really?)

@Merudo Thanks for chasing this down. Regarding the hollow point, IIRC I convert the VBL once to Geometry? There may be a setting to check for valid geometry when doing so (which may be on now) and maybe toggling that will fix it. We ran into a similar issue with holes recently in the token optimization update which was resolved by turning it off. 

If I'm feeling better tomorrow I'll take a look at the code.

**Comment by Merudo** [comment]
Thank you @JamzTheMan.

I looked more into it and the issue is that the `PathIterator` created by `vbl.getPathIterator(null)` has the `WIND_NON_ZERO` winding rule.

This means that any enclosed point becomes part of the VBL.

The `PathIterator` winding rule needed is the `WIND_EVEN_ODD`. This makes is so that the "hole" of a doughnut-shaped VBL will be free of VBL.

Unfortunately it seems to be that all `PathIterator` created from an area automatically have the `WIND_NON_ZERO` winding rule, and that it is isn't possible to change the rule of a `PathIterator` once created.

**Comment by Merudo** [comment]
Thank you, @JamzTheMan!

To my knowledge, the anchor offsets only affect the token's appearance and personal VBL. Moving a token around with AI movement ignores the offsets.

As for the hollow point issue, I believe our problem is [the same as this one](https://github.com/locationtech/jts/issues/408).

**Comment by Phergus** [comment]
I have a number of maps that have hollow VBL that don't exhibit this issue.

Once we have some test cases that produce the issue we can open a ticket just for the hollow VBL issue.
