### ISSUE TITLE
campaign variable

### ISSUE THREAD

**Issue by stolkun** [RPTools/maptool#1392]
**Is your feature request related to a problem? Please describe.**
I'm pretty frustrated when i try to use a macro which contain get notes and i do it on a lib:token if it's not in my map it doesn't work so i have to manually write in every macro with getNotes on a lib:token the map name but if i change of place the token it won't work anymore

**Describe the solution you'd like**
I would like the possibility to add campaign variable accessible from anywhere in the campaign so that i can just change once the campaign variable so that every macro that call it are directly changed from anywhere in the campaign. **little point to precise:** campaign variable could be used for more thing that only what i described, for example to retrieve constant you use multiple time in the campaign

**Describe alternatives you've considered**
the only workaround i've found was to use moveTokenFromMap() and moveTokenToMap() to not precise the map name in getNote

**Comment by Phergus** [comment]
Why are you moving lib:tokens around?   Just put them on one map, hidden from the players, and leave them there.

**Comment by Azhrei** [comment]
> **Is your feature request related to a problem? Please describe.**
> I'm pretty frustrated when i try to use a macro which contain get notes and i do it on a lib:token if it's not in my map it doesn't work so i have to manually write in every macro with getNotes on a lib:token the map name but if i change of place the token it won't work anymore

So if I understand correctly, you have a macro named `getNotes()`.  It sounds like this macro retrieves information about a particular map, so you put the information into that macro on a Lib: token and then you can execute the macro by selecting the token and clicking on it in the **Selection** panel (or **Impersonation** panel, or somewhere else).

But because the notes are different for each map, you copy the Lib: token from map to map.  What I don't understand is why you need the map name to reference the Lib: token (all maps are searched when you access a Lib: token).

I don't know what your `getNotes()` macro actually does, but there are multiple different ways to put notes on a map.  What I do is I drop down tokens on the Hidden layer and fill the Notes and GMNotes fields with my notes.  Then I can click the token at any time to see the text (and I use HTML inside the notes for formatting).  If you put public information into Notes and private stuff in the GMNotes, you can even move the token from the Hidden layer to the Object layer so that players can see it also (I do that for rooms:  description in Notes, treasure/trap details in GMNotes).

If you want to describe what your goal is, we may be able to tell you how to do that in MapTool.

> **Describe the solution you'd like**
> I would like the possibility to add campaign variable accessible from anywhere in the campaign so that i can just change once the campaign variable so that every macro that call it are directly changed from anywhere in the campaign. **little point to precise:** campaign variable could be used for more thing that only what i described, for example to retrieve constant you use multiple time in the campaign

This has actually been discussed.  Honestly, Lib: tokens are kind of a kludge and the plan is to find an alternative way of handling "global" macros and other data.

**Comment by stolkun** [comment]
So maybe i miss explained what i wanted to say cause @Phergus i'm not moving my lib:tokens around but my problem is that if i ever want to move them around i have to change the mapName where the macro function getNotes and setNotes are cause those function doesn't work if you don't precise the map if you are not on the same map so it's really time consuming to change every time the mapName.
@Azhrei i didn't create the macro getNotes, i'm just using the one already existing using those arguments getNotes(id, mapName) and setNotes(notes, id, mapName) which get and set the notes of a token.
Because we can't duplicate lib:token and it's not a good way to move them around, the best way is to precise the map name in the already existing macro function.
The only problem is that if i ever want to change of map where my lib:token are then i have to change the name for every set notes and get notes and if i had a way to store the name variable globally i would be able to call it from anywhere in a macro which would only make me need to change once the variable.

**Comment by Phergus** [comment]
You can't use `getCurrentMapName()` in your macro?  Assuming it is the current map you are wanting information from?

**Comment by stolkun** [comment]
getCurrentMapName() return the map where you currently are if you are not on the same of the lib:token it will not give the name of the map where the lib are situated but where you currently are

**Comment by emmebi** [comment]
Why not using a User Defined Function with the name of the Token map?

You call it getTokenMap(), now you can use:

setNotes("notes", getTokenMap())

and when you have to move the token map, for whatever reason, you just change it in the getTokenMap. Would it cover your use case?

**Comment by stolkun** [comment]
i guess it can i'll try it

**Comment by stolkun** [comment]
yup it worked so i guess i can use a macro to keep it like a campaign variable and then use a UDF well thanks for the tip and sorry for disturbing didn't know there was an easy workaround to get the mapName easily from one call
