### ISSUE TITLE
Old-style macros, deeper recursion

### ISSUE THREAD

**Issue by perkinslr** [RPTools/maptool#140]
Currently macros can only nest braces 2 levels deep.  There are some clever hacks to work around this, using extra single-quotes to make the regex match, but that causes other issues.  If anyone is interested, I hacked in a fix in MapToolLineParser.java that checks if match just doesn't consume the entire roll string.  If that is the case, it checks if it is missing any braces, and if so, increases the matched portion until it finds the missing braces.  If that makes it consume the entire string, it counts it as a match and doesn't raise an exception.  It seems to work, but is not a clean implementation.  If anyone is interested in using it, or in re-implementing it cleanly, it's commit perkinslr/maptool@a459babb8f269056d4dc9c6235121eeb426194eb

I did not bother to patch switches, since I've never needed to nest more than 1 level inside any given case.  Doing so would not be too difficult though.

**Comment by Azhrei** [comment]
We're switching to JavaScript (Craig has already done most of the work on this) so MTscript will eventually go away other than as a technique for calling JS code.  The remaining work will be building good, object-oriented interfaces to existing MT objects and fleshing out some details.

**Comment by perkinslr** [comment]
Aye, I already played with the JS stuff a bit using the 1.4.1 dev branch.  That's part of why I didn't bother making this clean enough for a pull request.  I only bothered with this at all because it took less than 10 minutes to write and test the hack.  I figured if anyone else needs it available in the 1.4.0 branch, they can apply the patch, or use it to implement a better version.

**Comment by MalukuSeito** [comment]
I am already going through the whole process of designing Libraries and Objects for my LUA Implementation, here is what I came up with so far: Token, Maps, Token Properties, Macros are special objects in LUA, their properties are mapped to the properties of the maptool objects. this is fairly easy in LUA, since objects are atomic there, so I have no idea how that would translate to JS

**Comment by Azhrei** [comment]
Craig is doing the JS implementation so the final result is up to him, but there are some questions to ask, the big being:  should JS have direct access to the objects in MapTool, or should there be a façade layer that JS uses?  It’s a tricky question with quite a few pros and cons...

One thing that really leans towards using a façade is that the core of MT could then change without necessarily changing the scripting API.  It’s important because we have a lot of things we’d like to do differently in the internals.

**Comment by perkinslr** [comment]
Why not both?  It's a common solution to this type of problem in Python, and I don't think it would be a bad idea here.  

Have a way to directly access the internal objects, to catch the edge cases where someone wants something fancy, but with no promises that it won't break in future updates.  Then have a stable API, which will use the usual deprecation-before-deletion and no undocumented changes.  

This has the advantage that the public API itself can be written in JS, using the unstable primitive API, which means it can use code generators to fill in a bunch of the gaps more easily.

**Comment by Azhrei** [comment]
Oh man, Python is a terrible example!  Just look at the fiasco of converting from Py2 to Py3!

I believe it would only muddle the API for people using it.  They'd have to know which objects are internal and which are part of the abstraction layer.  Otherwise, they can't know if their code is going to be upward compatible...

**Comment by perkinslr** [comment]
The mess that is converting Py2 to Py3 is mostly due to renaming builtin types nonsensically, then providing an 'upgrade' script, that doesn't properly map the Py2 type names to the Py3 type names.  

As for muddling the API, as long as the naming convention is clear, and the wiki only documents the public API, I don't think it would be an issue.  If the public API is something like `MapTool.Token`, the private API would be `MapTool._Private.Token`.  If your script doesn't have `_Private` in it, it is forward compatible.  The wiki would only mention that if you want to do something not covered by the API, check out the `_Private` class, and grab the source code for your particular version to see what it can do.

**Comment by Azhrei** [comment]
Well, the Py2 to Py3 conversion did some things that make sense (cleaning up mistakes like range/xrange and just creating range in Py3).  But what matters for this discussion is that a programming API had fundamental changes that made code incompatible.  The obvious example is `print` changing from a keyword to a function.

It's unlikely we'll start with both a public and private API.  More likely is that the public API will be settled and we'll add to it over time, as use cases prompt the need for additional access.  But we'll see how it shakes out as it evolves...

**Comment by Phergus** [comment]
At this time there is no plan to switch to JavaScript and a new parser + MTScript2 language is being worked on rendering this issue OBE.
