### ISSUE TITLE
getInfo("Campaign") not returning all states.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1472]
**Describe the bug**
The macro function `getInfo("Campaign")` is not returning all of the defined states.

**To Reproduce**
1. Open MapTool
2. Type `[json.get(getInfo("campaign"),"states")]` in the chat and hit enter.
3. Only returns: `{"no group":["Dead"]}` which is only the 1st of the 9 default states.

**Expected behavior**
Expect to get all defined states.

**MapTool Info**
- Version: 1.5.11+, 1.6.0
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows 10, Linux

**Additional context**
Macro `getTokenStates()` still returns full list.

**Comment by eCyclops** [comment]
I see that you've already noted that it appears to be a regression between 1.5.10 and 1.5.11. Further information: I encountered the issue in the Linux version, so you can add that to Desktop version.
I also appreciate the information about the workaround, as that will enable me to re-write macros which broke because of this.

**Comment by Phergus** [comment]
Fix committed.
