### ISSUE TITLE
Need capability to export Macro Groups

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#1482]
**Is your feature request related to a problem? Please describe.**
The macro panels only support exporting a single macro as a `.mtmacro` file or all the macros on a panel as a macro set (`.mtmacset`).  Frequently all that is needed is the ability to export/import just those macros in a group.

**Describe the solution you'd like**
Right-click _Export Macro Group_ option like _Export Macro Set_.

A copy/paste option for macros and macro groups would also be helpful.

**Describe alternatives you've considered**
Alternatives are the extremely tedious dragging of macros from one token to another via the selection window, or worse, between one macro panel and another.  Importing large macro sets when only a few in a group are needed risks overwriting other customized macros and takes an excessively long time.

**Additional context**

**Comment by selquest** [comment]
Added right-click action.

**Comment by Phergus** [comment]
Tested export/import of macro groups from Campaign, GM, Global, Selection and Impersonated panels.  Working as expected.

**Comment by Azhrei** [comment]
How do they come back in on older releases?  Just curious...

**Comment by selquest** [comment]
> How do they come back in on older releases? Just curious...

@Azhrei I haven't explicitly tested it, but it should be exactly as compatible as the current "Export Macro Set..." option.  Nothing changed in the output produced, it just applies a filter first so only members of the relevant group get included.

**Comment by Azhrei** [comment]
Ah, so there's no group name stored?  Sorry, I don't remember what the XML was of the existing macro set...  But that sounds good. :)

**Comment by selquest** [comment]
Yeah, each button stores its own group name so that when it gets re-imported it's back in the same group, but macro "groups" are really just a hint to the UI layer.

Really I'd love to see this as part of a more general-purpose macro button management system, where you could select multiple groups at a time for export, preview incoming imports to choose only those groups/macros desired, copy multiple macros/groups from one token or panel to another, etc... basically all the things RPedit does but with better integration.

I think all that would require some pretty fundamental restructuring to the implementation of macro buttons though, and I'm not sure it's a good idea to dive into that with expected changes coming to MTscript, campaign libraries, etc.

This particular bit was a quick win by just using the existing export mechanism for an easily identified subset of the buttons on the panel.

**Comment by Phergus** [comment]
The "group" macro exports import into older versions just like a full panel export.  You get a version mismatch message but they import just fine in 1.7.
