### ISSUE TITLE
Wrong tooltip on 'Language' in Preferences-Startup

### ISSUE THREAD

**Issue by pizzystrizzy** [RPTools/maptool#1498]
![image](https://user-images.githubusercontent.com/6253328/78943819-30209400-7a82-11ea-9875-c737ff697d6f.png)

1.6.0.rc1

**Comment by Merudo** [comment]
This page of the settings is not localized. Maybe that be done as well?

**Comment by Azhrei** [comment]
Sounds reasonable to me.

Note that there is an `AbeillePanel` class that was supposed to be able to bind field names to property keys at initialization.  Trevor wrote this so it's clearly _very_ old, but I never got it to work the way I thought it should work.  If you want to rummage around in it and see what the issue(s) are, this would be a good opportunity (as there are plenty of other panels that still need localization and would benefit from a layer that automates this aspect).  However, if it turns out to be an intrusive change...?

**Comment by Merudo** [comment]
What should the tooltip be?

**Comment by Phergus** [comment]
Perhaps:   _Select Language for User Interface_

**Comment by Phergus** [comment]
Fixed by #1611 .
