### ISSUE TITLE
function replace() 

### ISSUE THREAD

**Issue by JambonII** [RPTools/maptool#1517]
**Describe the bug**
Can't replace '|' 

**To Reproduce**
[r: test = "Please remove this | vertical bar"]
[r: replace(test, '|', ' ')]
P l e a s e r e m o v e t h i s | v e r t i c a l b a r 

**Expected behavior**
Please remove this  vertical bar

**MapTool Info**
- Version: 1.5.14

edit : 

Work with  :
[r: replace(test, '\\|', ' ')]

**Comment by cwisniew** [comment]
This is because the argument to [replace](https://lmwcs.com/rptools/wiki/replace) is a [regular expression](https://lmwcs.com/rptools/wiki/Macros:regular_expression) not a standard string. The | is a special character in regular expression (or) so its actually saying replace any non character OR any non character with ' ', which is why you are getting a space between each character in the output. 

To specify an actual | character you need to escape the | so its no longer a special character with \\ (two \ are required to specify the escape as documented in the above regular expression link on the wiki).

So to replace | use something like below.
[r: test = "Please remove this | vertical bar"]
[r: replace(test, '\\|', ' ')]
