### ISSUE TITLE
MapTool should be able to extract full pages (as a pdf viewer would render them using default layers) from a pdf

### ISSUE THREAD

**Issue by xdy** [RPTools/maptool#1518]
**Is your feature request related to a problem? Please describe.**
In many non-paizo pdf:s (such as the Mongoose ones) extracting images gets one only the various parts and layers of the full image as separate files. I.e. nothing that can be used as a map or token.

**Describe the solution you'd like**
If I could extract the whole page from the pdf this would often help. It's easy enough to mask out any 'non-player' parts with VBL or drawings.

**Describe alternatives you've considered**
Keep using printscreen, save to disk, load in maptool.

**Additional context**
I have this implemented on a branch (https://github.com/xdy-forks/maptool/tree/extractPdfPage), and will make a PR when the issue is assigned to me.
The way I've implemented it does what I wanted it to do, but has the effect that all pages in the pdf are extracted as images (as it hooks into the 'extract all images from a page' code), with a DPI of 96 (as 72 was just too grainy for me). The added time to process a pdf isn't enough to bother me (haven't really measured the time though.)
While doing this - or, rather, while fixing the bugs I caused by doing this :) - I also fixed a few warnings, added some javadocs, improved logging around this a bit, and even tested pdfs from various origins.
Maybe change to save 'whole page' files to separate directory, or just clear name standard.
Maybe change so this feature is turned off by default (use something like -Dmaptool.pdf.extract_rendered_pages=true to turn it on)

**Possible future improvements**
Make it possible to turn this on and off using the gui.
Make it possible to change the DPI.
Make it possible to only get the pages that are 'mostly image'.
Make it possible to 'split' a page into several images based on some criteria/get only a certain part of a page (useful for pdf:s with geomorphs).

**Comment by xdy** [comment]
Possible fix on branch.

**Comment by Azhrei** [comment]
This topic needs some discussion.

First, treating PDFs as directories makes sense because they are repositories of images, but it means searches for the name of the PDF don’t work (directory names are not searchable).  Should they work?  (It seems reasonable since the name of the image inside the PDF is likely meaningless.)

Second, how does the user choose full image vs. partial image?  (The OP says this is currently all or nothing.)  Should the PDF be exploded in the directory tree as having two components, “full” and “partial” (or some other names) and then the first contains full-page images (this PR) while the latter contains image components (existing approach)?

Is there any way to incorporate recognition of “layered PDFs”.  Paizo has been making PDFs that include embedded JavaScript code that can enable/disable layers of the image such that a GM could import the base map without traps and secret doors marked, but that doesn’t seem possible with the current implementation (although this is likely a separate issue, unless it factors into how this PR “flattens” the image).

Whew.  Overall, this sounds like a great idea.  And I’m all for it if the directory search thing is worked out, and there’s some way for the user to choose how they want to view the PDF.

**Comment by Phergus** [comment]
> in many non-paizo pdf:s (such as the Mongoose ones) extracting images gets one only the various parts and layers of the full image as separate files. 

Just verifying that this was happening with the current PDF reading capability of MapTool.  I know it happens a lot with Adobes Acrobat Pro (not reader).

Also there needs to be a way to control this as I for one won't ever want this.

**Comment by xdy** [comment]
@Azhrei the first part of your comment I assume applies to #1465?

Splitting them into separate directories sounds reasonable. Probably best to leave the ones produced by the current code where they are and put the 'whole page' ones in a subdirectory I guess. No particular reason they needed to end up in the same directory, other than MVP/me being lazy. :)

As for layers, I agree that this is probably a different issue, starting with some research. I know pdfbox can create pdf:s with layers, no clue if it can do other things with them (enable/disable, extract stuff from that layer only, etc). But, a very useful separate issue...

@Phergus Would a property to turn it on (i.e. disabled by default) work for you? Say, start maptool with -Dmaptool.pdf.extract_whole_page=true to turn it on. (And then create a separate issue to add gui for it.)

**Comment by Phergus** [comment]
> Would a property to turn it on (i.e. disabled by default) work for you? Say, start maptool with -Dmaptool.pdf.extract_whole_page=true to turn it on. 

I guess so. @JamzTheMan ?

Curious as to why using the export to image feature of Acrobat Reader, PDF-XChange Viewer, or other PDF readers isn't sufficient?  They already have all the configuration options for DPI and such.

**Comment by Azhrei** [comment]
> @Azhrei the first part of your comment I assume applies to #1465?

Yes.

> Splitting them into separate directories sounds reasonable. Probably best to leave the ones produced by the current code where they are and put the 'whole page' ones in a subdirectory I guess. No particular reason they needed to end up in the same directory, other than MVP/me being lazy. :)

They could likely even stay in the same "directory" as long as the title was meaningful, something like "full page 03" or similar...?  (Although I think a directory is easier for users.)

Does your PR cache the full page images similar to the way the original did for images?

> As for layers, I agree that this is probably a different issue, starting with some research. I know pdfbox can create pdf:s with layers, no clue if it can do other things with them (enable/disable, extract stuff from that layer only, etc). But, a very useful separate issue...

Yes, there's the pdfbox-app that has a variety of tools in it.  However, I opened a layered pdf using its PDFDebugger and can't see any of the toggle-able layers represented by objects?  Strange.

And because there's JavaScript involved, it would likely have to wait until MT does something with JS.  I expect that the JS code toggles some kind of "visible" property on/off for multiple elements.  That explains why there isn't a single object in the pdf to represent this "layer".  But as you say, research...

> @Phergus Would a property to turn it on (i.e. disabled by default) work for you? Say, start maptool with -Dmaptool.pdf.extract_whole_page=true to turn it on. (And then create a separate issue to add gui for it.)

If the full page images are clearly demarcated as such, I'd be fine with including this functionality without a command line parameter being needed.  The issue is simply not to remove existing functionality, AFAIC.

**Comment by Azhrei** [comment]
> Curious as to why using the export to image feature of Acrobat Reader, PDF-XChange Viewer, or other PDF readers isn't sufficient? They already have all the configuration options for DPI and such.

It just adds an extra step.  I presume that's why Jamz included the PDF import in the first place.

**Comment by Phergus** [comment]
It doesn't really.  You open the PDF in a viewer and select export to image.   You locate the PDF in your Resource Library and then click on it to extract.   You drag them to the map from your file explorer or from the resource library.

The original intent of the PDF import was to get the actual individual images which you can't easily do from most commercial gaming PDFs and can't be done with the typical PDF viewer.

Extracting both the individual images and the full page images means double (and more) the drive space as each one will be added to the `imageThumbs` cache - whether they get used on a map or not.  Fortunately the extracted images in the resource library folder go away when exiting MapTool.  We're also talking about double the time to extract two sets of images.

**Comment by Azhrei** [comment]
> It doesn't really. You open the PDF in a viewer and select export to image. You locate the PDF in your Resource Library and then click on it to extract. You drag them to the map from your file explorer or from the resource library.

This would be a fine approach, but I have not found the Rescan option to work properly when viewing a directory in the Resource Library.  But if it did work, then I agree, this feature is less necessary.

> Extracting both the individual images and the full page images means double (and more) the drive space as each one will be added to the `imageThumbs` cache - whether they get used on a map or not.

Hm, good point.  That's a definite downside.  (Likely not significant for most users, but still an issue.)

> Fortunately the extracted images in the resource library folder go away when exiting MapTool.

What are you referring to?  Do you mean the contents of the `imageThumbs` cache or something else?

**Comment by xdy** [comment]
@Phergus True, but, for me at least this saves enough effort that it's worth it.
My current campaign is a published sandbox, meaning that I often don't know where my players are heading until they are there. Now, true, I could prepare each location in advance, but, well, I have neither the time nor the energy for that.
Having to - in the middle of a session, swap to the pdf-reader, do a printscreen, paste it into paint.net, save the file in a directory a resource library, open the image and then dragging it onto the map is simply adds too much friction into the session for me.
Much better to simply open the pdf I already have in my resource library, find the proper page and drag it onto the map.
Of course, I still have to block out any bits the players shouldn't see, but that bit is kind of unavoidable. Well, other than saying 'Pay no attention to the man behind the curtain.' and expect the players to not act on information their characters don't have. :)
Now, it could be I'm the only one that needs this functionality, in which case fair enough, I'll keep it on my branch.
But, I kind of doubt I'm the only that tends to run things by the seat of my pants. :)

**Comment by xdy** [comment]
One reason one might want to have this turned off is if it takes 'too much' extra time to extract the full pages. I haven't measured it yet (and I have a fairly hefty machine, so might not say much about how slow it could potentially get), but it is a concern. 
Another would be if the rendered pages take up too much disk space, which they well might.
So, an option to turn it on/off is probably a good idea.

**Comment by Phergus** [comment]
@Azhrei 
> >  Fortunately the extracted images **in the resource library folder** go away when exiting MapTool.

> What are you referring to? Do you mean the contents of the imageThumbs cache or something else?

The folder in the resource library.  The extracted images that you see in the Resource Library go away when you shut down MapTool.  They are temporary.  So if you want to access them again you have to wait for the extraction process again.  In most cases folks are probably just looking for a few images which they put in their maps or tokens and then are done with it.  Not keeping the images around makes sense.

@xdy 
> ...swap to the pdf-reader, do a printscreen, paste it into paint.net, save the file in a directory a resource library, open the image and then dragging it onto the map simply adds too much friction into the session for me.

That does sound like a pain.  Why not open the PDF, select Export to Image in the PDF viewer and be done?  I use PDF-XChange viewer but I know others have that capability as well.

**Comment by Azhrei** [comment]
> The folder in the resource library. The extracted images that you see in the Resource Library go away when you shut down MapTool. They are temporary.

Interesting.  I assumed they were cached.  Now that you mention it, it does seem that they’re still pretty slow on the second viewing, but I chalked that up to the size of the image itself (I’ve been looking at map PDFs) and the time required to convert it into a thumbnail.  I suppose the thumbnail could at least be cached under `imageThumbs`...

**Comment by Phergus** [comment]
Yup.  The imageThumbs stay there so yay for that but the actual extracted images go into `.maptool-rptools/tmp/pdf-filename`.  If you check the folder via Finder that matches the Resource Library folder you'll see that only the PDF is there.

**Comment by xdy** [comment]
@Phergus Hmm. You can export something that is actually several pdf layers of images on top of each other as an image from that pdf viewer?
Certainly can't do it with either Acrobat Reader or SumatraPDF. Acrobat Reader and PDFSam Enhanced do have a built in snapshot tool to take a screen dump of just part of the picture, but then I still need to paste that into paint.net (etc), so seems little better than the windows snippet tool to me.
Or, am I missing something here?

**Comment by Phergus** [comment]
I'll have to track down one of the PDFs that have layers to verify.  I _think so_ but should check.  I know I have a number of PDF map tiles that have layers to turn on/off.  I'll just have to remember which ones.

**Comment by Phergus** [comment]
Got lucky. First PDF I looked at.  PDF-XChange exported it exactly as it displayed when I toggled different layers on/off.

**Comment by Phergus** [comment]
Just to clarify, I'm not against the capability of extracting a whole page as an image just automatically dumping an entire PDF as full page images for each and every page.

An option to disable it or just be more picky about which pages get extracted and I'm fine.

**Comment by JamzTheMan** [comment]
Layers are one thing but I can probably dig out a PDF that your typical "Extractors" will NOT work with. At least at the time I wrote this code and the reason I wrote this.

The Paizo "Interactive" maps will store "images" in "annotations" (buttons) and on click of the button swap the images. There are usually 4 images stored this way grid/no grid version of player/gm maps.

And ya, as long as you let it "finish" the extract, it's cached until you close MapTool. I didn't think people wanted to eat up disk space caching thousands of images.


With that said, IF i were to do this again and needed full page extraction, I'd probably copy my code from TokenTool.  It already did full page render, has a nice page view, only extracts images from the current page, and is threaded pretty decently I think.

But that depends if you would rather have an "Open PDF" window instead that you can then drag images onto the map vs the current `Resource Library` mechanic.  Both have there positives and negatives.


Now, given all that and since you coded it all before opening an issue for discussion, you probably don't want to redo all the code.  For "Full Page" extraction, on click of a PDF, I would just add a `Checkbox` next to `Search subdirectories`  like `Render Pages` that wound either ALSO render the page or JUST render the page (I'd lean for both so new users just don't check it and think the extractor sucks at getting images)

As far as search PDF's. I'd add another checkbox maybe in the same section as well `Include Directories` or some such and then also filter out Resource Library folders, PDF's and HL Portfolios. (Why limit to just PDF's?)

**Comment by JamzTheMan** [comment]
Example on how I do it in TokenTool, images are extracted on the right as "buttons" which can be dragged. One advantage of going with it's own PDF Extract Window is you could open multiple PDF's at once and keep them open and go to the direct page you need.

![image](https://user-images.githubusercontent.com/8051654/79076622-2df84880-7cc1-11ea-9f5a-35e11d32c15d.png)

**Comment by xdy** [comment]
@JamzTheMan Well, it's frankly not a lot of code. I started doing it because, well, I wanted an easier way to get a rendered page. Once I was done I figured someone else might want it as well. If nothing else, it'd start a discussion on what was actually needed. Which it has, so it's got that going for it. :)

I haven't really looked at TokenTool (I usually settle for just grabbing an image of the net, possibly giving it a transparent background if I'm feeling fancy), but that does sound like something that would be useful. In fact, if it had been in MapTool that would have been just the thing for me. Getting *all* the pages rendered was mainly a side effect of the way the resource library code looked, a specific page or two is usually what is needed.

Your other suggestions sound like good ideas for a 'resource library' implementation. Not for me - well, not right now anyway -  as that'd mean having to set up abeille (or whatever the gui tool was).

If I have some time tomorrow I might return to this and see how easy it would be to getting the functionality from TokenTool into MapTool.
Most likely not for a few weeks though, so if anyone is interested, feel free to grab it.

**Comment by JamzTheMan** [comment]
For now, I think just adding a checkbox to include full page renders will be ok. I pretty much used the same code for both TT and MT for extraction and ya, rendering a full page is pretty easy. And it's better than not having the option. For interactive pdf's you will get the default settings (tags, grid, etc probably on) but maybe that's what the user wants/needs.

IIRC in TokenTool I got the monitor's DPI via code and used that for page render, but I'm mostly just showing the full page and not using it. An higher DPI may be nice for Maptool though (I have flip mats that are like 300dpi IIRC)

Also, check the code first for Search Directories, I'm 90% sure that's just added in using normal swing and not via abillie forms in which case you can just duplicate and do all the code inline. (could be wrong, been 2 years since I wrote that code but seems familiar)

**Comment by xdy** [comment]
@JamzTheMan It seems I did indeed independently implement a less functional version of the same code from TokenTool. :)

Being a lazy so-and-so I settled for copying your DPI code (a dropdown with choices would be nice but this will have to do for now), but the two pdf-extraction codesets should probably be merged to a common library.

Anyhow, I've added a checkbox for 'Render and extract all pages from selected pdf as images?'. The code was indeed using plain Swing so adding it was no problem.

There is some funkiness around rescan meaning that a manual rescan after using the checkbox is most likely a good idea. Adding a forced rescan when the checkbox was selected grew painful on huge pdf:s (Pulp Chtulhu, I'm looking at you...) so I chose to not add it. This works, but it's awkward. My Swing-Fu has gone down the drain over the last decade or so of not using it. :) Any suggestions?

It *might* be a good idea to add a 'Force rescan' and 'Cancel current scan' buttons, huge pdf:s are a bother if you didn't intend to click on them. But, not in this issue. (I guess this will get a total rebuild when 'soon' comes. As in "most likely this panel will get an update       // with JavaFX soon(tm)..." :)

**Comment by xdy** [comment]
And, it seems that https://github.com/RPTools/maptool/issues/1537 would likely fix the remaining problems with rescan (as it would most likely remove rescan in favor of watching for changes)
So, I think this issue is ready for review.

**Comment by Phergus** [comment]
Re: the checkbox tooltip
`Render and extract all pages from selected pdf as images?`

I think this needs better wording.  That could describe what it does now.  Maybe `Extract each page from PDF to a single image.`

**Comment by xdy** [comment]
Sure, changed to that now.

**Comment by Phergus** [comment]
@xdy Go ahead and do a PR for it.

**Comment by xdy** [comment]
Created CR https://github.com/RPTools/maptool/pull/1577

**Comment by Merudo** [comment]
After this PR, the minimum columns my resource library can have is 3, instead of 2 in 1.6.1.

**Comment by Phergus** [comment]
@Merudo isn't that a function of the size slider on the left or has the panel minimum width changed?

Okay, it seems that the minimum width as changed.

**Comment by Merudo** [comment]
I'm pretty sure it's the long label, `Extract each page from PDF to a single image.`, that causes this.

**Comment by Phergus** [comment]
Doh.  It's the text label for the new checkbox.  Can that be set to wrap or perhaps get truncated?

**Comment by Phergus** [comment]
Heh.  Ninja'd

**Comment by Merudo** [comment]
`Extract one image per PDF page` might fit.

**Comment by JamzTheMan** [comment]
How about just making it `Render Pages`  (as it's really rendering the page vs extracting images) and just let the tool tip have the longer text above?
(I haven't loaded dev up yet, it only shows this option when a PDF is selected right? At least it seems that should be the behavior)

**Comment by Merudo** [comment]
Nope it is shown at all times.

**Comment by Phergus** [comment]
> How about just making it Render Pages (as it's really rendering the page vs extracting images) and just let the tool tip have the longer text above?

That's why you're the man.

> I haven't loaded dev up yet, it only shows this option when a PDF is selected right? At least it seems that should be the behavior

Might be less confusing but having it appear/disappear based on the file selected could be a bit weird as the panel changes size each time.  Doesn't the extraction start as soon as you select a PDF?

**Comment by xdy** [comment]
Yeah, it hooks into the same code as the image extraction.
I can definitely see useful follow-up issues to this one (e.g. the ones @JamzTheMan suggested about a separate pdf window), this is definitely the MVP version.

As for renaming it (and adding a tooltip with the full text), sure, I'll do that in a separate PR after lunch.

**Comment by Phergus** [comment]
Tested.  Pages extract as expected according to checkbox.  Issue with minimum width fixed.
