### ISSUE TITLE
Feature Request: Allow a DM to increase the maximum number of nested CODE:{} blocks

### ISSUE THREAD

**Issue by lynxworx** [RPTools/maptool#155]
I've been writing a lot of macros lately for my WEG Star Wars game, and I've had to adapt to some pretty weird coding practices due to the limitation on nesting CODE:{} blocks.  Can that limit be adjustable by preferences / campaign configuration?

I certainly wouldn't suggest making the sky the limit, but I found the current limit of 2 to be too restrictive, I wouldn't mind the option to be able to increase it to 5 or so, and have the GM be able to configure that.

**Comment by Azhrei** [comment]
MTscript is going away and will be replaced by JavaScript for anything significant.  I.o.w. MTscript will only be used to invoke JS, but all substantial scripting will be done in JS.

**Comment by wolph42** [comment]
there IS a way to have more than two nested code levels: http://www.lmwcs.com/rptools/wiki/Working%20With%20Two%20CODE%20Levels

**Comment by Phergus** [comment]
@wolph42 - you need to get that listed on the Main or Tutorials Page on the wiki.

**Comment by wolph42** [comment]
its in the macro cookbook, which I assume is where it should belong
http://lmwcs.com/rptools/wiki/Category:Cookbook
the cookbook IS listed on the main page.

**Comment by Phergus** [comment]
So it is.  I never remember the cookbook page is there.

**Comment by rkathey** [comment]
This should be resolved with MTSript2 in #245

**Comment by Phergus** [comment]
And almost two years later...

Should this be implemented?  If so, as a preference setting or what?

@Azhrei @JamzTheMan

**Comment by Azhrei** [comment]
This _will not_ happen in the current MTscript.  The regular expression-based parser has two levels instead of three for a reaso — trying to do three levels will quadruple the complexity of the code.  Given that kayila and Craig are working on a true grammar for the rewrite of MTscript, I don't see the point in this.  It would be nice to add, but it's like trying to retrofit a gasoline engine car to be a hybrid — just not practical.
