### ISSUE TITLE
Strange lighting when coloured light sources overlap

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#1550]
**Describe the bug**
Overlapping light source colours are blended only if they are different, whereas when they are the same colour the result is always that same colour. This creates an undesirable "Venn Diagram" effect when lights with colours for multiple ranges overlap.

**To Reproduce**
1. Modify the `Torch - 20` light source to use colours (under `Edit > Campaign Properties...`, `Light` tab):
   ```
   Torch - 20: circle 20#aaaaaa 40#666666
   ```
2. Add two PC tokens to the map, and attach a `Torch - 20` light source to each.
3. Disable Fog of War and set the map background to pure black. (Not necessary, but avoids distractions).
4. Place the tokens 80' apart, then 60', 50' and finally to 35' apart, observing the overlapping light behaviour. Notice how the brighter colour that is present only when the 20' colour and the 40' colour overlap, but no other blending occurs.

**Expected behavior**

Any one of these or some other reasonable behaviour:
1. Light source colours are always blended.
2. The colour for the smallest range is rendered, with no blending.

**Screenshots**

I've set up a map with a black background, and tokens placed at each of the ranges listed under "To Reproduce" (80' on the left, 35' on the right). Since the blending of the 20' colour and 40' colour is brighter than the constituent colours, we get this "Venn Diagram" effect when the tokens are less than 40' apart from each other.
![image](https://user-images.githubusercontent.com/7492219/79273982-ae9d7d00-7e58-11ea-9d7f-210082dc0358.png)

**MapTool Info**
- Version: 1.6.1
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 19.4

**Additional context**

```
==== MapTool Information ====
MapTool Version: 1.6.1
MapTool Home...: /home/kenneth/.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 250 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Vendor.: Oracle Corporation
Java Home...: /opt/MapTool/runtime
Java Version: 10.0.2

==== OS Information ====
OS Name........: Linux
OS Version.....: 5.3.0-46-generic
OS Architecture: amd64
PATH...........: /home/kenneth/.local/bin:/home/kenneth/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
Number of Procs: 6

==== User Information ====
User Name: kenneth
User Home: /home/kenneth
User Dir.: /opt/MapTool/app

==== Network Interfaces ====
Display Name..: wlo1
Interface Name: wlo1
Address...: fe80:0:0:0:ac8c:b884:10ef:1a47%wlo1
Address...: 192.168.43.246

Display Name..: lo
Interface Name: lo
Address...: 0:0:0:0:0:0:0:1%lo
Address...: 127.0.0.1

Host Address...: 127.0.1.1
Default Gateway: 192.168.43.1

==== Locale Information ====
Country.: Canada
Language: English
Locale..: English (Canada)
Variant.: 

==== Encoding Information ====
Default Locale:   en_CA
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(-1)

==== Internet Gateway Devices ====
	No IGDs Found!
```

**Comment by adyoungblood** [comment]
I found this issue while working on the lighting code, through the veritable web of issues/FREQs related to lighting. As far as I can tell, this is expected behavior. It may look strange when the lights are only white/grey, as they look similar to lights of different luminosity in the real world, but they're different colors. This becomes easier to see when setting the inner and outer rings to unexpected colors, like red and green:

![image](https://user-images.githubusercontent.com/16092423/149051689-1c45bd19-2468-4b1a-94eb-a398c58f59dc.png)
(Ignore the specific color blending in this screenshot, I'm working on getting colors to blend like real lights would, instead of how they do now)

**Comment by kwvanderlinde** [comment]
I see what you're saying, but even with the colours it still takes my eyes a while to figure out what is going on! I wouldn't say this is a pleasant experience.

The basic issue with current blending is that colors are only sometimes blended (from observation, maybe they technically are always blended in terms of implementation :shrug:). When different colours overlaps, it looks like they are added together as RGB to produce a third color. But when one color overlaps the same color, no blending is done and results in a seamless area of one colour.

By contrast, if overlapping colours were **always** blended (even when identical), we would be able to see, for example, the entire edge of all circles involved. But because of the blending is selected we can only see disjointed arcs, which I find very difficult to piece back together into a simple set of circles.

Going the other way, if colours were **never** blended, but had some kind of priority, your coloured example would look like this:
![149051689-1c45bd19-2468-4b1a-94eb-a398c58f59dc-reduced-colors](https://user-images.githubusercontent.com/7492219/149282166-452d1dc4-878e-4029-b5cb-06fd07c54b84.png)
I must admit I don't know how this would generalize to different overlapping sources, but at least I can now see what is happening in this case!

I've see you've been [working on proper additive blending](https://github.com/RPTools/maptool/issues/1895#issuecomment-1011798807). If that blending is always done even when two areas of the same colour overlap, that should resolve this particular issue.

**Comment by adyoungblood** [comment]
I had assumed separate colors were always blended, but you're exactly right! Two instances of the exact same color are not blended, but if you change the hex code ever so slightly they start blending. It appears to be a Java optimization of some variety, which is hopefully configurable.

An interesting side effect is that same color blending makes the resulting intersection appear lighter if the color is not already at the RGB maximum. This isn't technically intended, but I think it looks quite nice. Here's your original example, for context:
![image](https://user-images.githubusercontent.com/16092423/149390996-1ee579df-30a4-42c0-9814-1b93130a3e15.png)

**Comment by adyoungblood** [comment]
Okay, I think I've got it just right. There may be a few more subtle details to work out, but does look quite nice in testing.
![image](https://user-images.githubusercontent.com/16092423/149682706-0e2362f0-55d8-4808-912f-74936af4b32b.png)

**Comment by adyoungblood** [comment]
One addtional feature I've thought about is adjusting the alpha of each light based on how luminous it appears to be, i.e. white lights would be perfectly clear. There's [a whole lot of specifics](https://en.wikipedia.org/wiki/Relative_luminance) to this, but it would make blending nicer to the eye. One key point being that when all the colors of light blend together and create white, it's a bright white that washes out anything below it, whereas in the real world white light is clear.

**Comment by adyoungblood** [comment]
Or apparently I'm massively overthinking it and averaging the RGB values works better! Still not great by any means, though, so maybe a thought for another day.

**Comment by kwvanderlinde** [comment]
I've been testing this situation out since the PR was made and things are largely looking good so far.

There is one issue I've seen just a couple times where, when I open up a campaign, one light colour will completely override an overlapping colour rather than blending with it. It's pretty rare and I don't know how to reproduce it, but reassigning lights _seems_ to work around the issue. I don't see how it would be caused by this change, there may just be an underlying flaw that has just been exposed as a result. I'll try to share a screenshot if it happens again.

I also checked performance with a few different configurations of light sources in different arrangements. It seems consistently about 2x slower than the previous implementation, but we're still only talking ~20ms vs ~10ms per render.   This will be hardware dependent obviously, but at first glance it looks good for some common uses with relatively few light sources. Having lots of light sources is already taxing for other reasons but I'll check out that case as well sometime this week.

**Comment by kwvanderlinde** [comment]
> One addtional feature I've thought about is adjusting the alpha of each light based on how luminous it appears to be, i.e. white lights would be perfectly clear. There's [a whole lot of specifics](https://en.wikipedia.org/wiki/Relative_luminance) to this, but it would make blending nicer to the eye. One key point being that when all the colors of light blend together and create white, it's a bright white that washes out anything below it, whereas in the real world white light is clear.

> Or apparently I'm massively overthinking it and averaging the RGB values works better! Still not great by any means, though, so maybe a thought for another day.

Accounting for white lights somehow is going to be important. I'm finding it very easy to have both colourful and white lights disappear if I make the mistake of including a white light that can cover the other lights. It makes for a kind of confusing experience.

I tried out your idea of averaging RGB and I'd say it looks pretty good provided we don't have multiple lights overlapping. When multiple lights overlap, the simple average has the weakness that it matters in which order the lights are blending. But this could be worked around, e.g., by (ab)using the alpha channel to track how much weight to give each input (high alpha = low weight). I gave this a whirl and it seems to work pretty well, though the colours aren't quite the same as the simple average or the current 1.11.4 implementation, which surprised me a little.

Here's a showcase of some different blending implementations with the same map and lights and no tokens selected (sorry the view area is consistent). The colours are:
- white = `#ffffff`
- orange = `#ff5500`
- green = `#00ff00`

1.11.4:
![1550-1 11 4-blending](https://user-images.githubusercontent.com/7492219/150478015-f2be4278-7456-4969-a26d-40ccaf72cfb1.png)

develop:
![1550-develop-blending-no-selection](https://user-images.githubusercontent.com/7492219/150478037-b897fd33-ff02-4698-887b-673a2368af36.png)

pairwise RGB average:
![1550-pairwise-average-blending](https://user-images.githubusercontent.com/7492219/150478136-7bc8cbb8-6088-4e30-8f5d-d1159d7747c3.png)

weighted RGB average:
![1550-weighted-average-blending](https://user-images.githubusercontent.com/7492219/150478160-a5a01199-e703-4366-bbe8-67b58d342ef9.png)

**Comment by Phergus** [comment]
Overall I like the weighted average best though I'm not clear on why the green came out so much darker in the overlap with orange and the green-only area.

**Comment by FullBleed** [comment]
I think I like the pairwise RGB or the 1.11.4.  That dark green just doesn't seem light "light" to me... and the other sources look more like light as well.  I suspect monitor settings might have a significant impact on these effects though.

**Comment by kwvanderlinde** [comment]
I need to do some more investigation into our rendering code because the results are not entirely consistent. Sometimes the colors are very pale and sometimes very bold. E.g., here is another trial of the weighted average that is much more saturated:
![1550-weighted-average-blending-saturated](https://user-images.githubusercontent.com/7492219/150621773-b87c6d55-8bc3-4fc5-a2e2-34b5818fb700.png)

It goes the other way as well, sometimes the pairwise average is similarly desaturated.

If I restore FoW and then re-render the lights, I sometimes get totally different results. As I said, I'll be looking into why this is. As far as I can tell by debugging, the blending of the lights themselves seems to be consistent, but something about how it is combined with everything else is causing trouble.

**Comment by dorpond** [comment]
Do me a favor and consider of how auras will function when mixed with lighting as well. During my sessions, there always seems to be a paladin radiating an aura of some sorts (always on, 24x7). I’m not really sure how it should work, but since you are putting much thought into all of this, perhaps you can come up with something brilliant :)

**Comment by kwvanderlinde** [comment]
I did some more work on the weight average. Rendering has been made consistent and looks like this:
![image](https://user-images.githubusercontent.com/7492219/151226869-f1a60c82-a87c-4312-b5b1-5853b7d9f7ff.png)

I'll admit, the colours do look little faint. But don't blame me, blame the mage for holding a 300' whitish light that drains the color! Things look a lot better in a more typical case where there isn't a giant light source covering literally everything other light source:
![image](https://user-images.githubusercontent.com/7492219/151227089-95016734-2a45-42a0-942e-bf796d5c003d.png)

For comparison, here's the same thing on 1.11.4:
![image](https://user-images.githubusercontent.com/7492219/151228236-7ad2d942-3cda-4ca8-af3b-99b653cc8390.png)

I'm not sure yet why the hard FoW is generally darker, but that only affects the GM view.

@FullBleed 
> I think I like the pairwise RGB or the 1.11.4. That dark green just doesn't seem like "light" to me in the weighted... and the other sources look more like light in pairwise as well. I suspect monitor settings might have a significant impact on these effects though.

I don't know if this changes your opinion, but the "dark green light" is actually the portion of the green darkness covered by FoW. In a player view, that portion would be completely black in all implementations.

**Comment by FullBleed** [comment]
My bad.  I thought that was supposed to be "light"... if it is, essentially, colored "darkness" then it looks pretty much as I'd expect.

I appreciate you guys taking on this code, I know things get tricky and that there is a fair bit of hair-splitting that goes on in an attempt to get more attractive results.  

I did have a couple additional questions though:

1)  Do you think MT could use some in-app graphics adjustment settings?  I know users can tweak their monitors or OS for some of this, but in-app settings seem a better option... especially when the minutia can often boil down to "opinion."  Sometimes I might be playing an MMO with some people and they're complaining, "I can't see anything in here!"  To which I might reply, "Go tweak your gamma up a bit."  So when you mention that the FoW is coming up darker with the latest change, that might be fine for many... but others might have a problem with it... and being able to adjust an in-app slider for contrast/brightness/gamma, etc. might mitigate that.  Not to mention that individual maps also might just be more difficult to "read" using any defaults... so in some cases a 10% tweak one way or another might be all that's needed to make it more comfortable for any given user's experience/setup.

2)  Do any of these recent changes get us any closer to implementing light source fades/transitions?

**Comment by adyoungblood** [comment]
1. Most likely, yeah. Many of the changes I try are up to personal taste, i.e. they may not be the universal preference. For the moment, I think sticking to basic principles (RGB additive blending, for example) will have the best results with minimal configuration.
2. Yes! Before, the issue was that drawing a light source fade would be more like drawing darkness onto light, rather than the other way round. This resulted in some very odd looking boundaries when the edge of a gradient light wasn't touching fog. Now it should be easier to draw an even fade where necessary, though I'll get back to you on that one.

**Comment by kwvanderlinde** [comment]
Hmm, turns out averaging kind of sucks, in that the average of the same colour is (obviously) the same colour. In other words, averaging gives rise to same confusing behaviour in the initial bug report. This equally affects a simple average or a weighted average like I've been experimenting with.

Unfortunately I'm not going to be able to continue experimenting with this for the foreseeable future. My time has to be focused elsewhere so MapTool development is going to have to take a back seat.

---

@adyoungblood The current state of lighting that you created (`BlendingComposite`/`BlendingContext`) is a pretty good basis, it's just unfortunate that it drives colours to white and that white obscures all other colours. We might be able to use a different [Blend mode](https://en.wikipedia.org/wiki/Blend_modes) to get better results (current behaviour is called "**Lighten Only**" in the linked article). I was able to do some quick experiments, but the order-independent **Multiply** and **Screen** - while they look alright for middle colors - still drives results towards either black or white, with black or white dominating everything else. Some of the soft light options look pretty decent, but are very much dependent on rendering order. 

All that is to say that I think it would be good if we could enforce a stable rendering order for lights. E.g., always render lights according to the z-order of the tokens. That way we could use whatever sort of blending we want (even ones where order matters) and not have to worry about surprising behaviour when lighting needs to be reclaculated.

**Comment by Phergus** [comment]
Tested and overlapping colored lights much improved.  Any further issues should go on new ticket.

**Comment by q-station** [comment]
I've just started working with maptools again after a long time away and noticed this issue.  Having read through the comments, I thought I would chime in some idea on this topic as I can understand the frustration.

While I have been a programmer, I don't know anything about maptools (what language iw as coded with, how the coding is structured, etc.) so I can't offer any specific suggestions relating to the way the code is written, but as a professional inematographer, I do understand lighting and have some conceptual suggestions that might help... though I don't know if it would require a full recode of the lighting algorythms... I also don't know if this has been tried before, or how much overhead it will require.

Right now, it appears (and please correct me if I'm wrong) that the lighting is simply attempting to blend the colors of the light sources and overlaying them on top of the map image.  From a film standpoint, that's not really how light works of course, so I don't think that approach will ever achieve a natural lighting look.

What should really be happening is that the lighting should be changing the rgb value of the underlying pixels on the map by a certain amount to simulate the way light refects off a surface.

To use a simplified example, let's say that a light source would add 50 to a pixels value in the inner range (full illumination 0-20' for a torch) and only 25 to a pixels value in the outer range (less illumination from 20'-40').  This should be done for *each* light source.

Llet's say we have an even colored floor with an RBG value (in decimal) of 100, 100, 100

We place two light sources on this floor.

The inner range of each light source will add 50 to each rgb value (lightening it), so the "fully illuminated" area floor value will become 150, 150, 150 beneath each light source.

The outter range off each light source will add 25 to each rbg value (slightly lightening it), so the "partially illuminated" area floor value will become 125, 125, 125.

Now, where the outer area of these two light sources overlap, the effect on the pixel values will become cumulative: 150 each (100 + 25 + 25), while the area where the full illumination areas overlap it will become 200 each (100 + 50 + 50).  This gets much closer to the way light interacts in reality with one caveat: light doesn't add linearly, so where two fully illuminated areas overlap, it will be unnaturally bright.

The simple solution to this issue would be to only add the *greatest* value of all the light sources to the base pixel value in the fully illuminated range. So if all of the light sources have the same add value, only ONE is used in the calculation and the rest is ignored. Alternatively you could simply cap the add value to a fixed amount, so that any combined value greater than a certain value gets clamped before getting added to the underlying pixel rgb values.

The advantage of this is it will work consistently with ANY colored light source as the add values are in rgb format as well, thus a RED light would have a value of 50, 0, 0 while a BLUE light would have a value of 0, 0, 50.  Overlapping these two lights would result in an add value of 50, 0, 50 which is exactly what you would expect.

Anyway, that's my take on the lighting issue. Of course it's easy for me to through this out there because I don't understand how it's currently coded and what it would take to make that kind of a change. But still, I thought I would put it out there with the thought that I might be approaching it from a different perspective. :)

**Comment by q-station** [comment]
I just thought of a possible solution to this issue, presuming that currently the lights are simply subtracting from the fog of war, or something similar.

Since there are two rings for each light, the inner (full illumination) and the outer (partial illumination), simply render the lights in two passes. First, draw all of the outer, partial illuminations, and then draw the inner (full) illuminations.  The full illuminations will simply overwrite the shadowy illuminations on the second pass and that will achieve the desired result.
