### ISSUE TITLE
Variable names can't start with "tru" or "fal"

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1736]
**Describe the bug**
Assigning a variable with a name starting with `tru` or `fal` causes the message `line 1:4: expecting 'e', found ' '`.

**To Reproduce**
Type any of the following:
```
[tru = 0]
[trusted = 'friend']
[trumpCard = 2]
[truce = 1]
[fal = 0]
[falcon = 2]
[fall = 3]
```

**Expected behavior**
No error for starting a variable name with `tru` or `fal`.

**MapTool Info**
- Version: 1.6.1, 1.7.0 A2
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Phergus** [comment]
Been that way since 1.3. You can use `true` and `false` in logical comparisons.

`[r: if(0 == true,"yes","no")]`

**Comment by selquest** [comment]
I've never worked with antlr, so I'm not sure why it's choosing to identify a token type from only a prefix, whether we can change that with any kind of setting, or whether it's possible to restructure the definitions file so that it would fall through properly to other token types instead of producing this error...

The problem spot in the actual java code that gets generated though is in `ExpressionLexer.java`:
```java
if ((LA(1)=='t') && (LA(2)=='r') && (LA(3)=='u')) {
	mTRUE(true);
	theRetToken=_returnToken;
}
else if ((LA(1)=='f') && (LA(2)=='a') && (LA(3)=='l')) {
	mFALSE(true);
	theRetToken=_returnToken;
}
```
Changing those lines to:
```java
if ((LA(1)=='t') && (LA(2)=='r') && (LA(3)=='u') &&(LA(4)=='e')) {
	mTRUE(true);
	theRetToken=_returnToken;
}
else if ((LA(1)=='f') && (LA(2)=='a') && (LA(3)=='l') && (LA(4)=='s') && (LA(5)=='e')){
	mFALSE(true);
	theRetToken=_returnToken;
}
```
This seems to work... if tokens like `fallDamage` don't get incorrectly matched to `false`, the comparison continues to try and match it against operators and then ultimately conclude correctly that it's an identifier.  In short, the same path that every other variable takes.

Anybody sufficiently comfortable with the build process to have it run the antlr job, patch the generated code, then build (skipping the generateGrammarSource gradle task)?  That's a super hacky way to do this that I wouldn't begin to suggest if the grammar spec was still being actively supported, but it might be a way to whack this kind of weird quirk before welcoming in the triumphant parser 2.0.

@Azhrei since we were briefly discussing on Discord

**Comment by Azhrei** [comment]
Thanks for the mention.

Looking at `expression.g` — why is the lexer stuck on checking just three characters?  (Maybe a bug or limitation of the old antlr?)  I never came up with an answer to that question.

Whether to fix it in this hacky way will be up to the folks working on MTs2.  If they think it's coming sooner as opposed to later, I'd leave this alone...

**Comment by cwisniew** [comment]
This is due to the fact that the lexar rules for TRUE and IDENTIFIER, FALSE and IDENTIFIER are ambiguous. 

There is simply no way for the lexer to know if "true"/"false" should be a variable or an identifier because the grammar says its both. 
When the lexer gets to something like 'falling' it gets the 'f' and has to choose between FALSE or IDENTIFIER, since the lookahead for the lexer is 3 it can only look at the first 3 letters to make a decision, which are 'fal' which of course still matches FALSE and IDENTIFIER, and in the case Antlr follows the general rule for the majority of the lexers out there the most specific rule wins.

I have created a PR for RPTools/parser#50 which changes the lookahead to 5 for the lexer, but in Antlr lookahead is done by comparing to the token so since 'true' only has 4 letters there will be no fifth character to perform lookahead on so it will only be done against 4. This means 'truely' still matches TRUE and IDENTIFIER.

So now falling = 1, trusty = 1 should work. But truely = 1 and falseSenseOfSecurity = 1 will still have problems. This though will be a lot less of a problem than staring with just 'tru' or 'fal' and doesn't require large changes to the parser to remove the ambiguity. The correct fix would be to not tokenise true and false but instead let the parser decide what is an identifier and what is a boolean constant.

**Comment by selquest** [comment]
> This though will be a lot less of a problem than staring with just 'tru' or 'fal' and doesn't require large changes to the parser to remove the ambiguity.

Agreed - at the very least it's a lot more easily explained that you can't use `falseSense` as an identifier than it is that you can't use `fallDmg`.

Unfortunately the specific way that `falseSense` would now fail has me rethinking this a bit: `[r: falseSense = 4]` will no longer produce an error, but instead just print `0`.  Given the choice I'm not sure this is an improved user experience - we've traded an odd error message for just inexplicably incorrect behavior.  At least with the error message there's something users can search for to figure out what went wrong.

**Comment by selquest** [comment]
Following up on that last comment to say that I'm actually surprised `falseSense = 4` would resolve to `0` (`false = 4` throws a NPE), but that's what I'm seeing when adding a unit test to `ParserTest`:
```java
  public void testIdentifiersAreNotBooleans() throws ParserException {
    Parser p = new Parser();
    evaluateExpression(p, "x = 3", new BigDecimal(3)); //passes
    evaluateExpression(p, "fallDamage = 4", new BigDecimal(4)); //passes with these changes
    evaluateExpression(p, "falseSense = 4", new BigDecimal(4)); //fails with these changes, gets '0' instead of '4'?
  }
```

**Comment by Merudo** [comment]
Good catch @selquest.  `[r: falseSense = 4]` returns 0 instead of 4 or an error in current develop (8/16/2020). It works fine in 1.7.

Similarly, `[r: trueSight = 4]` returns 1.

I'm not sure which PR is to blame for this; maybe RPTools/parser#37 ?

**Comment by cwisniew** [comment]
Doh!! Looks like I am going to have to make more invasive changes to the parser then...

**Comment by Phergus** [comment]
Tested.  Variable names may now start with `tru`, `true`, `fal`, `fals` or `false` without producing an error and work correctly in expressions.
