### ISSUE TITLE
token VBL does not rotate correctly with image translated in layout

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#1760]
**Describe the bug**
Changing facing rotates VBL around different point to image in layout or rotation point in VBL JSON
**No rotation/facing change**
![image](https://user-images.githubusercontent.com/45483160/81137481-94574a80-8f91-11ea-820b-4150ff29f635.png)
**With rotation/facing change**
![image](https://user-images.githubusercontent.com/45483160/81137577-d7b1b900-8f91-11ea-9ce7-a5a7df8b0c17.png)

Likely related to [issue 1757: moveToken() does not work correctly with image translated in layout](https://github.com/RPTools/maptool/issues/1757)

Have tried with VBL generated automatically and with JSON shapes polygon and rectangle in setTokenVBL. With various rotation points
e.g. '{"shape":"polygon","close":0,"thickness":2,"r":0,"rx":0,"ry":65,"fill":0,"scale":0,"points":[{"x":0,"y":65},{"x":800,"y":65}]}' 

**To Reproduce**
Create VBL line on token
Translate token image in layout
![image](https://user-images.githubusercontent.com/45483160/81138172-be117100-8f93-11ea-8485-0b94fe7d8df9.png)
Change token facing

**Expected behavior**
VBL to rotate around point set in JSON or center point displayed in layout.

**Screenshots**

**MapTool Info**
- Version: 1.5.10

**Desktop (please complete the following information):**
 - OS: Win10

**Comment by melek** [comment]
Is this the same as #1049? 
 
  On Tue, May 5, 2020 at 9:20 PM, bubblobill<notifications@github.com> wrote:   


Describe the bug
Changing facing rotates VBL around different point to image in layout or rotation point in VBL JSON
No rotation/facing change

With rotation/facing change


Likely related to issue 1757: moveToken() does not work correctly with image translated in layout

Have tried with VBL generated automatically and with JSON shapes polygon and rectangle in setTokenVBL. With various rotation points
e.g. '{"shape":"polygon","close":0,"thickness":2,"r":0,"rx":0,"ry":65,"fill":0,"scale":0,"points":[{"x":0,"y":65},{"x":800,"y":65}]}'

To Reproduce
Create VBL line on token
Translate token image in layout

Change token facing

Expected behavior
VBL to rotate around point set in JSON or center point displayed in layout.

Screenshots
If applicable, add screenshots to help explain your problem.

MapTool Info
   
   - Version: 1.5.10

Desktop (please complete the following information):
   
   - OS: Win10

**Comment by Phergus** [comment]
This fixed a while ago.
