### ISSUE TITLE
Fix Show as Player so GM can reliably see what players see

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1838]
**Describe the bug**
"Show as Player" for GMs is notoriously unreliable, and what is displayed does not match what players see.

For example, the Initiative Panel and Map Explorer do not currently take into account "Show as Player".

**Expected behavior**
The "Show as Player" show the GM a view corresponding to what players see. More precisely, it should behave as if all tokens with an owner also had the GM as an owner.

Alternatively, the "Show as Player" menu could be replaced with a submenu listing all players. The GM could then select which player(s) to view the map as.

**MapTool Info**
- Version: 1.6.1, 1.7.0 beta, develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
PR #1839 adds the functions `MapTool.getPlayer().isEffectiveGM()` and `MapTool.getPlayer().getEffectiveRole()`, which will make it easier to manage code so that it takes `Show as Player` into account.

**Comment by Merudo** [comment]
PR #1840 fixes this for the Map Explorer.

**Comment by Merudo** [comment]
PR #1841 fixes it for the Initiative Panel.

**Comment by Phergus** [comment]
Show as Player was only ever about the Map view and not an actual role swap.  What is the purpose of having the Initiative and Map Explorer panels conceal information from the GM?

**Comment by Merudo** [comment]
By checking "Show as Player", the GM could quickly see what tokens are visible in the Initiative and Map Explorer panels. This information would require several properties to be checked for each token otherwise (token could be invisible, on the token layer, not owned, etc).

Map Explorer would quickly lists which PC tokens are visible to players on the map.

Initiative Panel would let the GM know if some tokens are not visible in the initiative for some reason. Maybe they are on the wrong layer or something.

My understand is that the "Show as Player" option is used for the DM to quickly check if something is not displayed correctly.

Why not have that be the behavior for the Map Explorer and Initiative Panel? To me, that's more useful than showing information the GM can already see in his usual GM view.

**Comment by Phergus** [comment]
Found the conversation on Discord.

Map Explorer already shows what is and isn't flagged as Visible to Players.  As does the Initiative panel.  The Map Explorer sorts first by Visible and Not Visible and then by name within those categories.  Initiative panel changes the shading.

> My understand is that the "Show as Player" option is used for the GM to quickly check if something is not displayed correctly.

In the map view.  Objects, tokens and background stamps that don't have visibility set correctly can quickly and easily be fixed from Map Explorer and then see that change reflected in the map view.  You can easily toggle back and forth the visibility of a map element to check alignment from the Map Explorer.

If you change it so that the Map Explorer now hides information from the GM they can't fix what is wrong in the map view by going to the Map Explorer.  They instead have to toggle back out of View as Player, make the change and go back in to View as Player to confirm.

**Comment by Merudo** [comment]
I see. This makes sense.

By the way some of the shading does not work. I suppose it could be fixed instead.

I'll change a few things and make new PRs. PR #1839 is still helpful as it provide a clearer method to tell if the GM is currently using Show Player View. The PR doesn't involve the Initiative or Map Explorer at all.

**Comment by Phergus** [comment]
Cleaning up the internal checks for the viewing mode is a good plan.

**Comment by Merudo** [comment]
PR #1840 now modified, does not use Show as Player anymore.

**Comment by bubblobill** [comment]
This is why I proposed [1796](https://github.com/RPTools/maptool/issues/1796)
