### ISSUE TITLE
Maptool registry MySQL database

### ISSUE THREAD

**Issue by Antafes** [RPTools/maptool#186]
Hi everyone,
maybe you should consider securing your MySQL database used for the Maptool registry. The last time my server crashed, I got the following message in the error logs:

`<b>Warning</b>:  mysql_query() [<a href='function.mysql-query'>function.mysql-query</a>]: Access denied for user 'XXX'@'localhost' (using password: NO) in <b>/home4/rptools/public_html/services/maptool_registry-1_3.php</b> on line <b>131</b><br />`

If this is the wrong place to submit those issues, please point me to the correct place.

**Comment by Azhrei** [comment]
No, this is a fine place to report any issues with MapTool.

Yeah, that code is really old... and really wrong.  I've updated it to use MySQLi (which means I'm surprised that it reported the problem in `mysql_query()`, since that doesn't exist anymore), but it needs to use prepared statements as well.  I did think that every field was protected by `real_escape_chars()`, but apparently not. :(

Did this happen Saturday night?  I had some issues with PHP version support and it got switched back and forth a few times and that could've triggered the error as well.  `mysql_query()` is deprecated as of PHP 5.6, so I had to force PHP 5.3 for that service until I had everything switched over.  But it would've been handled by 5.6 for a few minutes until I figured out there was a problem.

In any case, it definitely does need to use prepared statements, I'm just surprised by the `Access denied` error message, as credentials are not supplied by outside data and couldn't be tainted...

**Comment by Azhrei** [comment]
I see the timestamp on the file was Sunday night, around 6:30pm CDT (GMT-5).  There shouldn't be any errors after that, since I had converted everything to MySQLi by then.

Thanks of rthe offer, but it's no big deal.  I just hate the whole `bind()` thing for prepared statements in PHP; I'll build a function to do that and then the rest of the code will be simple.  (Python is nice because you can list the data as parameters and they are automatically bound into the prepared statement.  I'll likely model my solution after that approach.)

I'd love to update all the way to PHP 7.1, but there's just too much code that I can't guarantee will function okay.  In addition to the phpBB forum (which can probably handle 7, now that I just updated it), there's also the WordPress site and all of its plugins, along with a bunch of custom code for the WP Downloads page, the Server List page, and others.  Then the Hessian library that is used to talk to MT is PHP and old (that should be updated too, but I don't want to do that unless MT is updated at the same time, since they could break).

Sigh.

**Comment by Antafes** [comment]
WordPress itself shouldn't have any problem with PHP 7, running it for myself with PHP 7. Don't know if PHP 7.1 or 7.2 will make any problems.
But it also shouldn't be any problem to only switch some parts over to PHP 7 or higher. I'm doing that myself with multiple sites on my server. With nginx it's pretty easy, don't know about apache, haven't used that in a while ^^

**Comment by Phergus** [comment]
Status?

**Comment by Azhrei** [comment]
I have plans to replace all of this with a REST interface, once time permits.  Since this appears to have been transient, we can probably close this (but do we want to keep the reminder?).

**Comment by Phergus** [comment]
Leaving open for now and marking as deferred.

**Comment by cwisniew** [comment]
Closing as this is no longer relevant (old server registry doesn't exist since the vulnerability issues)
