### ISSUE TITLE
With dark theme, text while typing and text output in Chat window is black

### ISSUE THREAD

**Issue by rogue-ronin** [RPTools/maptool#1904]
**Describe the bug**
With dark theme, text while typing and text output in Chat window is black

**To Reproduce**
1. Apply RT Default Dark theme
2. Type something in Chat window (eg: /r 1d7)
3. Text being typed is black, text output is black

**Expected behavior**
Text should be the same white as the theme uses elsewhere

Note: if I impersonate a token, the text spoken color is correctly applied, but the name of the token is also black instead of white. I expect it to be white, not black.

**MapTool Information**
MapTool Version: 1.7.0
MapTool Home...: /home/rogue/.maptool-rptools
Max mem avail..: 3 GB
Max mem used...: 239 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

**Java Information**
Java Vendor.: Oracle Corporation
Java Home...: /opt/MapTool/runtime
Java Version: 10.0.2

**OS Information**
OS Name........: Linux
OS Version.....: 5.6.12-1-MANJARO
OS Architecture: amd64
PATH...........: /home/rogue/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
Number of Procs: 4

**Locale Information**
Country.: United States
Language: 
Locale..: United States
Variant.: 

**Encoding Information**
Default Locale:   _US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

**Display Information**
Number of Displays: 2
Display 1: 1680x1050(-1)
Display 2: 1680x1050(-1)

**Comment by Azhrei** [comment]
This is unrelated to your bug...

> **OS Information**
> OS Name........: Linux
> OS Version.....: 5.6.12-1-MANJARO
> 
> **Locale Information**
> Country.: United States
> Language:
> Locale..: United States
> Variant.:
> 
> **Encoding Information**
> Default Locale: _US

This is interesting; I would not have expected the default locale to be `_US`.  Would you mind opening a command prompt window and pasting the output of `locale` into a post here?  I'm curious how the Java runtime came up with that...  Thanks.

**Comment by rogue-ronin** [comment]
```
rogue@monarch [~]: locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC=en_US.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.utf8"
LC_MONETARY=en_US.UTF-8
LC_MESSAGES="en_US.utf8"
LC_PAPER=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_ALL=
```

**Comment by aliasmask** [comment]
semi-related to this is also the background color of an MT roll with tooltip. It's always white. I haven't tested all the cases but something like `[1d20]` will always have a white background.

**Comment by melek** [comment]
Also related to this.. It would be helpful to be able to define emote colors (defaults with a Black asterisk and Green text) for themes, and to be able to access that color in a macro so I can match the theme colors.

I simulate a lot of emotes :P

**Comment by crogonint** [comment]
Well.. I can't find the chat color in TinyCP after an exhaustive search, but I did figure out that it's using the JTextPane colors, and that you can simply lighten the box you type text in to with TextPane BG Color. The chat history box uses EditorPane BG Color. I just switched both to the 'Disabled Color' so that I can read the freaking chat text.
Pretty sure the Token labels use the same text color as well, but I'm not willing to change my entire 'dark mode' to light gray. :P 
![maptool chat box](https://user-images.githubusercontent.com/23371790/100538287-120fcb80-31ec-11eb-84d1-1adc24a70675.png)

**Comment by Rukbat16** [comment]
The issue persists in version 1.10.4, on Windows.

MapTool Version: 1.10.4

OS: Windows 10 Home x64

Locale: EN-GB

Number of Displays: 1
Display 1: 1920x1080

**Comment by FullBleed** [comment]
@crogonint How did you edit just the TextPane BG Color?

We can get at 300+ theme color element in MT with getInfo() but we can't edit them inside MT... and we can't open .theme files with a text editor... so I'm not sure how to do just that element.

**Comment by crogonint** [comment]
Hmm.. I was fiddling around with settings. The ones that you're probably looking for weren't in any of the obvious places. I just dug around for scripts and references for things that might work, and set them manually.

I seem to recall that some of the stuff was persistent, but some stuff was not, and needed to be set every time. 

I think MapTool has gone through a full version change since then, so everything MAY have changed up. Ideally, the devs ought to have a full list of the various color settings somewhere.

AH yes!! I mentioned that Reverend figured that one out! It's in the Discord somewhere. If you search my user name and "color" it should be relatively easy to find. :)

**Comment by FullBleed** [comment]
> AH yes!! I mentioned that Reverend figured that one out! It's in the Discord somewhere. If you search my user name and "color" it should be relatively easy to find. :)

@crogonint Yeah, found that post... but still not understanding how you did this:

> The chat history box uses EditorPane BG Color. I just switched both to the 'Disabled Color' so that I can read the freaking chat text.

What tool did you use?  You can't do that within MT and I don't know how to edit the .theme file outside it (tinylaf doesn't let you edit all 300 theme elements last I checked.)

**Comment by crogonint** [comment]
Well that's a good question right there.

Really good.

Yep.

Possibly the java console? I was helping with the weather project back when I wrote that, so likely it was something related to MapTools particular flavor of java. Where are the JTextPane colors defined?

I can tell you that the setting IS persistent, because my current chat text retained the colors above when I checked it. Actually.. after digging around in my custom jar, the ONLY change I see is a copy of RT_Default_Dark.theme dated 11/29/2020 ...which is the same date I posted the above. Best guess. Between Reverend and myself, somebody made a custom theme file to solve the problem..??
[RT_Default_Dark.zip](https://github.com/RPTools/maptool/files/8673804/RT_Default_Dark.zip)


Nothing else jumped out at me. I DO have the MapTool Launcher installed, so I AM pretty sure that I was fiddling around in the Java console, like I mentioned earlier. 

What DID jump out at me.. is that someone ought to do a text search of the contents of the jar file for "mlewis" and "frank".. then make the appropriate adjustments. (This is in 1.7.0) There are a few references to local files scattered around that are um.. unintentional.

**Comment by crogonint** [comment]
You can get the Java Console by using the MapTool Launcher. (Which is a
separate program.)

I honestly don't recall what TInyCP was.. It's a safe bet that it was one
of the tools I was using while helping with the weather stuff. I would be
shocked if the people on the Discord didn't know what it was, they were the
ones telling me how to do this stuff. ;)
 - James T. Long

------------
There are 10 kinds of people in the world - those who understand binary,
and those who don't.
