### ISSUE TITLE
MapTool is installed into the wrong location by default

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#1922]
**Describe the bug**
Per Apple’s guidelines, applications should be installed into `/Applications` for applications usable by all users, or into `~/Applications` for applications usable by a single user.  MapTool currently defaults to `~/Desktop` when installed via the **.dmg** file.  (Installing via **.pkg** doesn’t allow the user to specify the location and always uses `/Applications` in my testing.)

**To Reproduce**
1. Install MapTool on macOS via the **.dmg** file and note that `Desktop` is the option presented to the user.

**Expected behavior**
MapTool should adhere to the platform’s guidelines as much as it can if there are no portability issues.  (For example, **MAPTOOL_DATADIR** should be under `~/Library` on macOS, but that would complicate cross-platform support.  This correction doesn’t introduce any support issues.)

**MapTool Info**
- Version: All since 1.5?  Maybe earlier?

**Desktop (please complete the following information):**
 - OS: MacOS only
 - 10.15, but applies to all versions

**Additional context**
See [Apple’s guidelines](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW6)

**Comment by JamzTheMan** [comment]
You may need to open the issue with the JDK community and have them change the defaults for jpackager.

**Comment by Azhrei** [comment]
Good point.  I haven't tried it with JDK14 and our unreleased 1.8; this is for previous configurations where we _do_ set the location manually in our configuration files.  But I'll do that this afternoon.  Thanks for the idea. :)

**Comment by JamzTheMan** [comment]
> Good point. I haven't tried it with JDK14 and our unreleased 1.8; this is for previous configurations where we _do_ set the location manually in our configuration files. But I'll do that this afternoon. Thanks for the idea. :)

I didn't set the locations for javapackager either btw but they may have changed it in either case for jpackager.

All we set is whether it installs per user or not and we choose per user vs system because that generally requires less permissions, but ultimately the installer chooses the default location per OS.

Since installers had more options, for instance, in Windows we had the option to prompt the user before installing, but that doesn't exist for all installers.

We have even slightly less options with the new jpackager. But it is still incubating so the JDK community may be open to requests such as these? ( Be surprised if they wasn't already an open issue for this)

**Comment by Azhrei** [comment]
> We have even slightly less options with the new jpackager. But it is still incubating so the JDK community may be open to requests such as these? ( Be surprised if they wasn't already an open issue for this)

Yep, done (#9065185).  Thanks. 🙂

**Comment by thelsing** [comment]
@Azhrei The bug report in the jdk is marked as resolved. Is this issue still present?

**Comment by Azhrei** [comment]
It seems there are options we can apply when building, so I'm closing this.  (But I won't be testing those options any time soon.)
