### ISSUE TITLE
Repos error message missing end '

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#1996]
**Describe the bug**
If the repo is not valid, the log message reports the URL with a missing `'`.

**To Reproduce**
1. Add an invalid repo to a campaign, such as `http://dl.dropboxusercontent.com/s/bpujigvo57q1gzs/index.gz`
2. Load the campaign. It shows an error such as
```
ERROR net.rptools.maptool.model.AssetLoader - I/O error retrieving/saving index for 'http://www.rptools.net/image-indexes/gallery.rpax.gz
```
3. Notice the `'` in front of the url, but not at the end of it.

**Expected behavior**
There is a `'` both in front and at the end.

**MapTool Info**
- Version: 1.7, devlop
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
One thing I noticed is that the URL doesn't seem to be built correctly for windows:

` REPO_CACHE_DIR.getAbsolutePath() + "/" + new MD5Key(repository.getBytes())`

this return something like

`C:\Users\username\.maptool-RPTools\repoindx/17f3090ccaad76ccbf6a638e0c3b7a73`

**Comment by Merudo** [comment]
This could be fixed together with #715

**Comment by cwisniew** [comment]
@Merudo About the /... It depends, its a common misconception that you have to use \ for windows paths in java this is not the case (and genrally not desirable as its clumbsy and more prone to portability issues as you introduce a special case for one OS). / Works for both unix and windows, \ only works for windows. The path is abstract so not necessarily the path string required by the OS (although the java doc does say it will also respect underlying OS seperators which is why \ works on windows). 

If it was failing then it should have popped up when any windows user uses a repo (unless the exception is ignored, which is hopefully not the case). 

If it truely gives you the heebie geebies I suppose you can change it but please use the Paths.get() function to build the path, not checking OS and changing to an undeed \

**Comment by Phergus** [comment]
As the index files are likely to be less than 10k in size it's probably not worth the effort.

**Comment by Phergus** [comment]
Tested.  Error message localized and no longer has unmatched quote mark.  Error dialog opens when server is running otherwise message is printed to Chat window.

![image](https://user-images.githubusercontent.com/34379254/84794341-5c411f80-afb3-11ea-9816-a49d9a2cab78.png)

![image](https://user-images.githubusercontent.com/34379254/84794499-8d215480-afb3-11ea-85a0-62b2d3719c4a.png)
