### ISSUE TITLE
Add option to have "Lock Player Token Editor" checked as the startup default.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#2001]
**Is your feature request related to a problem? Please describe.**
I always want to have "Lock Player Token Editor" (found under the "Tools" menu) checked -- and I keep forgetting to check it.

**Describe the solution you'd like**
I would like to have MapTool startup with "Lock Player Token Editor" checked as the default.  I suggest adding an option to Preferences on the Application tab to enable GMs to set a default.

**Describe alternatives you've considered**
I keep trying to remember to set that to checked each time I start MapTool to run a game, but I keep forgetting to do it.

**Additional context**
The "Lock Player Token Editor" feature is critical because it prevents players from editing their tokens, which can create concurrency problems if the GM is trying to modify the token through his Token Editor or via macros.

**Comment by FullBleed** [comment]
The "Lock Player Movement" setting (located in the same place) also fails to remember previous settings.

Drives me crazy since I always forget to do it until someone moves when they shouldn't... and then I have to go and move them back and Lock Movement.

Is there a technical limitation keeping MT from remembering these settings from the menu bar?  Seems like some other menu items are remembered.

**Comment by FullBleed** [comment]
So, had a question tonight on discord about token names showing up permanently...

Turns out there is a setting for "Show Token Names" under the "View" menu bar drop-down.  Seems like that setting should be under "Tokens" in preferences... but, regardless, the point is that's an example of a menu bar preference that is remembered.  So, hopefully, "Tool>Lock Player Token Editor" and "Tool>Lock Player Movement" can both get setting memory fairly easily.

**Comment by Azhrei** [comment]
I would prefer Show Token Names to stay where a single keystroke and/or menu option can toggle it.

I don’t like it on in most cases as it clutters the screen too much at the zoom level I typically use, but it’d be a pain to have to open Preferences every time I want to toggle it (which is generally 3-4 times per game session as a player and more as a GM).

**Comment by FullBleed** [comment]
> I would prefer Show Token Names to stay where a single keystroke and/or menu option can toggle it.
> 
> I don’t like it on in most cases as it clutters the screen too much at the zoom level I typically use, but it’d be a pain to have to open Preferences every time I want to toggle it (which is generally 3-4 times per game session as a player and more as a GM).

Heh, I've never used "Show Token Names" from the menu bar, so I'm somewhat ambivalent about where it is.  Though I do hate having to look around for settings so much though (preferences, in campaign properties, on tokens, on menu bar drop downs, context menus, at server start, in the init panel, etc.)  And I suspect it creates a perception of complication and disorganization for newer users when trying to figure out what can be done.  As far as the names go, I mouse over tokens or use the map explorer to find stuff... but it's good that there are options for those that need/want different ways to see/find names.

Out of curiosity, does having a menu bar setting/hot key preclude being able to set the same thing in Preferences?  Do settings in Preferences preclude the ability to have hot-keys?  

That said, the real gist of this issue is whether or not MT remembers the settings you have these menu bar options at... it, fortunately, remembers the show token names setting or that would be quite an annoyance to have to turn it off every time because some dev thought having it on by default was the best way.  So, hopefully, someone can make these other menu bar settings (specifically "Lock Token Editor" and "Lock Player Movement") have a memory so people don't have to keep setting them every session.  Heck, having to toggle the name setting every time would actually be *less* annoying because you'd see it immediately and toggle it off... These other settings usually don't come to mind until someone edits a token when they shouldn't or moves somewhere and *then* you realize you have to go change the setting (after undoing the edit or move.)  ;)

**Comment by michaelperino** [comment]
I could probably add this to the start server dialog while the process is still fresh in my mind from #2777

**Comment by Phergus** [comment]
@michaelperino  go ahead and add both Lock Token Editor and Lock Player Movement to the start server dialog.

**Comment by thelsing** [comment]
@michaelperino #1104 would be similar too.

**Comment by FullBleed** [comment]
> @michaelperino go ahead and add both Lock Token Editor and Lock Player Movement to the start server dialog.

This would be really nice.  Gotta love it when one feature creeps into another!

**Comment by Phergus** [comment]
Testing.

New Server Options do disable functionality:
1. Player token movement
2. Player edit token
3. Player library access

However changing the settings for 1 & 2 via menu on the server side does not enable the functionality which means that once started with Player token movement disabled it will stay that way until the server is restarted.  Same for the other two.  I suspect that some GMs will need the ability to toggle them off/on as needed.

I believe that the goal was to allow the GM to ensure that those functions were disabled on server startup and not necessarily to keep them disabled for the whole session.

**Comment by Phergus** [comment]
@michaelperino  see previous comments.

**Comment by michaelperino** [comment]
I thought that's how it was functioning honestly, I'll take a look at what go swapped around.

**Comment by Phergus** [comment]
Tested again. Ignore previous comments.  Working correctly.
