### ISSUE TITLE
Rename the main branch.

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#2027]
As per discord discussion the main branch needs to be renamed.

**Comment by bubblobill** [comment]
Really? We're going for that?

**Comment by Azhrei** [comment]
I see the "feature" label was added, but no issue template was used.  Please use a template in the future.

If issues (like this one) are where the community is expected to discuss or comment on proposed changes, then referring to internal dialogue seems inappropriate.  To summarize for our users:

Some industries have used culturally insensitive terms for a long time.  Database parlance had "master/slave" tables, factory assembly lines had "slave channels", automobiles had "master cylinders", and so on.  Many of those same industries have long since changed their nomenclature to be more inclusive (databases have switched to "parent/child", for example).  It's time that open source communities clean up their act, too (not just RPTools, but all of them, everywhere).  We can only tidy up our little corner of the Internet, but this is something we should have done long ago.

Because RPTools used the main branch so little, the changes are minimal.

**Comment by JamzTheMan** [comment]
> Really? We're going for that?

Yes, there is absolutely no reason not too. It's little effort, has no negative effects, and assists in this project remaining inclusive.

@Azhrei you summed it up very well!

**Comment by Phergus** [comment]
Complete.
