### ISSUE TITLE
onChangeSelection events occuring when no change of selection has occurred.

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#2092]
**Describe the bug**
Changing a token via macro causes both an `onChangeToken` event and a `onChangeSelection` event.

**To Reproduce**
1. Load attached campaign file and click on Overlay campaign macro.
2. Right-click on Elf token and impersonate. (Generates an `onChangeSelection` event.)
3. Change a property of the token, e.g. `[r: Strength = 3d6]` or `[r: setVisible(0)]`, from chat.
4. Note an `onChangeSelection` event fires along with an `onChangeToken` event. Token remains selected.

**Expected behavior**
An `onChangeSelection` event that is triggered without an related mouse action is problematic.  Could easily create an infinite loop situation.  Actually, performing step 3 under MT 1.7.0, does exactly that but has been fixed in 1.8.0 develop.

**MapTool Info**
- Version: 1.7.0, current develop

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Remove `.zip` from name.  Be prepared for errors if used under MT 1.7.0.  See #2078 .
[OverlayOnChangeSelectionMT170.cmpgn.zip](https://github.com/RPTools/maptool/files/4920186/OverlayOnChangeSelectionMT170.cmpgn.zip)

**Comment by Merudo** [comment]
Maybe it is enough to delete
```java
        if (selectedChange) {
          selectedListChanged();
        }
```
in [HTMLFrameFactory.java](https://github.com/RPTools/maptool/blob/5c2c7c06bd0f41d35dd7e21152466716438b6faf/src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrameFactory.java#L223).

**Comment by Phergus** [comment]
Maybe so.  Haven't looked for why it's happening.

**Comment by Irarara** [comment]
Encountered an (effectively) infinite loop because of this and I was about to make a bug report but then realized it was just this issue. 💦

I can confirm that removing the call to `selectedListChanged()` like Merudo suggested does make the issue go away, and I haven't been able to spot anything breaking due to it (but it's unclear to me if that was there to cover some some weird edge cases or something.) 

Sort of unrelated to the issue, I'm unclear what the purpose of this bit is? Am I reading that right, It's firing `onChangeImpersonated` event if the currently impersonated token matches the one being changed? This doesn't seem like desirable behavior, unless the intended behavior of `onChangeImpersonated` is to fire every time the currently impersonated token *changes*, not just when impersonation changes (but the only documentation I can find for it says it's supposed to fire when impersonation changes):
https://github.com/RPTools/maptool/blob/5c2c7c06bd0f41d35dd7e21152466716438b6faf/src/main/java/net/rptools/maptool/client/ui/htmlframe/HTMLFrameFactory.java#L217-L220

**Comment by Phergus** [comment]
I've never used the impersonate functionality so I don't have a clear idea about how it is supposed to work.

In that same vein, I'm not clear as to why `selectedChange` is being set true if the token is already selected. Seems like it should be the other way around.

**Comment by Irarara** [comment]
It's pretty odd. Together, it seems like this was written as if `onChangeSelection` and `onChangeImpersonated` were supposed to fire if a selected or impersonated token(s) _changed_, not if the selection or impersonation changed. Which is certainly not the intent. It seems like it'd be safe to remove the calls to both of those events, unless I'm missing something.

**Comment by Phergus** [comment]
Tested against case above as well as Selection panel and macros getting selected tokens.  No new problems found and spurious events no longer occur.
