### ISSUE TITLE
When changing the vision setting, token must be moved to trigger vision reveal

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#213]
Assume a campaign with two (or more) vision types defined.  Changing from one to the other does not reveal the new visible range to the player unless the token is moved.  Changing the vision field in the token editor should trigger an immediate reveal.

**Comment by Merudo** [comment]
Changing the light source also has the same effect. The FoW is only revealed after movement.

**Comment by Phergus** [comment]
@Azhrei , @aliasmask , @JamzTheMan , @Jaggeroth @rkathey 

Any thoughts on Merudo's comment?

**Comment by aliasmask** [comment]
I think I agree with @MerudoI to keep our options open. IMO, there's no need to reveal FoW on vision change since players can hit ctrl-i or use the exposeFoW() function if in a macro. Same with a light change.

**Comment by Azhrei** [comment]
Agreed.  It’s more flexible to do things in small pieces under macro control.  Maybe an argument could be made for adding a parameter that causes FOW to be exposed automatically if options like Allow Players you reveal is set, but I don’t see the need for it.

**Comment by Phergus** [comment]
So it seems that the consensus is that changing the sight type, either via macro or Edit Token dialog, should **not** cause an automatic exposure.  That should be left to the calling macro or the person manually changing the sight type to do an exposure.

Would (should?) the same rule apply to changing lights on a token?

**Comment by dorpond** [comment]
I’d say keep consistent, because it would only confuse otherwise. 

I personally don’t ever use auto expose; as a DM, I want that granular power, but if I did play with autoexposure, I wouldn’t want my players changing vision/lighting and getting immediate results. Seems too trigger happy for spoiler reveal. 

But then again, Maptool wasn’t just built for a specific gaming system - Trevor had a system agnostic approach with Maptool - he wanted someone to be able to play cards, board games, and at one point when he was designing comic vision, how cool it would be If there was a video game style robot team one vs robot team two, where their conic vision would be rotated by the player, showing him the battle field in real time, as he rotated it. 

So yeah, it is hard to think outside our own play style box- my box being D&D and me being in control. 

Honestly, I don’t know how autoexposure should work. Maybe a public poll, on our social media sites, as well as our forum? 

I also don’t use initiative token lock (when it’s not my turn). Are tokens locked for macro use and editing? Might want to keep that feature in mind when changing whatever stuff you change. 

Hope this rambling helps some.

**Comment by aliasmask** [comment]
Preference setting? Expose FoW on Token Sight/Light Change? I would be okay with that.

**Comment by Phergus** [comment]
Closing this issue with everything how it stands currently:

_**Server Running**_
Token as PC and NPC
```
{
  "individual views": 1,
  "players can reveal": 1,
  "auto reveal on movement": 1,
  "strict token management": 1,
  "individual fow": 0
}
```
**Edit Token Dialog**
Changing Sight Type - No auto exposure
Changing Has Sight  - No auto exposure

**Right-Click Menu**
Setting Light On - No auto exposure

**Via Macro**
Setting Light On - No auto exposure
Changing Sight Type - No auto exposure
Changing Has Sight  - No auto exposure

If we want to add a preference setting for this or change behavior a ticket should be opened for the next release.
