### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ebudai** [RPTools/maptool#2135]
There are several redundant null checks, and many places where if conditions are always true or false.

**Comment by Phergus** [comment]
@ebudai let me know when you have no more changes to commit and we'll close this one.

**Comment by ebudai** [comment]
I'll do another couple PRs against this so they don't get too large

**Comment by Phergus** [comment]
@ebudai   Seeing a unit test failure when doing a `gradlew build` after merging in #2143 .

`MapToolLineParserTest.java`
```
org.opentest4j.AssertionFailedError: expected line #1:`expanded roll sh[...]` doesn't match ==> expected: <
expanded roll shows ...if\(1 == 1, 1, 0\) = 1.
> but was: <
expanded roll shows ???if(1 == 1, 1, 0) = 1?1?
>
```

**Comment by selquest** [comment]
@Phergus that's the test failure I had in my original dev environment since #2062.  I upgraded my dev box (was Mint 19, now Mint 20) and that got the test working for me.  Still working after merging #2143 too.

That test is looking for specific characters that are apparently somewhat environment-specific - not really ideal in a unit test, but it's working in all the auto-build environments, so..

**Comment by Phergus** [comment]
Interesting.  IntelliJ has had several updates lately so maybe that's what has broken it here on my Win10 system.

It's failing from both IntelliJ and the command line for me so probably not IntelliJ.  Maybe a Windows update somehow.

**Comment by Phergus** [comment]
No issues seen with code changes.
