### ISSUE TITLE
isNumber returns false for anything that is not a positive integer

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#2211]
**Describe the bug**
isNumber() returns false for number strings that are not positive integers

**To Reproduce**
1. Go to chat
2. Copy and paste
[isNumber('0.33')]
[isNumber('-0.33')]
[isNumber('.33')]
[isNumber('-.33')]
[isNumber('33')]
[isNumber('-33')]
[isNumber('3.3')]
[isNumber('-3.3')]

**Expected behavior**
Expected results
1 1 1 1 1 1 1 1
Actual results
0 0 0 0 1 0 0 0

**Screenshots**

**MapTool Info**
- Version: 1.8.0-beta.2
- Windows exe
- Win 10

**Comment by selquest** [comment]
From the `StringUtils.isNumeric()` docs:
> Checks if the CharSequence contains only Unicode digits. A decimal point is not a Unicode digit and returns false.

So not really what we want here.  The version prior to d444c46feafe496b89533ec3766de3ae01de3d89 just tried to parse it as an Int and then a Double and returned `0` if there was an exception on both, so that might not be ideal either.  It also can lead to some unexpected behavior because java recognizes some of its own string representations like "1E3" and "2F" as numeric.

From here it gets a little weird.

NumberUtils has some methods that look promising but have some odd behavior like:
> Non-hexadecimal strings beginning with a leading zero are treated as octal values. Thus the string 09 will return false, since 9 is not a valid octal value.

I'd be inclined to try and parse with Java's `NumberFormat` to easily get us Locale recognition baked in, so things like `isNumber("5,1234")` would return true - but it does annoying things like:
> The method may not use the entire text of the given string.

...

So I guess the question is what are we looking to achieve with this?  For which of the following do we want to return true?
String | `parseInt()` / `parseDouble()` (1.7)| `NumberUtils.isParsable()` | `NumberUtils.isCreatable()` | `NumberFormat.parse()`
--- | --- | --- | --- | ---
`0.2` | T | T | T | T
`09`  | T | T | false | T
`-3.5` | T | T | T | T
`1E3` | T | false | T | T
`2F` | T | false | T | T
`2L` | false | false | T | T
`0xFA` | false | false | T | (parses as `0`, T)
`1,000` | false | false | false | T 
`1,000.0` | false | false | false | T
`1.000,0` | false | false | false | T (locale dependent)
`2nd Place` | false | false | false | (parses as `2`, T)

**Comment by Phergus** [comment]
Along with that whatever `isNumber()` recognizes as a number must also be recognized as a number when that string is used in an expression.   Recognizing `027` as an Octal value doesn't do us any good if the macro blows up when it's a variable containing that is used in an expression.  It really needs to just recognize negative and positive integer and floating point values.

**Comment by selquest** [comment]
> whatever `isNumber()` recognizes as a number must also be recognized as a number when that string is used in an expression

Yup - to that end, I went looking a little deeper.  Numeric parameters in MapTool are represented by `BigDecimal`, but the interesting question is what literals get recognized as numeric by the parser, causing them to be fed to `BigDecimal` in the first place.  Ran the following test:
```
2+0.2: [r: 2 + 0.2 ]<br />
2+09: [r: 2 + 09 ]<br />
2+-3.5: [r: 2 + -3.5 ]<br />
2+1E3: [r: 2 + 1E3 ]<br />
2+2F: [r: 2 + 2F ]<br />
2+2L: [r: 2 + 2L ]<br />
2+2W: [r: 2 + 2W ] (<i>2W is not a valid number representation, demonstrating that the parser is only taking the prefix</i>)<br />
2+0xFA: [r: 2 + 0xFA ]<br />
2+1,000: [r: 2 + 1,000 ]<br />
2+1,000.0: [r: 2 + 1,000.0 ]<br />
2+1.000,0: [r: 2 + 1.000,0 ]<br />
2+2nd Place: [r: 2 + 2nd Place ]<br />
```
produces output:
```
2+0.2: 2.2
2+09: 11
2+-3.5: -1.5
2+1E3: 3
2+2F: 4
2+2L: 4
2+2W: 4 (2W is not a valid number representation, demonstrating that the parser is only taking the prefix)
2+0xFA: 252
2+1,000: 3
2+1,000.0: 3
2+1.000,0: 3.000
2+2nd Place: 4
```
This gives us this table:
String | Parsed Number
--- | ---
`0.2` | T
`09` | T
`-3.5` | T
`1E3` | wrong
`2F` | accidentally
`2L` | accidentally
`2W` | wrong
`0xFA` | T
`1,000` | wrong
`1,000.0` | wrong
`1.000,0` | wrong
`2nd Place` | wrong

Which conveniently matches none of the result tables from the `isNumber()` strategies above, and includes some troubling results that we can pretend we didn't see until parser 2.0 comes along.

**Comment by Phergus** [comment]
> The version prior to d444c46 just tried to parse it as an Int and then a Double and returned 0 if there was an exception on both, so that might not be ideal either.
So perhaps just switch back to what it was but also catch the empty string?

**Comment by selquest** [comment]
The empty string problem was a product of the switch to StringUtils, it's properly non-numeric in 1.7.

Definitely the easiest would be to basically revert that change (or, for the slightly cleaner approach that was being attempted, use `NumberUtils.isParsable()`), but it does leave us in a state where `isNumber()` doesn't perfectly match the parser's behavior. 
 Returning false for things the parser gets wrong (`1E3` parses as just `1`) is probably for the best, though.

**Comment by Phergus** [comment]
Agreed.  If a macro is checking a passed argument that is `1E3`, returning `false` is the better choice as having the parser see that as `1` would certainly lead to strange macro behaviors.

**Comment by selquest** [comment]
Mostly restores functionality from 1.7, but will return `0` for some additional number formats that are not handled correctly by the parser but that were previously considered numeric by this function.  Specifically:
* `isNumber("2nd")` returned `1` in 1.7, now returns `0`.  Parser interprets as `2`.
* `isNumber("1E3")` returned `1` in 1.7, now returns `0`.  Parser interprets as `1`.

**Comment by Phergus** [comment]
Tested.  Positive, negative numbers working as expected.  Empty string returns false.

**Comment by Phergus** [comment]
@selquest   It appears that something has broken this again.  Only one of the original examples given in the first post work in current code.

**Comment by selquest** [comment]
> My bad. It's still good. Was on the wrong branch.

I was going to say - I added those cases to the unit test, so if somebody broke it we should know! :)
