### ISSUE TITLE
1.8.3 says new version is available, upon update it is still 1.8.3 and says new version is available

### ISSUE THREAD

**Issue by mr-ice** [RPTools/maptool#2393]
**Describe the bug**
MacOS 11.2
Downloaded the 1.8.3 .dmg, installed maptool to my preferred location.  Upon launch it says there is a new version available.  It downloaded the 1.8.3 .pkg.  I installed that, and upon launch it still says there is a new version available.

**To Reproduce**
1. Go to maptool download page
2. Click on MapTool-1.8.3.dmg
3. Launch MapTool
5. Say "Download"
6. See new version is also 1.8.3
7. Install it
8. Launch it
9. See error

**Expected behavior**
Upon downloading the most up-to-date version, and certainly upon downloading the update from there should result in running the already most up-to-date version and one should not be prompted to download _again_.

**Screenshots**

**MapTool Info**
- Version: 1.8.3
- Install: New

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 11.2

**Additional context**

==== MapTool Information ====
MapTool Version: 1.8.3
MapTool Home...: /Users/michael/.maptool-rptools
MapTool Install: /Applications/MapTool.app/Contents/app
Max mem avail..: 4 GB
Max mem used...: 504 MB
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: /Applications/MapTool.app/Contents/runtime/Contents/Home
Java Vendor....: AdoptOpenJDK
Java Version...: 14.0.2
Java Parameters: 
  -Djava.library.path=/Applications/MapTool.app/Contents/app:/Applications/MapTool.app/Contents/MacOS
  -Djava.launcher.path=/Applications/MapTool.app/Contents/MacOS
  -Xss8M
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED

==== OS Information ====
OS Name........: Mac OS X
OS Version.....: 10.16
OS Architecture: x86_64
PATH...........: /usr/bin:/bin:/usr/sbin:/sbin
Number of Procs: 8

==== User Information ====
User Name: michael
User Home: /Users/michael
User Dir.: /

==== Network Interfaces ====
Display Name..: utun1
Interface Name: utun1
Address...: fe80:0:0:0:a5d6:fa5a:22a6:7d8a%utun1

Display Name..: utun0
Interface Name: utun0
Address...: fe80:0:0:0:84de:f67a:f208:a483%utun0

Display Name..: llw0
Interface Name: llw0
Address...: fe80:0:0:0:fc98:ffff:fefe:41ec%llw0

Display Name..: awdl0
Interface Name: awdl0
Address...: fe80:0:0:0:fc98:ffff:fefe:41ec%awdl0

Display Name..: en0
Interface Name: en0
Address...: 2603:8080:4340:1b9:bd12:2591:d9c5:7393%en0
Address...: 2603:8080:4340:1b9:1e:f57e:35ff:8a78%en0
Address...: fe80:0:0:0:c6c:4e5e:1398:f15c%en0
Address...: 192.168.111.111

Display Name..: lo0
Interface Name: lo0
Address...: fe80:0:0:0:0:0:0:1%lo0
Address...: 0:0:0:0:0:0:0:1%lo0
Address...: 127.0.0.1

Host Address...: 192.168.111.111
Default Gateway: 192.168.111.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: UTF-8
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1440x900(32)
Display 2: 2560x1600(32)

==== Internet Gateway Devices ====
Device Name.: MATRIXAP
Model Name..: EA4500
Manufacturer: Linksys, LLC
Model Number: EA4500
Model Desc..: Simultaneous Dual-Band Wireless Gigabit Router
Firmware....: Linux/3.3.8, UPnP/1.0, Portable SDK for UPnP devices/1.6.19
External IP.: 70.121.87.19

**Comment by mr-ice** [comment]
Hey, I see that @Azhrei put this in his post on the site about an hour before I posted.  When I searched here for the issue I didn't see it with my uninspired choice of search terms.

Feel free to close this if you are already tracking it.

**Comment by Azhrei** [comment]
No, it’s best to have an issue to track it here.  Thanks for filing it. :)

**Comment by selquest** [comment]
Dug into this a bit to see if I could help, and it looks like the problem is that the AppUpdate check is trying to compare a commit SHA from the jar manifest to the "target_commitish" field in the GitHub releases API.    The "target_commitish" field, however, appears to contain the name of the branch from which the release was made ("develop", for 1.8.3) instead of a specific commit.  There doesn't appear to be a field for commit SHA that's directly accessible on the Releases API - it looks like that would need an extra mapping through the List of Tags to lookup.

Is this a recent change in the Github API?  or did we just change the release process so the "target_commitish" field is getting populated differently?

I'm happy to add the extra step of looking up commit SHA through the tag, but wanted to make sure we weren't expecting this to be solved through the build process first.

**Comment by Azhrei** [comment]
thanks for looking into it/

There has definitely been a change on the GH side of things, as 1.7 started producing errors in the middle of its lifecycle due to a change in the data returned.

I would guess that the `target_commitish` works the same as in git — when the commit is the HEAD of the branch, the branch name suffices to identify the commit.

I'm not sure if the information is available, but I'd rather make a list of all release tags (our format is always going to be `##.##.##` for other reasons) and then sort them and see if there's one later than the current executable.  (There's a version check somewhere that is used to compare version numbers read from campaign files and the like.)

**Comment by selquest** [comment]
So we can use the [`/releases/latest`](https://api.github.com/repos/RPTools/maptool/releases/latest) endpoint to specifically get the information about the most recent non-draft non-prerelease Release (right now the AppUpdate process is actually applying its own filtering on the list of all releases to get that information, but that's an easy simplification).

At the moment that's obviously 1.8.3, described by:
```json
// for brevity, squashed the "author" and "assets" contents, truncated body
{
  "url": "https://api.github.com/repos/RPTools/maptool/releases/38082131",
  "assets_url": "https://api.github.com/repos/RPTools/maptool/releases/38082131/assets",
  "upload_url": "https://uploads.github.com/repos/RPTools/maptool/releases/38082131/assets{?name,label}",
  "html_url": "https://github.com/RPTools/maptool/releases/tag/1.8.3",
  "id": 38082131,
  "author": { ... },
  "node_id": "MDc6UmVsZWFzZTM4MDgyMTMx",
  "tag_name": "1.8.3",
  "target_commitish": "develop",
  "name": "MapTool 1.8.3",
  "draft": false,
  "prerelease": false,
  "created_at": "2021-02-15T22:42:34Z",
  "published_at": "2021-02-15T22:50:08Z",
  "assets": [ ... ],
  "tarball_url": "https://api.github.com/repos/RPTools/maptool/tarball/1.8.3",
  "zipball_url": "https://api.github.com/repos/RPTools/maptool/zipball/1.8.3",
  "body": "# MapTool 1.8.3\r\n**MapTool now uses Java 14 from AdoptOpenJDK. ..."
}
```
and the Manifest properties that are packed inside the 1.8.3 jar:
```
Manifest-Version: 1.0
Implementation-Title: MapTool
Implementation-Version: 1.8.3
Implementation-Vendor: RPTools
Git-Commit: 7032c44
Git-Commit-SHA: 7032c4488c4034d441ce5bd2c20dc1465a0ba00d
Built-By: runneradmin
Built-Date: Mon Feb 15 22:51:24 GMT 2021
Built-JDK: 14.0.2
Source-Compatibility: 14
Target-Compatibility: 14
Main-Class: net.rptools.maptool.client.LaunchInstructions
```

So it seems like the best option is to get the `tag_name` from the latest release, and compare to the `Implementation-Version` from the manifest.  I'll look for existing version comparison code, but otherwise take steps to compare semantic versions appropriately.

We could still use the `Git-Commit-SHA` info, but it would require a separate API call to [`/tags`](https://api.github.com/repos/RPTools/maptool/tags) (and for some reason there's not even a `/tags/<name>` endpoint, so we'd have to search that list for the matching tag internally), so probably not ideal.

**Comment by Azhrei** [comment]
We should also filter out prerelease and draft entries, though.  We don’t want the auto update to be recommending beta versions, I think.  (Do we?  We could provide the pop up with a big, bold note that it is “draft” or “prerelease” or “beta” or whatever, and still allow users to “skip this release”.)
--
Frank Edwards
Edwards & Edwards Consulting, LLC
Hours:  10A-6P ET
Phone:  (813) 406-0604

**Comment by selquest** [comment]
> We should also filter out prerelease and draft entries, though

Yup, and that's done automatically by using the `/latest` endpoint.  According to the [API Docs](https://docs.github.com/en/rest/reference/repos#get-the-latest-release):
> The latest release is the most recent non-prerelease, non-draft release, sorted by the created_at attribute. The created_at attribute is the date of the commit used for the release, and not the date when the release was drafted or published.

**Comment by selquest** [comment]
Linking to related issue: #2263

**Comment by Phergus** [comment]
@selquest  I assume you were able to test this successfully?

Running out of IntelliJ or from `gradlew run` with the version set to 1.8.4 prompts for updating to 1.8.3 for me.

**Comment by selquest** [comment]
> @selquest I assume you were able to test this successfully?
> 
> Running out of IntelliJ or from `gradlew run` with the version set to 1.8.4 prompts for updating to 1.8.3 for me.

Yes, testing this gets a little complicated because it's specifically pulling the version out of the Manifest file bundled in the jar.  The -version command line argument doesn't impact that at all, and the manifest is created by the `jar` gradle task.  I tested by temporarily mocking out the bit that retrieved info from the manifest, and by manually manipulating the manifest on a packaged jar.
