### ISSUE TITLE
changes to UI for token campaign property editing

### ISSUE THREAD

**Issue by acodispo** [RPTools/maptool#2405]
**Is your feature request related to a problem? Please describe.**

I frequently forget to click "Update" after editing a set of properties for a token type. Instead I click Ok to close the Campaign Properties dialog, and lose my changes. Or I simply click on a different Token Type.

**Describe the solution you'd like**

Ideally, changes should be saved as the default behavior. Currently, Revert is the default behavior (closing the dialog, or navigating to a different type, both serve to revert the changes), which is very confusing, to me at least.

**Describe alternatives you've considered**

A reminder prompt in these two situations (e.g. "You will lose your changes to this token type, are you sure?") might be a quicker fix keeping closer to how things currently work but reducing the chance of lost changes.

Thanks in advance for considering this!

**Comment by melek** [comment]
Noting this is related to #1238 (specifically [this comment](https://github.com/RPTools/maptool/issues/1238#issuecomment-650612003)). 

This issue is definitely important, but kind of relates to a big rats nest of issues with Campaign Properties and the need to update both the underlying implementation of the properties and being shy of working on the present Swing UI because it needs to be replaced. You'll note in the older issue thread that a new UI would probably do away with the update button entirely.

**Comment by acodispo** [comment]
Thanks, I didn't find that issue! It sounds like my concern would be dealt with by the proposed changes in the other issue. I'm fine if this gets marked as a duplicate, or whatever seems most appropriate. Thanks for your response!

**Comment by kwvanderlinde** [comment]
Tested. Can now add or modify token properties and click "OK" without losing the changes.
