### ISSUE TITLE
Specification for an RPTOK file?

### ISSUE THREAD

**Issue by Syndaryl** [RPTools/maptool#242]
Is there a specification document for token files?

I'm writing a plugin for the .NET application GURPS Character Assistant for exporting GURPS characters to a maptools token. The current iteration produces a macro script that needs to be pasted into Maptools to create and initialize the token, and it's ginormous, so it has to be done in segments... which is just a giant PITA.

It would be a much better user experience if I could just spit out a token file for them to import.

I can see it's a zipped document with XML and I would guess the XML is a serialized java object. I thought it would be "fairly" easy to replicate a token with a placeholder image (thus avoiding the whole question of matching the Maptools GUID algorithm) but I've been pretty unsuccessful.

**Comment by JamzTheMan** [comment]
There is no spec because as you said, it's just the Token class serialized so that changes as the token class changes.

There will be RESTful macros though that may be of use? If you have it online you can grab data using a macro?

Eventually we do want to create some better ways to make import data into tokens...

**Comment by Syndaryl** [comment]
RESTful macros? As in, Macros will be able to tap REST services? Well, that's exciting!

GCA is an offline, desktop program of a rather classical architecture (the codebase has been evolving continuously for I think almost 20 years now) but the plugin system lets me get into more modern features. . . There might be some possibility getting the two programs to talk to each other. However, that would require Maptools to pull from GCA, rather than GCA pushing - interesting.

**Comment by Syndaryl** [comment]
In the meantime, if I work on trying to create tokens for (e.g.) 1.4.1.8 that actually work, are they likely to be reasonably forward compatible ish?

**Comment by Azhrei** [comment]
Hm.  You wouldn't need most of the properties in the token and you could leave them out (or include them with a value of zero or something).  I guess it depends on how much you want your plugin to do.  Here's what I would look at doing:

1.  Plugin creates a token with a graphics object for the portrait and a single property that contains the data you want to use in the token formatted as JSON.  (The plugin could create the token from scratch, or it could ask the user to drop on image into MT, then save the image as a token.  Now the plugin would have a template that could be filled in with other values, but the basic shape would be there.)
+  The user imports a macro that reads the JSON from the token and spreads it out as separate token properties.  This macro never changes unless there's an update to the format of the JSON object, maybe because additional new features are being supported.

This makes the payload as small as possible (just the JSON object in an empty token with a portrait image).  The macro rarely changes, so it's managed separately.  If you store a version number inside the JSON, the macro could even tune itself at runtime, even to the point of refusing to run if the JSON object's version is newer than the macro (and thus contains unsupported or unknown data).

**Comment by rkathey** [comment]
I would generate an example Token in MapTool in a GURPS framework. Create a token, save it as an RPTOK file, unzip it, and get the property names inside the XML. Then you could generate the XML via that example along with images files and such. With this method, you'll be tied to a specific framework for the generated tokens or a set of frameworks that use the same property names.

**Comment by Syndaryl** [comment]
A sort of side note: for experimentation I tried pushing Maptools into IKVM, and successfully produced a DLL that I can import into my C# project, and actually create Token objects in C#.
Presuming I can properly serialize the Token back to disk, working with the original class files might be the "simplest" route, for certain values of simple that include converting java bytecode to a dll. I would need to determine the exact class files required in building a token - including all of MT would be just sloppy.

Creating a JSON object and an accompanying "bootstrap" macro might be the _actual_ simplest.

**Comment by Azhrei** [comment]
That might work...  The classes that are used for persisting tokens are in `net.rptools.maptool.util.PersistenceUtil.class`, but they use plenty of other classes.  For example, images are maintained by the AssetManager and related classes.

**Comment by JamzTheMan** [comment]
@Syndaryl Feel free to join our Discord server for more discussions.  I don't mind questions on GitHub issues (it's perfectly fine!) but I never know when they should be closed. 😄 

I don't want to cut anyone off, but don't want to l leave issues open for ever.  #housekeeping
Just reply if/when this issue can be closed.
