### ISSUE TITLE
Servers de-listed from RPTools.net

### ISSUE THREAD

**Issue by Akaku-Keninari** [RPTools/maptool#2423]
**Describe the bug**
After some minutes listed servers stop being listed on rptools.net registry

**To Reproduce**
Start a server listed on rptools.net.
Check if it shows up on second client.
Wait a hour or two.
See no server listed

**Expected behavior**
Should likely keep itself registered as long as the server is actually up.

**MapTool Info**
- Version: 1.8.3
- Install: New

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by Bloodvixen** [comment]
###Have used 1.83 since week of release, this situation has been observed from multiple machines, with different campaigns, has occured every session

**Describe the bug**
After some minutes listed servers stop being listed on rptools.net registry

**To Reproduce**
Steps to reproduce the behavior:
Start a server listed on rptools.net.
Check if it shows up on second client.
Wait a hour or two.
See no server listed

**Expected behavior**
Should likely keep itself registered as long as the server is actually up.

MapTool Info

    Version: 1.8.3
    Install: New

Desktop (please complete the following information):

    OS: Windows
    Version 10

**Comment by Phergus** [comment]
Changes have been made to the registry server to address this.

**Comment by cwisniew** [comment]
The problems seem to have been resolved.
