### ISSUE TITLE
Macro Editor Function Descriptions

### ISSUE THREAD

**Issue by JamzTheMan** [RPTools/maptool#243]
Now that we have Auto-Completion turned on, we need to document the macro functions in the i18n properties file (it's own file has been created just for macro descriptions for the editor)

We have a lot of work to do for this and anyone can do this. Feel free to submit changes/additions, even if it's a function or two!

**Comment by Azhrei** [comment]
I was hoping to work on this tomorrow, but I've been co-opted for something else during the day, but I'll try later.  I'm pretty convinced that an HTML dump of the wiki can be made to work.  After all, I scraped the entire d20pfsrd site for spell information to embed into self-created tokens.  This should be easier than that. ;)  If anyone picks this up, post here first so that I can get what I have so far pushed to this repo.  @JamzTheMan I'll branch from merge-from-nerps to do this and issue a PR as soon as I have some progress.

**Comment by JamzTheMan** [comment]
Cool cool. I thought having an issue just to track this will be good.

We'll need a process to not overwrite work. For instance, Jagged is going to document his new functions but they won't be in the wiki. Minor test case.

Feel free to create/change the name/files needed etc. This is a rough skeleton and we'll need another file anyway for shorthand (see my class file for notes on that)

**Comment by Jaggeroth** [comment]
My new functions are already in the wiki. Added them a while back (teacher's pet)

**Comment by Azhrei** [comment]
Yes, saw them there — a bunch of setDraw*() and getDraw*() functions.  Thank you for beating me to the punch! ;)

**Comment by JamzTheMan** [comment]
i haven't gotten around to "documenting" yet, I'll get to it eventually...
Don't wait on it for the merge of this work though.  I'll work with Phergus to get it on the wiki hopefully this week...

**Comment by Azhrei** [comment]
After changing the way the **description** is output, I need to grab everything from the wiki again.  I should be able to push to the `macro-editor-help` branch within an hour.

**Comment by cwisniew** [comment]
I am moving this out of this release, as this is an enhancement on top of what is already there and its been 7 days since it has been looked at.

**Comment by Azhrei** [comment]
Sorry, it's been merged already.
