### ISSUE TITLE
return(0) renders an error trace

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#2441]
**Describe the bug**
[h:return(0)] in the code renders an error trace

**To Reproduce**
Create new macro on lib:test
put it: 
[h:return(0)]
run it. 

**Resulting behavior**
Error trace : (new)@Lib:test

**Expected behavior**
nothing (as in no output)

**MapTool Info**
- Version: 1.8.3
- Install: New

**Desktop (please complete the following information):**
 - OS: win10

**Comment by MeloDub** [comment]
Working on this.

**Comment by Phergus** [comment]
Tested.  Calling a macro that has [h: return(0)] no longer produces an error.  Return is now `null`.

**Comment by selquest** [comment]
I'm not sure these changes are working as intended, and I'm a little confused by some of the choices.  This appears to be overloading the existing `macro.return` special variable (normally used to convey a result back to a caller) as a flag to control whether the exception produced in the `return()` function should be ignored.  Reuse aside, do we know for certain that we never want `macro.return` to contain other information while we're making this decision?  Also, we're now creating an empty Result in the new catch block in `MapToolLineParser` - does this still allow the rest of `return()` functionality to operate?

I haven't tested this thoroughly myself yet, but @wolph42  has demonstrated on Discord some confusing behavior of `return()`, and this jumped out at me as the only mention of `return()` on the 1.8.4 Change Log.

@Phergus does reviewing an already closed-PR make sense?  Do we have a re-open workflow if it turns out these changes do need to be reverted?  Should further investigation be a new issue (they may be anyway - not sure Wolph's issue is actually directly related)?  I don't know what our SOP is here.

**Comment by JonathanGabor** [comment]
#2513 appears to be caused by this.

**Comment by Phergus** [comment]
@selquest we don't really have an SOP for this but generally have just opened a new bug issue referencing the previous issue/pr that way anyone looking at the old ones will see the new mentions at the bottom of the discussion.
