### ISSUE TITLE
Delete Drawings from Map with mouse

### ISSUE THREAD

**Issue by thelsing** [RPTools/maptool#2466]
**Is your feature request related to a problem? Please describe.**
I like to select one or more drawings/templates from the map and delete them.

**Describe alternatives you've considered**
I can use the Drawing-Explorer. But with more drawings it can take some tries to select the right drawing and in fullscreen mode it is not available.

**Comment by Azhrei** [comment]
The code in the PR uses e.isControlDown() to determine whether to use multiselect.  This doesn't translate well to the Mac where Ctrl-Click is equivalent to Right-Click.  I can't tell if this will be an issue without trying it out and I can't do that right now, but I wanted to offer a warning prior to the PR being merged.

**Comment by Phergus** [comment]
MT uses Shift for multi-select of tokens, objects and stamps so it may be preferable to stick to that paradigm.

**Comment by thelsing** [comment]
I changed the multi select key to Shift now.

**Comment by Phergus** [comment]
Tested.  Select and hitting Delete key working.  Multi-select with Shift works.  Draw Explorer updates appropriately.  Load/save/reload campaign.  No issues.

Minor niggles:  
- You have to be on the correct layer in order to select a drawing which means still using the Draw Explorer to figure out what layer the drawing is on.
- Bounding box doesn't take into account stroke thickness.

![image](https://user-images.githubusercontent.com/34379254/115921512-d4c90600-a438-11eb-8115-ee3806f1dd86.png)

**Comment by Azhrei** [comment]
I don't think I'd mind that you have to be on the correct layer IF there was some help identifying which layer that was!  Maybe when in this mode, there could be a tooltip that identifies which layer the drawing is on?  I don't think I'd want to be able to (accidentally) select a drawing on the wrong layer and delete it, otherwise we could just ignore the layer...  (Does drawing a selection rectangle over the area work?)

Probably should include stroke width to bounding box; your image looks a little silly. 🙄

**Comment by Phergus** [comment]
Selecting across layers would certainly be likely to cause issues.  Be too easy to select a very large background layer drawing where the bounding box was outside of the view without realizing it.  As you say, maybe a hover tip that shows the layer of the drawing that is under the mouse pointer?  Maybe when the layer is chosen only those on that layer are visible?  Or marked in some way?

**Comment by thelsing** [comment]
My usecase was that I wanted to delete my own drawings as a player. As a player only the token layer is available. For the GM its the same with tokens. You have to know what the correct layer is or just try it out.

**Comment by Irarara** [comment]
> Maybe when the layer is chosen only those on that layer are visible?

I think this might be nice. Maybe with an option to toggle whether it's displaying only the current layer or not?

If we're talking minor niggles, for the selection box wouldn't it be more consistent to use the red/white dashed outline that's used for tokens, etc.?

As an aside, I think this feature is really nice (...despite the fact that I basically never use drawing tools). It might be cool to develop it into a more general thing. I was toying around yesterday with adding in the ability to drag select things as with the pointer tool and bring up the context menu. Being able to select a bunch of stuff on the map and merge or group them right there is pretty nifty. Dragging images around would be nice, but that seems like it might be more work (are there existing facilities for updating the position of drawings? I haven't really dug too deep).

**Comment by Azhrei** [comment]
> If we're talking minor niggles, for the selection box wouldn't it be more consistent to use the red/white dashed outline that's used for tokens, etc.?

The selection outlines are based on repeating patterns of horizontal and vertical segments that are pieced together; they're not drawn, per se.  That means they could easily be used for something like this, unless you wanted them to actually follow the stroke path and not just be a rectangle.

<aside>
it's always kind of irked me how the various decorations added to the token images were not implemented as "decorators" (ie, the design pattern), so that they could be applied to things other than tokens.  Such as drawings, macro buttons, groups of tokens, etc.  but that was the original implementation and it's never been revisited.
</aside>

**Comment by thelsing** [comment]
I can change the border to the normal image border used for selecting tokens. As the stroke thinckness is not available in the Drawable interface, I would have to modify the getBounds method for those misbehaving drawings. I'll create a new pull request for this. What should be done in regards to the "documentation needed" tag?

**Comment by thelsing** [comment]
A bit of further testing shows that the bounds for all drawables are not completely correct. Most only don't take line thickness into account. The starting field of the line template is missing from the bounds and the circle template centered on fields is too big in the north and west sided. 
Spell templates have a BOUNDS_PADDING of 10 pixels. So only thicker strokelines result in incorrect bounding boxes.

Should the fixing of the bounds go to another issue?

**Comment by thelsing** [comment]
I change the selectionbox and accounted for the line thickness now.

**Comment by Phergus** [comment]
@thelsing _Documentation Needed_ refers to providing documentation on how the new/changed functionality works and updating the appropriate wiki page(s).

Fixing of issues with template bounds and/or template drawing on different grids should definitely go on another issue.

**Comment by Phergus** [comment]
Tested.  Selection uses the regular MT candy stripe pattern and the bounds are correct for regular drawings.  Bounds on selected template drawings on non-square grid types can be off but that is part of the issue that templates only really work on square grids.
