### ISSUE TITLE
Map Export should warn if file exists before overwriting

### ISSUE THREAD

**Issue by dbirchbauer** [RPTools/maptool#2486]
**Describe the bug**
When using the export map feature there is no confirmation prompt to warn you if a file already exists with the same name as you are exporting.

Provide a confirmation prompt to avoid accidentally overwriting a file

**To Reproduce**

1. Go to Map -> Export Map
2. Name and save the export.
3. Go to Map -> Export Map
4. Save the export to the same location with the same name as in #2. 
5. It overwrites the file without warning that a file with that name already exists. Poof!

**Expected behavior**
It should clearly warn about overwriting a file that already exists. It currently just overwrites the file. Poof!

**Screenshots**
N/A

**MapTool Info**
- Version: 1.8.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [10, 20H2, 19042.928 ]

**Additional context**
I would change this as a bug, personally.

**Comment by Phergus** [comment]
Please follow the templates.

**Comment by dorpond** [comment]
This may help, Phergus, as I was able to reproduce this.

**Describe the bug**
When using the export map feature there is no confirmation prompt to warn you if a file already exists with the same name as you are exporting.

Provide a confirmation prompt to avoid accidentally overwriting a file

**To Reproduce**

1. Go to Map -> Export Map
2. Name and save the export.
3. Go to Map -> Export Map
4. Save the export to the same location with the same name as in #2. 
5. It overwrites the file without warning that a file with that name already exists. Poof!

**Expected behavior**
It should clearly warn about overwriting a file that already exists. It currently just overwrites the file. Poof!

**Screenshots**
N/A

**MapTool Info**
- Version: 1.8.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [10, 20H2, 19042.928 ]

**Additional context**
I would change this as a bug, personally.

**Comment by Phergus** [comment]
Yup.  Changed.  Thanks for the fixing the original.

**Comment by BlackwingNL** [comment]
I have fixed this in a local branch, will put up a PR shortly

**Comment by Phergus** [comment]
Tested.  MT now shows a confirmation prompt before overwriting existing file.
![image](https://user-images.githubusercontent.com/34379254/123442879-9368ea00-d592-11eb-9172-24b1d1f5d8a4.png)
