### ISSUE TITLE
Random view switch when starting and stopping server.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2487]
**Describe the bug**
Immediately after starting a server, my view usually switches to a random location on a random map. This also happens after stopping the server.

**To Reproduce**
1. Open a campaign with several maps.
2. Pick a map you like to look at.
3. Click on `File > Start Server...` and start a server as a GM.
4. Witness your view switch to a different map.
5. Switch maps back to what you were looking in (2)
6. Click on `File > Disconnect From Server...`
7. Witness your view switch to yet another map.

Try that a few times and you'll find the exact map may vary, and your view may be positioned differently (and zoomed differently, I think, but I'm not sure on that).

**Expected behavior**
When I start a server as a GM, my view should remain at the same location and on the same map. And when I stop a server, my view should also remain where it is.

Or, if a view change is warranted (e.g., starting server as a player but currently on a hidden map), the view should change to something predictable or else just black the map out (as when a map is hidden when a player is still on it)

**Screenshots**
Before I start the server, I am enjoying by beautiful grassy wilderness:
![image](https://user-images.githubusercontent.com/7492219/112095248-67843580-8b59-11eb-8969-af0e56879c2c.png)
But when I start the server I am brought to a creepy dungeon
![image](https://user-images.githubusercontent.com/7492219/112095327-84206d80-8b59-11eb-8b7c-f953992ea399.png)
I go back to my grass patch, but when I stop the server I'm back in skeleton central! Or any one of my other maps...

**MapTool Info**
- Version: 1.8.3, but I've been seeing this since at least 1.7.
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Comment by melek** [comment]
Noting that this is related to #75.

My ideal MVP for solving these two issues:
* GM view should remain the same when starting a server (this suggestion)
* If the GM view is on a player-visible map, the GM view at the moment they started the server (Map, Position, and Zoom) should be set as the default for connecting players.
* If the GM tries to start a server when viewing a non-player visible map, players are brought to 0,0 @ 100% zoom on the first player-visible map.
* If no player visible maps exist, players will see a blank screen until one becomes available (current behavior).

This scheme is nice because no extra UI is needed while creating a predictable situation for GMs.

**Comment by kwvanderlinde** [comment]
I like the pragmatic approach of melek's suggestion. And as far as the GM side goes, that is exactly the behaviour I would expect.

For the player-side, it might be nice to always send them to the first visible map by default (i.e., that would become the "landing map"). But if the GM has enabled "Center Players on Current View (Continuous)", then they would be brought to the GM's view.

**Comment by Phergus** [comment]
And this is also related to the more recent #2698.
