### ISSUE TITLE
Colors for images in Html5Panel are weird for some images.

### ISSUE THREAD

**Issue by thelsing** [RPTools/maptool#2490]
**Describe the bug**
For some images (some png with transparent background) I get a black background and weird colors if I use it with asset:// in Html5Panel.

**To Reproduce**
Find an image that is affected and put it into an Html5Panel. (Mine is from D&D-Beyond so I can't upload it here.)

**Expected behavior**
Image shows the right colors.

**Screenshots**
![image](https://user-images.githubusercontent.com/20617946/112515984-15305800-8d97-11eb-9ddb-a2a0a027b5cd.png)

**MapTool Info**
- current development branch

**Desktop (please complete the following information):**
- Windows 10

**Additional context**
I tracked the issue down to AssetURLStreamHandler [here](https://github.com/thelsing/maptool/blob/cfa752803beec88a5bcfe23e045b9f1313e653d8/src/main/java/net/rptools/maptool/client/AssetURLStreamHandler.java#L137).  If I `return new ByteArrayInputStream(ImageUtil.imageToBytes(img, "png"));` in this line, it works as expected. But it should probably fixed in Asset.getImage().

**Comment by Phergus** [comment]
That looks like what happens with a CMYK image that is displayed as if RGBA.

![image](https://user-images.githubusercontent.com/34379254/112519826-5bb69000-8d60-11eb-8640-f4e30d121df7.png)

**Comment by Irarara** [comment]
I'm not sure if `Asset.getImage()` should be touched. It's supposed to return the raw data, which it does. To be displayed properly it needs to be processed, which is why the cached version from `ImageManager` is fine. 

I can't speak to the design intent here, but I get the sense you're generally expected to go through `ImageManager` when dealing with fetching images to display (somebody correct me if I'm wrong). In that case, just calling `imageToBytes` on `img` probably _is_ the way to go.

**Comment by Phergus** [comment]
Yup.  Instead of modifying the `return` line just changing the `else` clause to:
```
} else {
          data = ImageUtil.imageToBytes(img, "png");
}
```
will fix the issue.

**Comment by thelsing** [comment]
I can check and prepare an pull request. The `Asset asset = AssetManager.getAsset(assetId);` [here](https://github.com/thelsing/maptool/blob/cfa752803beec88a5bcfe23e045b9f1313e653d8/src/main/java/net/rptools/maptool/client/AssetURLStreamHandler.java#L113) should be removed and the line after should check if `img != null`, right?

**Comment by Phergus** [comment]
No.  As @Irarara said, you need to use `ImageManager` to get get the `BufferedImage`.

Just need to change line 137 so that the `data` there is created with `ImageUtil.imageToBytes(img,"png")`

**Comment by Irarara** [comment]
Since `asset` isn't really needed there anymore you should be able to just remove it, yeah. And you really could just remove that entire if statement at 114 (and the following `else` block.) AFAIK, `getImageAndWait()` should never return null, it just returns `BROKEN_IMAGE` (the red X) if it can't find a valid image, so the check isn't necessary.

**Comment by Phergus** [comment]
My bad.  That's true.  `getImageAndWait()` should be logging failures to find the asset so the logging in 138-141 is redundant.

**Comment by thelsing** [comment]
Should I remove the comments in line 96 - 105 and 108?

**Comment by Phergus** [comment]
Yeah.  I don't see the need to keep the comments in 95 to 107.

**Comment by thelsing** [comment]
PR is complete.

**Comment by Phergus** [comment]
Reviewed.  Test images working as expected.
