### ISSUE TITLE
copyToken() relative to active token coordinates

### ISSUE THREAD

**Issue by SterLovesFood** [RPTools/maptool#2657]
**Is your feature request related to a problem? Please describe.**
copyToken() can not place a token relative to the coordinates of the currently active token.
I would like a way to have X:0,Y0 be the location of the current token and not the true coordinates on the map of 0,0.

**Describe the solution you'd like**
Parameter 'delta' within copyToken() uses the original position of the _copied_ token, not the current token. This is intended, but I've seen it confuse some people looking for what I'd believe to be the more common use for copyToken(), to create tokens near the relevant active token.

I'd like to be able to set 'delta' to '2' to make coordinates relative to current token.

**Describe alternatives you've considered**
I think it would have to be an additional setting within 'delta' to prevent any other new parameter from clashing with it.
There are alternatives to get the same end result within multiple lines of code, but this solution streamlines something simple and very useful.

**Comment by michaelperino** [comment]
LMK if you have some macros I can use as test cases to make sure everything is working right. The solution on the branch I'm pushing soon should be working close to your request. If delta is "2", it checks if the command originated from a trusted macro within a token. If not, it defaults back to the first selected token as the origin for the delta 2. If people think one of those use cases should be dropped (or a way to have an option for forcing selected/impersonated) that can be done as well.

**Comment by SterLovesFood** [comment]
> LMK if you have some macros I can use as test cases to make sure everything is working right.

I'm currently using something like this:

'[x=getTokenX(0)][y=getTokenY(0)]
[x = x+1]
[y = y+2]

[copyToken(TileType,1,"xData",json.set("{}","delta",0,"x",x,"y",y,"name",TileType))]'

This could just drop the first half of the code and set delta:2, simplifying the entry of x and y so it fights less with the other UDFs that lead to this code. If I understand what you are saying completely it sounds like that works for me in every case I currently have.

**Comment by michaelperino** [comment]
Thanks for getting back to me, wanted to make sure I fully understood the request. Within my test branch commit above, your code is equivalent to:
```
[copyToken(TileType,1,"xData",json.set("{}","delta",2,"x",1,"y",2,"name",TileType))]
```
The other behavior I discussed allowed using the position of a selected token as your source of delta 2 if you were using copyToken in a campaign macro and no impersonated token was found. If there are no selected or impersonated tokens when the macro is run, the location will default back to 0,0.

If anyone has a problem with these features or thinks they should have a different implementation, let me know.

**Comment by kwvanderlinde** [comment]
@michaelperino Came here after seeing your message in Discord, and I've also taken a look at the solution in your fork. I haven't actually tried it out yet, so what I'm about to say is based on your description of it, and my fallible reading of your changes. I'm going to go into quite a bit detail just so everything is super clear. Apologies for being so longwinded, or if I've made any errors in my reading.

First of all, based on your description, the code you posted **would not** match the behaviour of the @SterLovesFood's code except in certain (albeit common) circumstances. Their code always operates relative to the *current token* while yours always ignores the current token in favour of the token the macro is running on, or the impersonated token, or one of the selected tokens (any of which or none of which may be the same as the current token depending on the circumstances). The difference can be made clear by inserting this line prior at the top of each snippet, making sure `someOtherTokenId` is any token that is definitely not the token that the macro is running on, nor the impersonated token nor any selected token:
```
[h: switchToken(someOtherTokenId)]
```

Secondly, as far as I'm aware, there are no built-in functions that change their behaviour based on the impersonated. and especially not on which tokens are selected (aside from `getImpersonated()`, `getSelected()`, and similar of course). Instead, everything is based on the *current token* which can be changed locally without changing the impersonated or selected tokens. For consistency (and therefore less confusion), we should do the same thing for `copyToken()`.

Thirdly, it's kind of redundant to check whether it is called from a trusted macro on a token and otherwise falling back to the impersonated token. Actually, I'm noticing now that there is a discrepancy between your description and your code. Your description is similar to the process of determining the current token, except that it's missing a few details (such as what happens when the trusted macro is itself called by another macro on another token). However, your code actually does use current token first (`FunctionUtil.getTokenFromParam()` with negative indexes is basically just `resolver.getTokenInContext()` with error handling). It then tries to fall back to the impersonated token if no current token is found. However, the impersonated token is kind of the fallback case for the current token already, making that bit redundant.

Fourthly, we should be hesitant to rely on the order of lists, such as the list of selected tokens. I'm not even sure whether the order of selected tokens is meaningfully defined, but even so there is an inherent ambiguity from the user's perspective. I.e., to the user, it may seem arbitrary which one of the selected tokens gets picked, especially given some edge cases like some of the selected tokens being off screen without the user realizing it. If a user wants this functionality to apply to the selected tokens, they can do so explicitly by using `token():` or `switchToken()` together with `getSelected()`, or they can use `Apply to Selected Tokens` if that makes sense for their use case.

So all that was a longwinded way of saying that we should use the current token rather than any other scheme. It would be more consistent with other functions, is more general, and has better defined in edge cases. It would also significantly simplify the selection process down to basically a single line of code.

**Comment by Phergus** [comment]
> So all that was a longwinded way of saying that we should use the current token rather than any other scheme.

Agreed.  I believe that would match what the OP asked for and should be straight-forward to implement.

**Comment by michaelperino** [comment]
I tried to create a summary of the changes suggested to the copyToken function. Hopefully this table makes some sense. The PDF is just a copy of the conversation that led to the suggested changes. Let me know if anyone has any additional concerns or potential use cases to include beyond map, source, and current parameters.





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/MICHAE~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/MICHAE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





As of new commit   (2021-05-31 9:51 AM GMT) this is how the changes should operate. | &nbsp;
-- | --
Input | Output
absolute   position | All create a single copied token at global   coordinates 1,1
[copyToken("Eagle   1",1,"Grasslands","{x:1,y:1}")]
[copyToken("Eagle   1",1,"Grasslands","{'x':1,'y':1,'delta':0}")]
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","delta",0,"x",1,"y",1))]
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","relativeto","map","x",1,"y",1))]
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","relativeto","MaP","x",1,"y",1))]
&nbsp; | &nbsp;
relative to copied 'token' | All create a single copied token offset from the original by 1   in both x and y
[copyToken("Eagle   1",1,"Grasslands","{x:1,y:1,delta:1}")]
[copyToken("Eagle   1",1,"Grasslands","{'x':1,'y':1,'relativeto':'SOURCE'}")]
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","relativeto","souRCE","x",1,"y",1))]
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","delta","&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   ","x",1,"y",1))]
&nbsp; | &nbsp;
relative to in context 'token' | All create a single copied token offset from in context token by   1 in both x and y
[copyToken("Eagle   1",1,"Grasslands","{x:1,y:1,relativeto:current}")]
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","relativeto","CURrenT","x",1,"y",1))]
&nbsp;
&nbsp; | &nbsp;
error for missing map | No puedo encontrar el mapa "FakeMapName" en la función   "copyToken".\nError trace : (new)@Token:Eagle
[copyToken("Eagle   1",1,"FakeMapName","{x:1,y:1,relativeto:current}")]
&nbsp;
&nbsp; | &nbsp;
error for conflicting   arguments | In "copyToken": Parameters "delta" and   "relativeto" cant be used at the same time. ("delta"   parameter is deprecated as of 1.9.0). Visit   https://wiki.rptools.info/index.php/copyToken\nError trace :   (new)@Token:Eagle
[copyToken("Eagle   1",1,"Grasslands","{x:1,y:1,relativeto:source,delta:1}")]
&nbsp;
&nbsp; | &nbsp;
error for unresolvable   relativeto | In "copyToken": "relativeto" value within   4th parameter (json properties) not recognized. Visit   https://wiki.rptools.info/index.php/copyToken\nError trace :   (new)@Token:Eagle
[copyToken("Eagle   1",1,"Grasslands","{x:1,y:1,relativeto:currenty}")]
&nbsp;
&nbsp; | &nbsp;
error for no current token | No current token found. Try using switchToken() or impersonate   one. See https://wiki.rptools.info/index.php/Current_Token\nError trace :   chat
[copyToken("Eagle   1",1,"Grasslands",json.set("{}","relativeto","souRCE","x",1,"y",1))]
&nbsp;






[2657 work completed.pdf](https://github.com/RPTools/maptool/files/6569479/2657.work.completed.pdf)

**Comment by Phergus** [comment]
Looks great Mike except for the last error.  Using `relativeto:source` shouldn't require a current token.  Source in your example would be "Eagle 1".  Lots of macros are run without a current token from the Campaign, GM and Global panels.

**Comment by michaelperino** [comment]
Whoops, typo on my part. That was run with relative to:current while there was no token selected or impersonated (I just ran the command through chat for that example).

**Comment by Phergus** [comment]
This macro works on 1.7.0, 1.8.5, 1.9.0 beta 2 but does nothing with code from #2691 
```
[h: cloneNo = 0]
[h: x = 0]
[h: facing = 0]
[h: updates = json.set("{}",
	"name", "Hero Clone - [r: cloneNo = cloneNo + 1]",
    "delta", 1,
    "x", "[r: x = x + 2]",
    "facing", "[r: facing = facing + 40]"
)]
[h: copyToken("Hero", 2, "Grasslands", updates)]
```

This macro places the two copies on top of the original:
```
[h: cloneNo = 0]
[h: x = 0]
[h: updates = json.set("{}", 
	"name",  "Hero Clone - [r: cloneNo = cloneNo + 1]",
	"relativeto", "map",
	x, "[r: x = x + 2]"
)]
[h: copyToken("Hero", 2, "Grasslands", updates)]
```

**Comment by Phergus** [comment]
The `relativeto` option looks to be working as expected.

Documentation complete.

**Comment by Phergus** [comment]
@michaelperino are you going to have a fix for the issue above?

**Comment by michaelperino** [comment]
Missed that comment, I'll take a look after work. Sorry, feel free to at me on discord if I don't get back to you on something.

**Comment by michaelperino** [comment]
> 
> 
> This macro works on 1.7.0, 1.8.5, 1.9.0 beta 2 but does nothing with code from #2691
> 
> ```
> [h: cloneNo = 0]
> [h: x = 0]
> [h: facing = 0]
> [h: updates = json.set("{}",
> 	"name", "Hero Clone - [r: cloneNo = cloneNo + 1]",
>     "delta", 1,
>     "x", "[r: x = x + 2]",
>     "facing", "[r: facing = facing + 40]"
> )]
> [h: copyToken("Hero", 2, "Grasslands", updates)]
> ```
> 
> Changing delta to 0 also fails to produce a result on current code.

It has a response: if you zoom out, the tokens are just 120 tiles south of where they should be :). Should be fixed in a few.

**Comment by Phergus** [comment]
Yup I didn't zoom out far enough or look at the Map Explorer, Doh!

**Comment by michaelperino** [comment]
Both cases should work as expected (the Elf indicates 0,0). 
![image](https://user-images.githubusercontent.com/33206261/120717354-02b85600-c48d-11eb-98af-1bacd8fc364a.png)

```
[h: cloneNo = 0]
[h: x = 0]
[h: facing = 0]
[h: updates = json.set("{}",
	"name", "Hero Clone - [r: cloneNo = cloneNo + 1]",
    "delta", 1,
    "x", "[r: x = x + 2]",
    "facing", "[r: facing = facing + 40]"
)]
[h: copyToken("Hero", 2, "Grasslands", updates)]

[h: cloneNo = 0]
[h: x = 0]
[h: facing = 0]
[h: updates = json.set("{}",
	"name", "Hero Clone - [r: cloneNo = cloneNo + 1]",
    "delta", 0,
    "x", "[r: x = x + 2]",
    "facing", "[r: facing = facing + 40]"
)]
[h: copyToken("Hero", 2, "Grasslands", updates)]
```

I'll edit the pull request after I run my tests on the table code fragments to make sure nothing else changed.

**Comment by Phergus** [comment]
Tested new code.  Working as expected.
