### ISSUE TITLE
AI pathfinding behaves suboptimally and inconsistently when using 1-2-1 movement with token terrain modfiers

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2696]
**Describe the bug**
When using 1-2-1 movement, the pathfinding sometimes chooses to go through tokens with a terrain cost when going around is more optimal. In other cases, it avoids the terrain by multiple cells when not necessary. Moreover, the difference in behaviour can be quite drastic depending on the route taking to get to the problematic terrain.

**To Reproduce**
1. Ensure that "Movement metric" is set to "One-Two-One" in the preferences dialog
2. Create a new map with a square grid. I use 5.0 cell distance, but this shouldn't matter.
3. Create a line of 5 terrain tokens as shown in the attached screenshots. Set each token's Terrain Modifier to Add 5.0
4. Create one more token to use for pathfinding
5. Place the pathfinding token above and to the left of the terrain tokens, with one diagonal grid space between (shown in the screenshots). Then try each of these scenarios:
    1. Drag the token along the line of terrain tokens, to any position between the terrain tokens (or an odd number of cell past the last terrain token). Notice that the path goes straight through the entire line of tokens.
    2. Drag the token one cell down, set a waypoint (right click), then drag to the same destinations as the previous step. Notice the path avoids all terrain tokens and results in a cheaper (even optimal) route.
    3. Drag the token along the line of terrain tokens, to any position coinciding with a terrain token (or an even number of cells past the last one). Notice that the route dodges all the terrain tokens and gives an optimal route.
7. Now place the token immediately above and to the left of the terrain tokens. Then try each of these scenarios:
    1. Drag the token along the line of terrain tokens, to any position between the terrain tokens. Notice that the path goes straight through the entire line of tokens.
    2. Drag the token one cell down, set a waypoint (right click), then drag diagonally until right next to the destination, set another waypoint, then move one cell to the right to get to one of the same destination as the previous step. Notice this path is forced to avoid all terrain tokens and results in an optimal route.
    3. Drag the token along the line of terrain tokens, to any position coinciding with a terrain token. Notice that the route goes through all the terrain tokens.
    4. Drag the token one cell down, set a waypoint, then drag it onto a terrain token. Notice that this path avoid all but the last terrain token and gives and optimal route.
    5. Drag the token to the location immediately below and to the right of the last terrain token. Notice the path avoid all terrain tokens, and even veers further away for the final two terrain tokens.
    6. Drag the token down one cell, set a waypoint, then drag to the cell immediately below and to the right of the last terrain token. Notice the path avoid all terrain tokens, does not veer at the end and results in an optimal route.

**Expected behavior**
First of all, the path should never veer away from the target when doing so gives a higher route length.

Secondly, the pathfinding algorithm should dodge terrain if that leads to suboptimal paths.

**Screenshots**

Setup for 5: 
![5](https://user-images.githubusercontent.com/7492219/120586830-1c07c680-c3e9-11eb-87c5-450c199b589f.png)
5.i: 
![5 1](https://user-images.githubusercontent.com/7492219/120586842-20cc7a80-c3e9-11eb-9811-401079f04780.png)
5.ii
![5 2](https://user-images.githubusercontent.com/7492219/120586847-24600180-c3e9-11eb-9e7a-f93b6cd06562.png)
5.iii
![5 3](https://user-images.githubusercontent.com/7492219/120586855-288c1f00-c3e9-11eb-8d98-f1e7f54195e7.png)

Setup for 6:
![6](https://user-images.githubusercontent.com/7492219/120586862-2cb83c80-c3e9-11eb-8610-a096cfb41575.png)
6.i
![6 1](https://user-images.githubusercontent.com/7492219/120586867-2fb32d00-c3e9-11eb-9a4e-8ec38818c169.png)
6.ii
![6 2](https://user-images.githubusercontent.com/7492219/120586874-32ae1d80-c3e9-11eb-8ec4-f18d93b4c285.png)
6.iii
![6 3](https://user-images.githubusercontent.com/7492219/120586891-380b6800-c3e9-11eb-80b6-2cd2c89cea36.png)
6.iv
![6 4](https://user-images.githubusercontent.com/7492219/120586899-3cd01c00-c3e9-11eb-8af7-7da803e91f5c.png)
6.v
![6 5](https://user-images.githubusercontent.com/7492219/120586912-4194d000-c3e9-11eb-8883-fa4c528da23e.png)
6.vi
![6 6](https://user-images.githubusercontent.com/7492219/120586919-45c0ed80-c3e9-11eb-9163-eda87dc34cf0.png)

**MapTool Info**
- Version: 1.8.3, observed in develop as well
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**
This issue is specific to square grids with 1-2-1 movement as it depends on the fact that the cost of a particular cell move depends on the route taken to get to that cell in the first place. This is the only scheme with this property (it also happens for iso grids, but those are just a squashed view of square grids from pathfinding perspective). In every other case, movement between any two cells is consistent. E.g., manhattan *always* treats diagonals as 2 cells' worth of movement, and others as 1 cell. For hex grids, everything costs one cell of movement.

**Comment by kwvanderlinde** [comment]
I found this issue while reading the pathfinding code as part of #2355. The underlying cause is quite simple:
- For "odd" diagonal movement, we apply a cost of **1 cell**.
- For "even" diagonal movement we apply a cost of **1.5 cells**.

Obviously, that is a 1-1.5-1 metric, not a 1-2-1 metric (though the displayed cost is correctly calculated as 1-2-1!).

There are two ways to try fixing this. The first and obvious way is to fix this 1-1.5-1 metric and make it a 1-2-1 metric. But after implementing that "fix" the problem actually gets worse! E.g., we get this wild weaving behaviour: 
![1-2-1 metric](https://user-images.githubusercontent.com/7492219/120589081-2c21a500-c3ed-11eb-9154-3e6da23784b8.png)
Fundamentally, the issue with 1-2-1 is that it breaks the assumptions of A*, in that the cost of movement can change significantly (an entire cell's worth, even without counting modifiers) depending on the route taken prior to the move. So unless we move to a more general algorithm that can handle changing movement costs, we kind of have no choice but to avoid 1-2-1 with pathfinding.

The second way to fix this is to always apply a 1.5 cell cost for diagonal movement, regardless of whether it is an odd or even diagonal. I.e., ignore the 1-2-1 metric itself and itself the metric it was meant to approximate (which actually is a metric, unlike 1-2-1). It can be shown that, in the absence of terrain modifiers, the 1.5 metrics always produces the same ideal routes as the 1-2-1 metric. Also, I believe (but haven't quite shown yet) that both give the same ideal routes in the presence of additive terrain modifiers, since such terrain always adds the same amount to the route if used. Multiplicative terrain modifiers may show a difference between 1.5 and 1-2-1, but that entirely depends on how terrain modifiers ought to behave with the 1-2-1 rule. E.g., does the terrain cost apply when entering, leaving, or are those cases each 50% of the penalty? Intuitively, using the 1.5 metric gives the same route as 1-2-1 in the case that a move's cost comes half from the source cell and half from the target cell, which seems a good compromise to me.

Given that 1.5 tends to give the same results as 1-2-1, and works with A*, I would suggest we take the second approach.

**Comment by FullBleed** [comment]
> Secondly, the pathfinding algorithm should dodge terrain if that leads to suboptimal paths.

This is somewhat of a tangent...

I started using my own movement method (with a clickable movement pad) long before pathing and terrain modifiers were available (in part because they weren't.)  So I don't (currently) have a horse in this race.  But, I'm not sure if I agree with the above assertion... even though I acknowledge that if that's the intended behaviour it should be fixed (as you've noted.)

But when playing a game with "hidden" terrain modifiers a player does not always know that stepping into the next square is going to be "difficult terrain".   Nor does a character always choose to take the path of least resistance for various reasons (maybe they're running through a tangle of vines or webs to clear the terrain for the next person.)

So, I wonder if there should be an option on terrain tokens that could indicate that pathfinding AI avoidance/optimization should not apply? 

EDIT:  After typing the above I see that there is supposed to be a way to go through difficult terrain by using spacebar waypoints through the terrain (sounds annoying)... but, again, this doesn't deal with the surprise difficult terrain where you don't know it's difficult until you're in it. 

Anyway, I mention this now because if you've got your fingers in it, now might be the time to add the option.  ;)

**Comment by cwisniew** [comment]
> Fundamentally, the issue with 1-2-1 is that it breaks the assumptions of A*, in that the cost of movement can change significantly (an entire cell's worth, even without counting modifiers) depending on the route taken prior to the move. So unless we move to a more general algorithm that can handle changing movement costs, we kind of have no choice but to avoid 1-2-1 with pathfinding.

This is not really a problem and A* can handle it fine as A* makes no assumptions on how the cost is calculated between one point and the next. As far as an A* algorithm is concerned each point is just a node in a graph and the cost to get between the two is a just a number and it doesn't really care how its calculated. So determining if it's an odd or an even diagonal and adjusting the cost to get to the next cell based on that isn't a problem in of itself and nothing that breaks A*. 





> 
> The second way to fix this is to always apply a 1.5 cell cost for diagonal movement, regardless of whether it is an odd or even diagonal. I.e., ignore the 1-2-1 metric itself and itself the metric it was meant to approximate (which actually is a metric, unlike 1-2-1). It can be shown that, in the absence of terrain modifiers, the 1.5 metrics always produces the same ideal routes as the 1-2-1 metric. Also, I believe (but haven't quite shown yet) that both give the same ideal routes in the presence of additive terrain modifiers, since such terrain always adds the same amount to the route if used. Multiplicative terrain modifiers may show a difference between 1.5 and 1-2-1, but that entirely depends on how terrain modifiers ought to behave with the 1-2-1 rule. E.g., does the terrain cost apply when entering, leaving, or are those cases each 50% of the penalty? Intuitively, using the 1.5 metric gives the same route as 1-2-1 in the case that a move's cost comes half from the source cell and half from the target cell, which seems a good compromise to me.
> 
> Given that 1.5 tends to give the same results as 1-2-1, and works with A*, I would suggest we take the second approach.



The correct cost for a diagonal should be 1 for odd and 2 for even as this will work for no modifier, additive modifiers and multiplicative modifiers. Using 1.5 as a constant diagonal cost works only for first two cases and not when there is a a high modifier (say 2x cost) as that raises the cost of a first diagonal. 


You could argue that there is a problem created in the situation where you are looking for a path from A -> C and multiple paths pass through B at same cost but differing number of diagonals (one even one odd) as its then possible for the B -> C part to be non equal on two different paths even though they should. But since A* is returning an optimal path not every optimal path if its the optimal path one of the choices will still match so it will be ok. 

So a cost based on current path is not what is breaking the A* path finding, it's the fact that the current cost metric for diagonals is wrong which gives you results you don't expect. And given what your 1-2-1 examples above show I think 1.5 was selected because it is more aesthetically pleasing (probably trial and error involved in that), so 1-2-1 is correct even though it looks uglier, A* produces an optimal path not the most aesthetically pleasing optimal path... Usually afterwards you would use a string pulling / funnel algorithm but that doesn't work well when you have cost modifiers as it can return paths that look better but are no longer optimal.


Another way to do it is introduce a second cost (There is nothing that says there has to be be a single cost as part of the cost determination function) and can be used as a tie breaker if the first costs are equal. It could be something as simple as 0 if the direction is different to last direction travelled, 1 if it's the same, or 1 if it reverse x or y of last movement (so zig zag) .5 if its same direction, .1 otherwise. This would tend to keep the path going in a straighter line with less zig zag or wandering back and forwards effect but would probably take some tweaking with trial and error to see which tie breaker costs look best. 

You don't need to do anything fancy for the "estimated" remaining heuristic just always use 1 for diagonals, the important thing is the heuristic DOESN'T over estimate the remaining steps, under estimates are fine. Just using 1 though could lead to issues if there is a terrain modifier which reduces cost if there are no other obstacles requiring navigating between current cell and destination.

**Comment by Phergus** [comment]
As Craig suggests using the true 1-2-1 produced really ugly paths and there was much complaining about it leading to using 1.5.  If you go back in issue history to when the A* and terrain modifiers were being added you can probably find some discussions about this.

**Comment by kwvanderlinde** [comment]
> This is not really a problem and A* can handle it fine as A* makes no assumptions on how the cost is calculated between one point and the next. As far as an A* algorithm is concerned each point is just a node in a graph and the cost to get between the two is a just a number and it doesn't really care how its calculated. So determining if it's an odd or an even diagonal and adjusting the cost to get to the next cell based on that isn't a problem in of itself and nothing that breaks A*.

Yes, the cost of moving from one node to the node can be anything, but it does have to be a *fixed* value. I.e., moving from a given node A to its neighbour B must always costs some value `c(A, B)`. But with a path-dependent metric, that cost can fluctuate based on factors other than the node themselves. As this does not satisfy A* assumptions, we can't rely on A* producing optimal routes, and this report demonstrates shows how it can pick suboptimal paths for 1-2-1 and 1-1.5.1.

> So a cost based on current path is not what is breaking the A* path finding, it's the fact that the current cost metric for diagonals is wrong which gives you results you don't expect. And given what your 1-2-1 examples above show I think 1.5 was selected because it is more aesthetically pleasing (probably trial and error involved in that), so 1-2-1 is correct even though it looks uglier, A* produces an optimal path not the most aesthetically pleasing optimal path... Usually afterwards you would use a string pulling / funnel algorithm but that doesn't work well when you have cost modifiers as it can return paths that look better but are no longer optimal.

To be clear, the example given in my comment isn't about the aesthetics - it's about the route being suboptimal. The wide veer around the second and third terrain tokens adds cost to the route that isn't necessary. Just straightening out that segment results in an optimal route: 
![Optimal 1-2-1](https://user-images.githubusercontent.com/7492219/120678666-32e00480-c44d-11eb-8520-afe797f2c52b.png)
Note that I put waypoints exactly on the path given by the 1-2-1 algorithm, past where the curve was, yet the curve is smoothed out in this case.

**Comment by cwisniew** [comment]
> > This is not really a problem and A* can handle it fine as A* makes no assumptions on how the cost is calculated between one point and the next. As far as an A* algorithm is concerned each point is just a node in a graph and the cost to get between the two is a just a number and it doesn't really care how its calculated. So determining if it's an odd or an even diagonal and adjusting the cost to get to the next cell based on that isn't a problem in of itself and nothing that breaks A*.
> 
> Yes, the cost of moving from one node to the node can be anything, but it does have to be a _fixed_ value. I.e., moving from a given node A to its neighbour B must always cost some value `c(A, B)`. But with a path-dependent metric, that cost can fluctuate based on factors other than the node themselves. As this does not satisfy A* assumptions, we can't rely on A* producing optimal routes, and this report demonstrates that it can pick suboptimal paths for 1-2-1 and 1-1.5.1.

But this is not likely be caused of the 1-2-1 cost. If the 1-2-1 metric cost is set up correctly then the cost of the path you forced with way points (the straighter less expensive path) is same for A* calculated cost. 

In your example above even using 1-2-1 the cost calculation for the path is shown below in red.

![image](https://user-images.githubusercontent.com/73173/120690434-5b670d80-c4e4-11eb-8c6c-db7f381aabeb.png)

The problem appears that the A* is not calculating this path as it sees it more expensive based on the heuristic part of the algorithm and discards it. So rather than varying cost based on path already traversed its the estimated cost for the path remaining that appears to be incorrect. So my first guess would be the heuristic is off.

And taking a quick look at the code seems to back that up -- although its way past that time of the early morning for code to make complete sense for me -- it looks like using a diagonal cost of 1.5 for every diagonal. This would explain the tendency for it to veer off down a vertical path near the start and disregard the diagonal as a potentially shorter path and not calculate it. It would also explain why you get a much better result by setting the diagonals to always use 1.5 as that matches what the heuristic part is saying the expected cost is. What would be happening is the following, you have an odd number of diagonals in your example above this means the heuristic overestimates the cost for the diagonal path which makes it non consistent, and the problem with non consistent heuristics in A* is they can cause non optional results.

**Comment by cwisniew** [comment]
It should be easy enough to test the above and see if it is the case / quickly rule it out
I think if you alter AStarSquareEuclideanWalker
![image](https://user-images.githubusercontent.com/73173/120694351-3e810900-c4e9-11eb-9789-851a151e6087.png)

This will remove that potential problem so it can be verified if that is the case or not

**Comment by kwvanderlinde** [comment]
The heuristic is calculated in `AStarSquareEuclideanWalker::metricDistance()`, which does give the expected results for 1-2-1, since it floors the result of (1.5 * # of diagonal movements):
- floor(1.5 * 1) = 1
- floor(1.5 * 2) = 3
- floor(1.5 * 3) = 4
- floor(1.5 * 4) = 6
- etc.

In `AbstractAStarWalker::getNeighbors()`, the diagonal multiplier is conditionally applied when calculating the actual path cost, which makes the path cost disagree with the heuristic by half a cell for each even diagonals. But I already experimented with changing that to 1-2-1 to agree with the heuristic, and that resulted is suboptimal behaviour as well. So this isn't an issue of discrepancy between heuristics and actual cost.

**Comment by cwisniew** [comment]
Have you tried changing the hueristic to just one? Because having it calculate 1-2-1 can still lead to a non consistent hueristic as it's not considering current diagonals taken. Using 1 as a diagonal cost will never end up over estimating so will always be consistent (disregarding modifiers that reduce cost of course).

If that also doesn't work we will have to look for another solution as setting it to 1.5   flat will just break it in other ways.

**Comment by kwvanderlinde** [comment]
Yeah, I did try that, and it resulted in paths that cut through the terrain tokens. So that's not it. Also, the 1-2-1 heuristic shouldn't overestimate either. Maximizing diagonals is most efficient, so that part is good. And it either agrees with the current path state (both want 1+2+1+...) or it doesn't (path wants 2+1+2+... but heuritics does 1+2+1). Either way, the heuristic is less than or equal to what the path would want.

I did find a pretty bad thing, though. We aren't reordering the priority queue (`openList`) after a cell's f-score changes! If I fix that, behaviour becomes optimal for 1-2-1. E.g.,: ![1-2-1 after fixing priority queue](https://user-images.githubusercontent.com/7492219/120707509-43a17200-c46f-11eb-8a11-f58a21fe7537.png)

**Comment by kwvanderlinde** [comment]
Unfortunately that's not the end of the story. This is what it looks like when trying to go completely diagonally: 
![fixed-priority-queue-funny-but-optimal-path](https://user-images.githubusercontent.com/7492219/120720984-dc40ed80-c481-11eb-833b-da1a75e72631.png)
That is actually an optimal path, just as good as if the movement ran right along the terrain tokens. But on a whim I tried interfering with this path with some more terrain and doing the same thing, and then I got a suboptimal path: 
![fixed-priority-queue-still-suboptimal](https://user-images.githubusercontent.com/7492219/120721126-13170380-c482-11eb-8650-d2ad5df40e97.png)
That's using 1-1.5-1 g-score, but an almost identical situtation happens for 1-2-1 g-score:
![fixed-priority-queue-suboptimal-path-1-2-1](https://user-images.githubusercontent.com/7492219/120721588-02b35880-c483-11eb-9701-53e25c627035.png)
This would be an optimal path: 
![fixed-priority-queue-optimal-path](https://user-images.githubusercontent.com/7492219/120721168-25913d00-c482-11eb-9000-cf45049467a3.png)

At this point I tried setting the diagonal multiplier to 1 inside the heuristic function, while keeping 1-2-1 for g-scores. At first that seemed to do the trick, but one more modification exposed another problems: 
![fixed-priority-queue-unit-multiplier-suboptimal-path](https://user-images.githubusercontent.com/7492219/120722116-0c898b80-c484-11eb-9133-cd606c5f9d6e.png)
An optimal route would be the basically the same as above, just finishing in the cell over. The cost should only be 75.

Using a 1-1-1 in the heuristic while using 1-1.5-1 for g-score works for this case. But it fails to give optimality for other cases: 
![fixed-priority-queue-1-1-1,1-1 5-1-suboptimal](https://user-images.githubusercontent.com/7492219/120723582-e0233e80-c486-11eb-8448-60b009024226.png)
Vs the optimal: 
![fixed-priority-queue-1-1-1,1-1 5-1-optimal](https://user-images.githubusercontent.com/7492219/120723633-f6c99580-c486-11eb-9610-fa670af88967.png)

**Comment by cwisniew** [comment]
The diagonal cost of 1 I think is ok to live with yes its not optimal but its still better than having no heuristic in our most common use cases. A quick look at the code shows there is a differing neighbourhood map for even/odd diagonals if we have a 1 cost it should probably be the same.

The last one is odd, I suspect that the g cost is not calculated correctly or not updated, its probably worth turning on the debug (I think you have to set the instance variable and recompile to do that) to see the g.costs are actually what you expect while moving.

**Comment by kwvanderlinde** [comment]
I tried turning on the debugging and got loads of errors showing. I had to settle for logging each current node/new node/updated node and digging through that. Still have to dig through exactly what is going on with my last example. Will update when I discover what it is.

I can put together a PR this weekend to fix the priority queue and maybe tweak the heuristic. That simple change would remove the really bizarre cases in this report.

**Comment by kwvanderlinde** [comment]
I've finally put together an example that clearly shows what I mean about A* not being able to handle 1-2-1 properly. All it takes is one cell of 2x terrain and some constraints on the path. The idea is this:
- A diagonal move into this terrain will either cost 2 or 4 cells of movement depending on the prior route. That difference of 2 cells can be exploited.
- We'll force all paths to take the same diagonal move into this terrain. I.e., all paths have to go through a common cell just before entering the terrain on a diagonal.
- We'll setup a situation with only two valid paths, where one path takes an odd number of diagonal steps to get to the common cell (expensive step into the 2x terrain), and the other path takes an even number (cheap step into the 2x terrain).
  - More than that, we'll make A* try the odd path first. That is, until it encounters the 2x terrain and realizes the mistake, but then (as we'll show) it's too late!

Here is the simplest setup I could create with these constraints: 
![multiplicative-distinguish-1-2-1-from-2-1-2-cropped](https://user-images.githubusercontent.com/7492219/120849121-82e0c900-c52a-11eb-91db-af635d4bb487.png)
The `(!)` tokens are blocking terrain, the `($)` token is 2x terrain. The token `(*)` starts at (0, 0) and ends at to (2, 3).

The shown path is suboptimal since moving into the 2x terrain will cost 4 cell's movement (2 for even diagonal, 2x for terrain). By contrast, the optimal path would take that diagonal for only 2 cell's movement (1 for odd diagonal, 2x for terrain), and would give a total path cost of 25.

Here's what's happening from A*'s perspective:
1. Only the start cell (0, 0) is in the queue. A* visits and closes it.
    - The neighbor cells (0, 1) and (1, 1) are evaluated and queued.
2. The cell (1, 1) is looks cheapest, so A* visits and closes it next.
    - In MapTool, (1, 1) is cheaper than (0, 1) because the heuristic has a built in preference for straight lines from the start to the goal. Without that preference, the estimated costs are equal and so the selection would depend on the specific behaviour of the priority queue. As it happens, MapTool would still pick the (1, 1) first, in general A* could pick either. Still, we'll assume this case as it is a valid selection and exposes the issue.
    - The cell (0, 1) is re-evaluated as a neighbour of (1, 1). But it is not updated since doing so would make it more expensive.
    - The neighbour cell (2, 2) is evaluated and queued, and it's quite expensive!
3. The cell (0, 1) now looks cheapest, so A* visits and closes it next.
    - Cell (0, 1) has no open cells in its neighbourhood, since (1, 1) and (0, 0) have already been closed. This route gets abandoned.
4. Only cell (2, 2) remains in the queue, so A* visits and closes it.
    - The neighbour cell (3, 3) is queued.
5. Only cell (3, 3) is available. It's also the goal, so the route is complete.

The mistake happens in step (2), which causes the problem in step (3). With nowhere to go, there is no way for the optimal route to be selected at that point.

Note that this is not just a detail of MapTool's behaviour, it's something I built to break A* in general. This also isn't about choosing a different heuristic since the mistake is with the very first move, where the true cost is identical for both possibilities. Yes, the heuristic could be changed to bias the other route, but that just requires a different example to show the same underlying problem.

**Comment by kwvanderlinde** [comment]
This is solvable, though. We just need a graph whose nodes don't have path-dependent costs. This can be done by splitting each cell into two nodes, one for odd-diagonal paths and one for even-diagonal paths. These nodes are completely distinct from one another, they just happen to correspond to the same (x, y) coordinates. So they are queued separately and have their own f, g, and h scores. The h-score can account for the evenness of the path, or it can be kept as a simpler underestimate. The g-score is always calculated using with the true cost of movement.

This satisfies the constraints of A*. An optimal path through this graph is converted to an optimal path on the map by dropping the even/odd discriminator.

**Comment by kwvanderlinde** [comment]
I've looked further into the unusual case for the 1-1-1 heuristic / 1-1.5-1 g-score. To show what's happening, I've added the g-score to the path renderer debugging: 
![heuristic-1-1-1-g-1-1 5-1-suboptimal-debug](https://user-images.githubusercontent.com/7492219/120903282-2b119300-c5fa-11eb-983d-8178f7278867.png)
And for the optimal path:
![heuristic-1-1-1-g-1-1 5-1-optimal-debug](https://user-images.githubusercontent.com/7492219/120903286-31a00a80-c5fa-11eb-8a3c-13df84f4384e.png)

The numbers are in this order:
1. true 1-2-1 cost (in map units) This gets shown to users, but has no impact on pathfinding.
2. pathfinding cost without terrain (in number of cells). Cost of the path disregarding terrain modifiers. Used to track even/odd diagonals.
3. g-score (in number of cells). I.e., the actual path cost as calculated by A*. Need to add this to the g-score of the last waypoint to know the total true cost for that path.

If the token weren't in the way, we would see that the last cell has a g-score of 12 for both paths, even though the first path has a true cost of 70 and the second a cost of 65. So both paths perform equally from a pathfinding perspective, even though the true costs differ. It's worth pointing out as well that 70 / 5 = 14, and 65 / 5 = 13, so A* is given a path cost that underestimates the true cost. This is a natural consequence of the discrepancy between the displayed 1-2-1 cost of the path (average of 1.5 for diagonals, or 2 diagonals equals 3 straights) vs the g-score being calculated using 1-1.5-1 (average of 1.25 for diagonals, or 4 diagonals equals 5 straights).

To be a little loose with the interpretation, what the given setup allows is a "trade" between straights and diagonals, one that takes advantage of cheap diagonals and which wouldn't be possible under 1-2-1. The trade is (4 straights + plus 3 cells terrain) for (4 diagonals + 2 cells terrain). The four diagonals is the key, since those are equivalent in cost to 5 straights, making this a fair trade of 7 for 7. The fact that such a trade exists isn't a problem _per se_, but the depressed cost of diagonals means that 1-1.5-1 allows trades that 1-2-1 wouldn't.

**Comment by kwvanderlinde** [comment]
> As Craig suggests using the true 1-2-1 produced really ugly paths and there was much complaining about it leading to using 1.5. If you go back in issue history to when the A* and terrain modifiers were being added you can probably find some discussions about this.

I wasn't able to any such discussion, which is too bad because I was hoping to look at some of the ugly examples. I did find two interesting bits in the commit history though.

The first is from the dawn of git-time: 135f6e95835040724b6853120b21e979a588ebc3. The issue with the priority queue already existed back then, so it could be that the cause of the complaints was actually the priority queue bug rather than 1-2-1 _per se_.

The next interesting commit is where the flat 1.5 cost gets split into 1-1.5-1: 78069712968b636765e84f881ba859782f0cd5c3. No mention about aesthetics in the message (doesn't mean much in itself), but it reads like the intent there was to do 1-2-1, not 1-1.5-1.

**Comment by Phergus** [comment]
It's quite possible the cause was something other than the use of 1-2-1.  I recall a number of map images being posted showing paths chosen that while equivalent in cost were not "natural-looking".  I think at least some of them ended up on GitHub issues but may have been mostly in Discord.

This illustrates at least one of the cases:
![image](https://user-images.githubusercontent.com/34379254/120906489-11cb0f80-c617-11eb-84ec-9f4aa5431b08.png)
The pathfinding algo was choosing the top path instead of the lower one that MT chooses now.

While better it isn't as "natural" as this one:
![image](https://user-images.githubusercontent.com/34379254/120906607-1ba14280-c618-11eb-875b-679f3b2ad410.png)

**Comment by kwvanderlinde** [comment]
I did the same example, with a reference line drawn center to center from start to finish. Aesthetically, I would think the path should follow that line pretty closely. With the fixed priority queue, g using 1-2-1, and h using 1-1-1, the chosen path is not bad: 
![fixed-priority-queue-unaesthetic-path](https://user-images.githubusercontent.com/7492219/120916416-65ad1700-c65e-11eb-9655-0b62e1299422.png)
Not quite as aesthetic as your ideal path, but it's just as well if not a little better than the current behaviour you showed.

The algorithm "shys away" from taking some of the diagonals (like at the end of the straight segment of four cells), because the actual cost for the diagonal move is 2 but h only reduces by 1. If I make h more accurate, by making it a 1-2-1 heuristic that accounts for the prior number of diagonals, it becomes a very nice approximation of the line: 
![fixed-priority-queue-aesthetic-path](https://user-images.githubusercontent.com/7492219/120917201-baeb2780-c662-11eb-80c3-c0267168696a.png)

The heuristic's tiebreaker is playing an important role here by punishing paths that aren't parallel to the start-to-finish line. Otherwise other less nice paths would still be picked. It seems to me that it's important for the heuristic to be accurate in order for the tiebreaker to have a consistent effect. Otherwise, the tiebreaker doesn't have sufficient impact in some important decisions between diagonal and straight steps that would yield equality optimal paths.

**Comment by Phergus** [comment]
Accuracy and consistency are more important than aesthetics because players should always consider the use of waypoints to have the characters travel the path that makes sense to them.  However if the path that is most balanced about the line of travel can be chosen out of a set of equal cost paths that would be ideal.

**Comment by FullBleed** [comment]
Are we approaching the need for players to have to choose between multiple pathing options (like multiple route choices in a navigation app)?

If so, I'd consider the following method:

1)  If a waypoint is dropped at the end of the move, upon release of the left click the token would go into a Path Selection Mode before executing the move.
2)  Then allow the mouse wheel to scroll through the various path options (arrow keys for keyboard), with a single left click choosing the selected path and completing the move.

If players don't have a problem with the "default" drag they won't bother looking at the alternatives.

**Comment by Phergus** [comment]
> Are we approaching the need for players to have to choose between multiple pathing options (like multiple route choices in a navigation app)?

Need?  No.  It could be put in as a feature request however.

**Comment by Phergus** [comment]
Tested.  Pathing much improved and overall better looking.  A couple of cases where previously a valid path would not be found are now working.
