### ISSUE TITLE
Autoresize a whole token without the need to select it

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#2703]
**Is your feature request related to a problem? Please describe.**
When you add a token as background, and you want to resize it, you have to select part of it. This is annoying because you know exactly the size of the whole token, and you would like to use it. 

**Describe the solution you'd like**
I want either a new entry in the right mouse menu or a modifier which allows me to use the whole size of the token in the auto-resize option.

**Describe alternatives you've considered**
I have tried to select the whole token, but it's very hard to get the border of it. Moreover, as the token represents a background map, it tends to be quite large, and with that the precision of your pointer is low.

**Additional context**
This is very useful if you have a map and you want to use it without the grid lines.

**Comment by emmebi** [comment]
I will give it a shot in the week-end unless someone has an objection on this.

**Comment by Azhrei** [comment]
> **Is your feature request related to a problem? Please describe.**
> When you add a token as background, and you want to resize it, you have to select part of it. This is annoying because you know exactly the size of the whole token, and you would like to use it.

If you know exactly the size of the token, why not create the map using the given grid size?

For example, I opened MT and created a new map with a grid size of 40px.  Then I selected the Background layer and dragged the **Default > Maps > Denoleran Enclave** image to the map.  Since that image has a grid size of exactly 40x40 px, the grid lines up perfectly (although I did have to use Shift-arrow keys to align it).

> **Describe the solution you'd like**
> I want either a new entry in the right mouse menu or a modifier which allows me to use the whole size of the token in the auto-resize option.

Using the token size will only work if the grid goes right up against the edge of the image.  Is that how your maps are drawn?  (The ones I have in my archive rarely look like that.)

> **Describe alternatives you've considered**
> I have tried to select the whole token, but it's very hard to get the border of it. Moreover, as the token represents a background map, it tends to be quite large, and with that the precision of your pointer is low.

It's not really necessary to get the whole image.  If you've got 10-15 cells in the horizontal direction and about the same vertically, you should end up with a scale that is very close.  After that, I usually align the upper left and follow the process outlined on the [wiki](https://wiki.rptools.info/index.php/Auto_Resize).  Have you tried that step-by-step approach?

**Comment by emmebi** [comment]
> 
> 
> > **Is your feature request related to a problem? Please describe.**
> > When you add a token as background, and you want to resize it, you have to select part of it. This is annoying because you know exactly the size of the whole token, and you would like to use it.
> 
> If you know exactly the size of the token, why not create the map using the given grid size?
> 
> For example, I opened MT and created a new map with a grid size of 40px. Then I selected the Background layer and dragged the **Default > Maps > Denoleran Enclave** image to the map. Since that image has a grid size of exactly 40x40 px, the grid lines up perfectly (although I did have to use Shift-arrow keys to align it).

I didn't think of this; just tried it and it works perfectly :) and this actually solves my use case :)

To clarify it better, here is my usual use case:

- I have a map whose division in cells is known in advance (so I know it is a 30x30 or 30x45 for example)
- I have bot the grid version and the non-grid version
- up to now I had to use the grid version and use the auto-resize/grid aligns to align the grid of the map with the grid of maptool

With your suggestion I can use now the gridless version and have a perfect division in cells; so hooray for you :D 

Feel free to close the ticket.
