### ISSUE TITLE
Clients can't adjust the grid color

### ISSUE THREAD

**Issue by Azhrei** [RPTools/maptool#271]
Is there a reason that clients can't adjust the grid color?  It would be convenient to be able to set the grid color to white or yellow or similar when the background image is dark-colored.

**Comment by JamzTheMan** [comment]
You can adjust the grid color now I thought? Or is that restricted to GM only right now?

Otherwise, yes, there should be no reason a client could not set their own grid color.

**Comment by Azhrei** [comment]
I couldn't select the **Adjust Grid...** menu option on a Player client as it's grayed out.  Obviously, we'll need to leave the grid size and any other settings grayed out for anyone except the GM...

**Comment by Jaggeroth** [comment]
Didn't we discuss this a while ago?

I thought the idea solution was that players _SHOULD_ be able to adjust the colour of the grid, but that it only affect them.

However for some reason that was problematic (due to how the UI was built?) so we greyed out the option.

At least, that's my recollection. Which gets increasingly unreliable ;)

**Comment by Azhrei** [comment]
I did have some déja vu about it, but didn’t recall an outcome.  I thought it might’ve been because it involved editing the Grid changing panel which is in Abeille and no one wanted to touch it!!

**Comment by JamzTheMan** [comment]
FYI I created a MapTool 2.0 project now. Feel free to start tagging other  issues that make sense to defer to that release.

Must UI stuff like this would have to be redone in FX so no reason to do it before then.

**Comment by Phergus** [comment]
Duplicates #167 .
