### ISSUE TITLE
MBL geometry is recalculated and checked too often when pathfinding, leading to an unfortunate user experience

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#2729]
**Describe the bug**
When a token is dragged with pathfinding enabled, every time the goal cell is changed the MBL/VBL AWT geometry is converted to JTS geometry. When there is lots of geometry, this can take a long time and leaves the user without any feedback that the drag is in progress. Also, when checking moves against MBL, the checks are cached but only when the token is near MBL, meaning expensive geometry checks are still done in the common case of moving through unobstructed cells. This leaves the user waiting longer than necessary for feedback about the path.

**To Reproduce**
1. Enable pathfinding
2. Import this map: [50x50 Cave 100px.dd2vtt.zip](https://github.com/RPTools/maptool/files/6640037/50x50.Cave.100px.dd2vtt.zip)
3. Place a token in the top-left of the map.
4. Try dragging the token to a neighboring cell.
    1. Without releasing the token, wait at that cell for a while (a second or more) and a path should be calculated.
    2. Without releasing the token, move a cell over and observe the same wait time.
5. Try dragging the token to a point across the map. Wait noticeably longer for a path to show up.

**Expected behavior**
When MBL/VBL does not change, the pathfinding algorithm should minimize the number of new geometry operations, since these are relatively expensive.

**Screenshots**
Dragging one cell takes about a second on my machine for any feedback to be presented to the user: 
![large-vbl-processing-time-cropped](https://user-images.githubusercontent.com/7492219/121727320-99de6880-caa0-11eb-9034-ec45a584346d.png)
And then continuing the drag one cell over also costs a second:
![large-vbl-processing-time2-cropped](https://user-images.githubusercontent.com/7492219/121727354-a6fb5780-caa0-11eb-979e-3a4926dac4e3.png)

A longer move like this takes about twice as long due to the great number of MBL intersection checks: ![large-vbl-long-move](https://user-images.githubusercontent.com/7492219/121726638-af06c780-ca9f-11eb-837f-4d92780e43e7.png)

**MapTool Info**
- Version: develop
- Install: New

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Version 20

**Additional context**

**Comment by FullBleed** [comment]
Just wanted to take a moment to show some appreciation for all the code optimizations and tweaks you've been doing lately , kwvanderlinde.  A lot of the time things like this go untouched because there is a sense that "it works good enough".  But these performance and accuracy improvements really add up and improve the user experience.

I also wanted to mention that, on occasion, when I see a dev with their fingers in an area like this I will chime in from the peanut gallery to see if other tweaks and/or improvements can be considered at the same time.  The assumption being that when the code in question currently is in focus it's the best time for consideration and/or a viability comment.

In this case, I wanted to inquire about "smooth path traveling".  In MT, when you drag a token along a path it, essentially, teleports from A to B.  Has JavaFX enabled some method that would allow for tokens to glide along the path?  I think that's a more pleasing/organic visual if it can be done.

**Comment by Phergus** [comment]
The map isn't rendered with JavaFX.

**Comment by Phergus** [comment]
Tested.  Significant improvement in response to moving token in complex VBL/MBL environments.  Test map was unusable on my system prior to this change.
