### ISSUE TITLE
Change logs directory (Linux)

### ISSUE THREAD

**Issue by MRAAGH** [RPTools/maptool#2786]
**Describe the bug**
Changing the Data Directory in the MapTool config does not change where the logs end up.

**To Reproduce**
1. Change Data Directory
2. Run MapTool
3. Note logs still go to `<userhome>/.maptool-rptools/logs`

**Expected behavior**
Logs should go to the MapTool Data Directory.

**Screenshots**

**MapTool Info**
- Version: Unknown

**Desktop (please complete the following information):**
OS: Arch Linux
I installed MapTool [from the AUR](https://aur.archlinux.org/packages/maptool-bin/)

**Additional context**
Changed to Bug from original Question issue.

> I was able to move almost everything from `~/.maptool-rptools` to a different directory by changing Data Directory in MapTool preferences. However, `~/.maptool-rptools/logs/` persists. Is this intentional? Is there a way to relocate the logs directory as well?

**Comment by Irarara** [comment]
That definitely shouldn't be the case, and I believe it used to work. 

This probably should have a proper bug report, but either way I've looked into it a bit and should have a fix.

**Comment by Phergus** [comment]
Doesn't logging start at the splash screen and before MT has read the preference setting for the data dir?

**Comment by Irarara** [comment]
It actually is loaded at that point (...though I went and made sure to test since I was worried for a second 😅). 

The issue is that the logger is being initialized before `appHome` is being set. If the property is set first using `appHome` for the log path works fine. So, setting `appHome` at the top of `AppUtil` (and calling `AppUtil` in `LaunchInstructions` like it used to be) fixes it.

Or at least, it does on my end (on Win10). `appHome` was changed to be set later with [this commit](https://github.com/RPTools/maptool/commit/6832705345216554ccbac1cd82ae99894f7d2063#diff-39df10fb1ad7f608bc329888c52240bdd6c3f9344bbf9901da54b7345c23572b), and I couldn't find anything to suggest there was a special reason for that change (was there?).

**Comment by Phergus** [comment]
The last time I looked at apphome/datadir stuff it was a convoluted mess.  There was  `appHome`  and also a `MAPTOOL_DATADIR` property set when the JVM is started and is passed `-DMAPTOOL_DATADIR=.maptool-rptools`.   I believe that `appHome` was supposed to be used to locate where the config file was at and *not* to find the logs directory.

Even though there is a datadir field on the Preferences dialog it isn't save dwith the other preferences it is managed through the UserJvmOptions class.

IIRC the last changes were to fix a problem where the logs were being written in whatever directory MT was launched from.

**Comment by Irarara** [comment]
I can't speak for how things were ever supposed to be, but I'll break down what I observed while looking into this:
* The `appHome` system property is set to the full path of the `logs` dir in the data dir (its value is the result of  `getAppHome("logs").getAbsolutePath()`). The only place this property seems to be used right now is to [log its value at launch](https://github.com/RPTools/maptool/blob/c73bf5bcf1261b8656add5d540d216b6cf9455bd/src/main/java/net/rptools/maptool/client/MapTool.java#L1532) and in some [i18n strings](https://github.com/RPTools/maptool/blob/c73bf5bcf1261b8656add5d540d216b6cf9455bd/src/main/resources/net/rptools/maptool/language/i18n.properties#L576) (which doesn't actually work anyway, since values can't be inserted that way).
* `MAPTOOL_DATADIR` is used to set the path to the data dir and can be an absolute or relative path (relative to the user's home dir). Because it can be absolute or relative the full path is worked out in code (`AppUtil.getDataDir()`, which is used by `AppUtil.getAppHome()`). 
* Because the full path is worked out in code, just using `MAPTOOL_DATADIR` is insufficient. For instance, the current paths used in [log4j2.xml](https://github.com/RPTools/maptool/blob/c73bf5bcf1261b8656add5d540d216b6cf9455bd/src/main/resources/log4j2.xml),  `${sys:user.home}/.maptool-rptools/logs/...`, could be changed to `${sys:user.home}/${sys:MAPTOOL_DATADIR}/logs/...`, but that would only work when `MAPTOOL_DATADIR` is a relative path.
* As far as I can tell, the reason using the `appHome` property to provide the log dir stopped working is because log4j started being initialized before the property was set (because things got [moved around](https://github.com/RPTools/maptool/commit/6832705345216554ccbac1cd82ae99894f7d2063#diff-39df10fb1ad7f608bc329888c52240bdd6c3f9344bbf9901da54b7345c23572b) in `AppUtil`). This then resulted in a relative path of `${sys:appHome}/...` being used, because it falls back on using that string when it can't fetch the property and leading to last year's issue. 

Part of what makes this weird is that the `appHome` property really doesn't sound like it should refer to the log dir, but that's how it has been since at least 2019. It seems like it should point to the root data dir or be renamed something clearer.

No idea about the preferences thing.

**Comment by Phergus** [comment]
My thought is that:

-  `appHome` should be the actual application home aka the installation directory and so it's only real use should be to find the `MapTool.cfg` file in the hopes that someday soon we'll be able to change those settings within MT again.
- `MAPTOOL_DATADIR` should be where all of the content that is by default found under `${sys:user.home}/.maptool-rptools/`  including the `logs` directory.
- The `logs4j2.xml` file should reference a different system property like `MAPTOOL_LOGSDIR` which MT constructs as a fully-qualified path from the passed in `MAPTOOL_DATADIR` and is set prior to initializing logging.

**Comment by Irarara** [comment]
Regarding `appHome`, is there a real need to store the install dir as a property? It's needed for the log path so the logger config can use it, but will something like that be the case with the config too? If not it doesn't seem like there's much point to it. There does exist a method for fetching the install directory already (`AppUtil.getAppInstallLocation()`).

**Comment by Phergus** [comment]
I don't think we need to store the install location.  As you say, it can be retrieved when needed via the `getAppInstallLocation()` method which isn't very often.

Just reading over the AppUtil class, I think you can ignore what I said above about `appHome`.  Lower in the class there are actual JavaDocs that explain how things should be working.

The one hiccup is that it appears to be currently setup to look for the config file in the datadir under `config` but that way of doing it went away with Java 14 and MT 1.8.  So the `CONFIG_SUB_DIR` property and `getDataDirAppCfgFile()` are no longer appropriate until we can overwrite the config file while MT is running.

**Comment by Phergus** [comment]
Tested under Windows.  Changing data directory in MapTool.cfg changes where the logs go.

@Irarara you're on Linux?

**Comment by Irarara** [comment]
@Phergus Just Windows here, I'm afraid. Be happy to test otherwise. This _should_ be the same on all platforms though.

**Comment by Phergus** [comment]
Okay.  Maybe somebody under Linux will wander by and test it.  :)

**Comment by Azhrei** [comment]
I can test my Ubuntu VM and macOS, but it'll be late tonight.

**Comment by Phergus** [comment]
@Azhrei roger that.

**Comment by Azhrei** [comment]
Okay, I used `./gradlew jpackage` to build the macOS PKG file.  Part of that is to create `maptool/build/jpackage` under which the macOS app is created.  I ran that app after editing MapTool-Dev-Release.app/Contents/app/MapTool-Dev-Release.cfg` and it had the proper effect (created the new directory and populated it).

So success on macOS.  (I don't have a Java environment installed in my Ubuntu VM, so that'll take a little longer.)
