### ISSUE TITLE
Slow opening 1.9.3 - sometimes

### ISSUE THREAD

**Issue by taustinoc** [RPTools/maptool#2887]
**Describe the bug**
Maptool 1.9.3 is very slow to open on some computers.

**To Reproduce**
1. Reboot computer, and allow enough time for it to completely finish starting up.
2. Open Maptool
3. Wait up to 10 minutes for program to appear.

**Expected behavior**
Open in less than 10 minutes.

**MapTool Info**
- Version: 1.9.3
- Install: New (both computers)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 7 & 10

**Additional context**
On windows 7, with a Pentium G630 dual core processor with 8 GB of RAM and a normal hard drive, it took 7 1/2 minutes for the program to open, and another minute before it would respond to the mouse. This is on the first use after a reboot (but with enough time waiting for Windows to fully start up and settle down). After the first time, it usually starts up quickly unless some time has passed with other programs in use.

On Windows 10, with a quad core Xeon processor with 64 GB of RAM and an SSD drive, it too 40 seconds.

Clearing the cache makes little difference, and, of course, it's opening to an empty campaign.

On the Win 7 computer, there appears to be a great deal of disk activity the entire time.

<details>

<summary>

**Debug info on Win 7 computer:**

==== MapTool Information ====
MapTool Version: 1.9.3
MapTool Home...: C:\Users\terry\.maptool-rptools
MapTool Install: C:\Users\terry\AppData\Local\MapTool 1.9.3\app
Max mem avail..: 1 GB
Max mem used...: 227 MB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\terry\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

</summary>

==== Java Information ====
Java Home......: C:\Users\terry\AppData\Local\MapTool 1.9.3\runtime
Java Vendor....: AdoptOpenJDK
Java Version...: 16
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\terry\AppData\Local\MapTool 1.9.3\MapTool.exe

==== OS Information ====
OS Name........: Windows 7
OS Version.....: 6.1
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
PATH...........: C:\Users\terry\AppData\Local\MapTool 1.9.3;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\ImageMagick-7.0.8-Q16;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.6-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common Files\Roxio Shared\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\DLLShared\;C:\Program Files (x86)\Common Files\Roxio Shared\OEM\12.0\DLLShared\;C:\Program Files (x86)\Roxio\OEM\AudioCore\;C:\Program Files (x86)\Calibre2\;C:\Program Files\Java\jdk1.7.0_03\bin;C:\Program Files (x86)\Intel\Services\IPT\;C:\Program Files\Calibre2\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\OpenVPN\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\dotnet\;;.
Number of Procs: 2

==== User Information ====
User Name: terry
User Home: C:\Users\terry
User Dir.: C:\Users\terry\AppData\Local\MapTool 1.9.3

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Realtek PCIe GBE Family Controller
Interface Name: eth3
Address...: 192.168.50.240
Address...: fe80:0:0:0:44d7:48a4:b4cb:8a34%eth3

Display Name..: VirtualBox Host-Only Ethernet Adapter
Interface Name: eth5
Address...: 192.168.56.1
Address...: fe80:0:0:0:7897:3327:5079:3743%eth5

Host Address...: 192.168.50.240
Default Gateway: 192.168.50.2

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1920x1080(32)

==== Internet Gateway Devices ====
	Error scanning for IGDs.
	No IGDs Found!

**Debug info on Win 10 computer:**

==== MapTool Information ====
MapTool Version: 1.9.3
MapTool Home...: C:\Users\taustin\.maptool-rptools
MapTool Install: C:\Users\taustin\AppData\Local\MapTool 1.9.3\app
Max mem avail..: 15 GB
Max mem used...: 232 MB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\taustin\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: C:\Users\taustin\AppData\Local\MapTool 1.9.3\runtime
Java Vendor....: AdoptOpenJDK
Java Version...: 16
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\taustin\AppData\Local\MapTool 1.9.3\MapTool.exe

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
PATH...........: C:\Users\taustin\AppData\Local\MapTool 1.9.3;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Google\Google Apps Sync\;C:\Program Files (x86)\Google\Google Apps Migration\;C:\Users\taustin\AppData\Local\Microsoft\WindowsApps;;.
Number of Procs: 4

==== User Information ====
User Name: taustin
User Home: C:\Users\taustin
User Dir.: C:\Users\taustin\AppData\Local\MapTool 1.9.3

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: Intel(R) Ethernet Connection I217-LM
Interface Name: eth2
Address...: 192.168.1.114
Address...: fe80:0:0:0:2d8e:1d0c:18f0:72d5%eth2

Host Address...: 192.168.1.114
Default Gateway: 192.168.1.10

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 2
Display 1: 1920x1080(32)
Display 2: 1920x1080(32)

==== Internet Gateway Devices ====
	No IGDs Found!

</details>

[Win 7 maptool.log](https://github.com/RPTools/maptool/files/6985752/Win.7.maptool.log)
[Win 10 maptool.log](https://github.com/RPTools/maptool/files/6985753/Win.10.maptool.log)

**Comment by taustinoc** [comment]
As an additional datum, on a third computer, Windows 10, dual core Xeon processor and SSD drive, but with only 8 GB of RAM, it look less than 40 seconds to open (after a fresh boot).

It does not appear to be memory related.

**Comment by Phergus** [comment]
Here is 3:40 of the start time.

```
2021-08-13 18:44:49.085 DEBUG net.rptools.maptool.client.swing.AssetCacheStatusBar - AssetCacheStatusBar updated...
2021-08-13 18:48:29.768 DEBUG net.rptools.maptool.client.swing.ImageCacheStatusBar - ImageCacheStatusBar updated...
```

How much is in your `.maptool-rptools\imageThumbs` folder?

**Comment by taustinoc** [comment]
About 15,000 items, at a little over 200 MB. I do have a lot of stuff in
the resource library on that computer.

**Comment by Phergus** [comment]
So you know how to shave off nearly 4 minutes then. :)

**Comment by Azhrei** [comment]
Hm, the Internet ate my homework. :(

First, thanks for the log files.  Those are really helpful!

I agree with Phergus, those two are an indicator; clear the asset cache and the thumbnail cache.  Some of the tools from [SysInternals](https://docs.microsoft.com/en-us/sysinternals/) might be useful in monitoring disk IO, particularly Process Monitor and SysMon, for monitoring how much disk IO is caused by MapTool itself.  On the faster Win10 system, the logging shows only 23 seconds for both.

That Win7 machine is also reporting only 1GB of RAM available for MT.  You could try upping that to 2GB and then 4GB and see if either of those help.  Upping the amount of memory may allow Java to cache more of the responses from the OS to file queries, but it also means less memory for the OS to do its own caching.  I'm only partially familiar with memory mgmt on Win7, so I don't know how far you can go on a system with 8GB, and it's not clear how well NTFS caches file attributes when a directory contains thousands of entries.

[This page](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc781134(v=ws.10)) goes into detail and says that reading the attributes of a file (such as its size) requires reading a 1k record, so an asset cache with 3000 files requires reading 3MB.  The real issues with this is that MT is reading them by name (requiring a directory lookup) and NTFS will set the Last Access Time on the file as well, meaning those 1k records need to be written back to the disk.  All of this generates a lot of IO.  And running three threads simultaneously, all hitting the same partition, just makes it worse.

Longer term...

These threads need to be toned down a lot.  I'm not sure how to do that.  Ideally, Java could drop the IO priority of those threads, but I don't see an obvious way to do that.  (Maybe it's enough to do `setPriority(Thread.MIN_PRIORITY);` but that seems to be cpu priority and not IO priority.)

The MT code currently triggers an update request any time a file is added/removed from a cache directory, then those updates are throttled to once per 60s.  The problem is that every 60s it will reevaluate the contents of the directory; it _could_ just keep track of which file(s) were added/removed and update an existing total instead.  Huge win.

It _might_ help if the asset cache and thumbnail cache used subdirectories.  For example, an asset named `7c0e6ba238f40d7465f775a2b68bfeba` would be stored as `7c/7c0e6ba238f40d7465f775a2b68bfeba` so that there are not hundreds or thousands of assets in the same directory (my asset cache has 3000+ files and most filesystems don't do well with that many).  There is a delay shown later in the log file, after the status bar threads are done, where a lookup of a single asset file takes ~0.3 seconds (that's a long time!).

It would also be helpful if the logging included the start time of those threads in addition to the end time (right now, the timings are not really clear since no start time is mentioned).

**Comment by taustinoc** [comment]
That certainly helps, though it's still a bit slower. Getting rid of the
PDFs in the Resource Library seems to have done the most good. It's down to
less than 3 minutes now, even after being off doing other things for a
while.

Mind you, it didn't actually bother me that much to begin with, because
once it was up and running, everything was OK. But it does bother other
people, and I could definitely reproduce the problem easily, so glad to
help out. (And get some benefit along the way, even.)

**Comment by taustinoc** [comment]
The biggest issue seems to have been a dozen or so PDFs in the Resource
Library. Once I removed those, it dropped to less than 3 minutes even with
15,000 files still in the thumbnail folder. After clearing that folder out,
it dropped to just under 30 seconds.

Mind you, the slow start up time didn't really bother me much to begin
with. Gave me time to make a cup of tea, and once it was up and running,
everything was fine. But if it helps other people, it's worth a little
troubleshooting, and I won't complain about the faster startup times.

I'll leave the details to those of you who are programmers. I'm just the IT
guy for a retail chain, and programming is not in my skillset.

**Comment by Phergus** [comment]
FWIW, I probably have hundreds if not more than a thousand PDFs in one of my Resource Library folders though they are also down 2+ folder levels deep and rarely if ever accessed with MT.  I have a top-level folder in my Library that is just for extracting info out of PDFs.  I copy the PDF into the folder and then access it in MT.  (Though I am way more likely to use TokenTool for this.)

I'm not convinced that the thumbnails cache is actually beneficial.  We need to put in some metrics to track cache hits/misses and see if we are even getting more than single-digit percentage hits.

**Comment by taustinoc** [comment]
I think the biggest issue was that the PDFs were in a top level folder, so
it was scanning them every time I opened MT. I'll leave the esoterica of
the guts of the program to y'all who understand it, and just have fun
running games.

**Comment by aliasmask** [comment]
I'm having similar issues (Discord: https://discord.com/channels/296230822262865920/296230822262865920/876649371884716052)

Here's what my logs say:
```
2021-08-15 19:59:31.431 DEBUG net.rptools.maptool.client.swing.AssetCacheStatusBar - AssetCacheStatusBar updated...
2021-08-15 20:02:27.598 DEBUG net.rptools.maptool.client.swing.ImageCacheStatusBar - ImageCacheStatusBar updated...
2021-08-15 20:02:28.147 DEBUG net.rptools.maptool.client.swing.AppHomeDiskSpaceStatusBar - AppHomeDiskSpaceStatusBar updated...
2021-08-15 20:05:51.977 INFO  net.rptools.maptool.client.ui.MapToolFrame - Removing the F10 key from the menuBar's InputMap; it did  exist
```

So, the AssetCacheStatusBar and the AppHomeDiskSpaceStatusBar take around 3 minutes each, sometimes. I'm guessing the difference is it gets cached somewhere and restarting computer clears that cache.

[1.9.3 quick.log](https://github.com/RPTools/maptool/files/6989560/1.9.3.quick.log)
[1.9.3 slow.log](https://github.com/RPTools/maptool/files/6989561/1.9.3.slow.log)

**Comment by aliasmask** [comment]
After clearing my cache and thumbs it takes like 15 seconds instead of 7 minutes to open. I had about 2GB cache and 571MB thumbs.

**Comment by Phergus** [comment]
>  The real issues with this is that MT is reading them by name (requiring a directory lookup) and NTFS will set the Last Access Time on the file as well, meaning those 1k records need to be written back to the disk.

What I see when opening MT is that just those `assetcache` items that are initially needed by the GUI  - quick map textures, whatever tokens might be visible in the library and so forth - are actually accessed and thus have their records updated.  For  me it was 22 assets out of 2308.

`campaignthumbs` was different with 253 thumbnails last access times updated out of 451.

`imageThumbs`  only one of the 40 thumbnails had the last access time updated.

Filesize should have nothing to do with it unless MT is actually verifying checksums or otherwise reading the image.  The images are read if populating the library preview or building the Quick Map previews.

**Comment by Azhrei** [comment]
> > The real issues with this is that MT is reading them by name (requiring a directory lookup) and NTFS will set the Last Access Time on the file as well, meaning those 1k records need to be written back to the disk.
> 
> What I see when opening MT is that just those `assetcache` items that are initially needed by the GUI - quick map textures, whatever tokens might be visible in the library and so forth - are actually accessed and thus have their records updated. For me it was 22 assets out of 2308.

How do you "see" that?  Are you running the monitoring tools from the SysInternals page?  Or looking at a column from the Windows file manager?

If you look at the code in MT, it uses `File.listFiles()` (or whatever the method is) that generates a list of all names in the directory.  For my system, that'll be 3000+ names.  Then each name is visited and its file size is queried.  (This access to the metadata is what should be triggering the last accessed time to be updated.  However, the page I linked to above _is_ pretty old, circa 2009, so maybe NTFS has a different scheme now.)

> Filesize should have nothing to do with it [...]

Correct.  Those two threads in MT don't read the content of the file, they just grab the size field from the metadata.

**Comment by Phergus** [comment]
I'm looking at the last accessed timestamp in file explorer as that reflects whats been written to disk versus what the filesystem has in memory.  Simply getting a list of files in the directory doesn't access the files themselves.  Getting the file sizes also does not trigger an update to the files metadata at that time.

> The Last Access Time on disk is not always current because NTFS looks for a one-hour interval before forcing the Last Access Time updates to disk. _NTFS also delays writing the Last Access Time to disk when users or programs perform read-only operations on a file or folder, such as listing the folder’s contents or reading (but not changing) a file in the folder._ If the Last Access Time is kept current on disk for read operations, all read operations become write operations, which impacts NTFS performance.

It's easy enough to check by just starting MT, note which files had their last accessed time updated.  Wait an hour or two and refresh the folder.   Many hours later, with MT still running, 2000 of the 2800 files are still timestamped from one or more days ago.

What could negatively impact startup time when calculating the disk usage for the various cache directories is a anti-virus program that is also getting involved in every access.  So testing on a system with a large asset cache both with and without the anti-virus running may provided a data point.

**Comment by kwvanderlinde** [comment]
I've reproduced this on a large asset cache (9.3 GB, >100,000 files) and found Apache Common's `FileAlterationMonitor` to be the culprit. The `start()` method is taking over 5 minutes to complete, holding up the main thread the entire time (and it will do so for both `assetcache` and `imageThumbs`). Part of how the monitor works is that it lists all the files in the directory in order to keep track of changes. But it also immediately checks each file for existence, which is a surprisingly costly operation.

An alternative we can use is Java's [`WatchService`](https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/nio/file/WatchService.html), which uses built-in filesystem functionality to watch directories rather than doing so itself. After a quick test, it does not seem to have any performance issues with watching large directories.

Beyond that, the `AssetCacheStatusBar` and `ImageCacheStatusBar` bars also enumerate all files on the main thread via `FileUtils.sizeOfDirectory()`. The cost of this is much less, only about 15 seconds for my assetcache, but that is still long enough to be noticable. I'm not sure if there is a better alternative, aside from just moving that work off-thread somewhere.

**Comment by Azhrei** [comment]
> I've reproduced this on a large asset cache (9.3 GB, >100,000 files) and found Apache Common's `FileAlterationMonitor` to be the culprit.

Thanks for doing this.  It's good to have data. 😉

What is the start() method doing that takes 5 minutes??  It doesn't doesn't that long on macOS...

In terms of alternatives, I don't know of a way to obtain a directory's size other than that method.  A better question might be whether the amount of disk space allocated by the assetcache is meaningful for the user.  If not, perhaps the number of files is enough?

**Comment by kwvanderlinde** [comment]
> What is the start() method doing that takes 5 minutes?? It doesn't doesn't that long on macOS...

Not sure why this is platform specific tbh. Apparently it's a known problem that `Files.exists()` and similar can be quite slow in some cases. All the information I see is about Java 8, though, and definitely includes non-NTFS system. E.g., JGit has a [bug report](https://git.eclipse.org/r/c/jgit/jgit/+/54757/) that specifically involves moving away for `Files.exists()` on POSIX file systems. But considering I was seeing `Files.exists()` being the issue here, my guess is that the POSIX NIO implementations have since been fixed, but the NTFS NIO implementation still has that issue, or at least a similar one.

> In terms of alternatives, I don't know of a way to obtain a directory's size other than that method. A better question might be whether the amount of disk space allocated by the assetcache is meaningful for the user. If not, perhaps the number of files is enough?

It's entirely possible that `FileUtils` is not doing things in a reasonable way. or else NTFS is just out to get us. When I'm back in front of a windows machine, I'll compare to some simple alternatives like using `Files.walkFileTree()`.

**Comment by kwvanderlinde** [comment]
Results are in:
1. `FileUtils.sizeOfDirectory()`: 15.x seconds
2. `Files.walkFileTree()` aggregating `Files.size(...)`: 5.x seconds.
3. `Files.walkFileTree()` aggregating `BasicFileAttributes::size()`: <0.5 seconds

**Comment by Phergus** [comment]
Testing with 200K files in the cache (mostly .lnk files) and 500MB in total size took more than 5 minutes to load 1.9.3 but showed no delay with fix.
