### ISSUE TITLE
[1.10 JavaScript] Token.getProperty does not return default value and does not process calculated properties.

### ISSUE THREAD

**Issue by Darinth** [RPTools/maptool#3028]
**Describe the bug**
Token.getProperty does not return default value and does not process calculated properties.

**To Reproduce**
1. Create a set of default campaign properties where strength is 10 and strmod is `{Floor((Strength-10)/2)}`
2. Create the following javascript code in a macro:
```
        MapTool.chat.broadcast(MapTool.tokens.getSelected().getProperty("Strength"));
        MapTool.chat.broadcast(MapTool.tokens.getSelected().getProperty("StrMod"));
```
3. Create a token, select it, and run the above javascript with `js.evalNS`
4. `null` will appear in chat twice, because it doesn't use the default value.
5. Confirm this by changing strength to 12 and strmod to `{Strength+2}` on the token and re-running the javascript code on the token.
6. You will then get `12` and `{Strength+2}` in the chat window.
7. This is closer, but still not correct

**Expected behavior**
If you create a macro with
```
[r:getProperty("strength")]
[r:getProperty("strmod")]
```
and run it on a fresh token, you get `10` and `0` which would be the expected output of the same javascript code above.

**MapTool Info**
- Version: 1.10.0 javascript
- Install: Upgrade

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by aeauseth** [comment]
I ran across this issue as well.  The temporary/clunky work around is to pass calculated props into js.eval.  I also considered getting the base prop and re-doing the calculation in JS, which isn't fantastic either, but should work.

**Comment by fishface60** [comment]
This is especially awkward because if you set a property to the same value as its default then maptool will delete the property from the token and it'll start returning `"null"` again.

If it returned an actual `null` then the convenient null-handling operators could be used rather than checking against `== "null"`, but the fallback you'd have to do would either be to keep your macros in-sync with the campaign properties, or eval getInfo to do the fallback logic yourself.
