### ISSUE TITLE
Add 'Implicit Lights'

### ISSUE THREAD

**Issue by wolph42** [RPTools/maptool#3087]
**Is your feature request related to a problem? Please describe.**
The problem is that EVERY light source needs to be defined in the campaign properties. This has the following issues:
- hard to transfer to another campaign
- always visible to players (e.g. the source 'glowing dragon eyes' might be something you  don't want to show
- light sources are not 'self contained' (like tokens)

**Describe the solution you'd like**
Add the option to the token editor to set an 'implicit lightsource'. That is a text field where you can enter e.g.:
Dragon Eyes : cone arc=70 30.5 122.5#000000
this makes it easy to create specific lights AND to export import specific lights AND export import maps without worrying about the light settings in the campaign properties.

**Describe alternatives you've considered**
none

**Additional context**
suggested spot for the lightbox: 

<img width="460" alt="light" src="https://user-images.githubusercontent.com/19568714/138168397-7b7f1e6d-aa79-49c6-b0e5-9e0e0be830c8.png">

**Comment by Phergus** [comment]
See #331.

**Comment by melek** [comment]
Would this make it possible for lights imported via the the Universal VTT format to work out of the box, at least in a limited way?

**Comment by FullBleed** [comment]
Totally for this.

**Comment by BlackwingNL** [comment]
All 3 goals listed by @Phergus will need the Light itself to be implemented first. To achieve that the current Light needs to be adapted with (as far as I can see):

1. The type distinction between a regular light and this new type light
2. A location where to store these lights.

As for 2: As I understand it, tokens don't actually contain a light object, but only a reference (GUID) to a light object in the central list of light sources. These light objects only exist in a campaign, not in an exported map or a saved token (!). This significantly limits the portability of lights through maps of tokens but that's a different issue.
So for these implicit lights a light object has to be created and stored somewhere so it can be referred to by the token in the same way and current functions that interact with lights need to be able to find these implicit lights as well.

One option would be to still store them in the campaign with the other lights, just hide them in relevant places (in de campaign properties dialog, and the light menu when the token does not contain that specific light). Outside of the UI this would mean the rest would be pretty much transparent for the light functions.

A second option is to store them on the token that also has the reference to it. This would mean a bit more work for the light functions but makes these lights more modular and able to be saved with a map or token.

**Comment by Phergus** [comment]
Tokens actually have a list of AttachedLightSource objects and each of those have a GUID reference to a campaign-defined LightSource object that contains a list of Lights that make up the LightSource.

So there is a pretty good starting point to having self-defined lights as part of a token.

**Comment by kwvanderlinde** [comment]
I've been working on this concept through the sister issue #331. I won't be dealing with the UI for now (aside from basic right-click support), instead focusing just on macro function support.

This is the approach that seemed most natural after playing around with it for bit:
1. Allow defining any number of light sources on tokens in addition to the campaign.
2. Allow toggling token lights sources by name, just like for campaign light sources. I.e., via the right-click menu or `setLight()` function.
3. When a token light source is toggled off, its definition sticks around on the token rather than being dropped.

And for this FR, I would add a point (4): editing token light sources should be similar to editing campaign light sources. I.e., via our lighting DSL right now, and via some improved UI when we get #4088.

End result is that these token-specific light sources would be identical to campaign lights except for where they are defined and some other minutiae. I believe this will accomplish any stated goals (UVTT support, keeping lights secret, enabling specialized lights, etc).

Any feedback, especially on what we should call these lights, would be appreciated.

**Comment by bubblobill** [comment]
Having just read this, it jumps straight to an overcomplicated implementation of something people have been asking for for a long time.
Whilst it may be nice to have transient light sources, surely we should first have put in place;
- createLight,
- removeLight, and
- updateLight, 

that update the campaign.

**Comment by cwisniew** [comment]
> Having just read this, it jumps straight to an overcomplicated implementation of something people have been asking for for a long time. Whilst it may be nice to have transient light sources, surely we should first have put in place;
> 
> * createLight,
> * removeLight, and
> * updateLight,
> 
> that update the campaign.

I know we haven't been doing it this way in the past but I have been trying with my additions to follow it, my preference going forward is to do it via the UI first, macros can follow.
UI makes it available to more people and you can change it based on feedback, macros functions are hard to change without breaking people's macros so should probably wait until the feature is ready and has feedback.

**Comment by kwvanderlinde** [comment]
I will at least add a UI for this so it isn't only macros. Will keep this in mind going forward.
