### ISSUE TITLE
[Feature]: Auras - Shape, Hole-in-the-middle

### ISSUE THREAD

**Issue by bubblobill** [RPTools/maptool#3302]
### Feature Request

Pretty sure I had this on GIT before. If you can find the original please link it.

I use auras to illustrate things like reach, fields of fire, targeting, and many other things.
Some of them become quite complex with multiple arcs of different sizes and offsets.

Since I can only have auras emanating from the token they necessarily overlap and start getting ugly fast.

Read forum post for pretty pictures and more detail.
https://forums.rptools.net/viewtopic.php?f=26&t=22854

### The Solution you'd like

I want to be able to specify a distance at which the aura starts as well as when it ends.

**Comment by bubblobill** [comment]
Nb: This can also be strong-armed into providing an "edge" or border. Ref: #1108

**Comment by Ghost49X** [comment]
I'd also love this feature. I already use the Lighting system in Maptool for normal lighting so I'd like to use auras for this.

**Comment by kwvanderlinde** [comment]
This can be achieved since 1.13.0, e.g.,:
```
Donut: aura circle 10 30#793500
```
![image](https://github.com/RPTools/maptool/assets/7492219/51013e9d-5979-4292-9976-3e027f3de8af)


And for those that look at the top of the forum post, but don't scroll down to the bottom of: we've long had an offset parameter for cones that for changing the angle relative to facing:
```
Slice: aura scale cone arc=90 offset=90 5 15#793500
```
![image](https://github.com/RPTools/maptool/assets/7492219/ce39d28d-872c-4475-a81e-6bc8eea2eb5c)

**Comment by bubblobill** [comment]
Stale and completed
