### ISSUE TITLE
[Bug 1.11.5]: player.getConnectedPlayers() is empty when server starts

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#3356]
### Describe the Bug

When I open MT then run that function it returns data, but when I start a server (see image) then the function doesn't return any data.

![image](https://user-images.githubusercontent.com/43827071/151715556-ee0a205c-3dae-4992-b5b1-7a53d739963b.png)

### To Reproduce

Start a server with the above settings.
Run macro in chat to view empty array.

### Expected Behaviour

I expect it to show all the connection info.

### MapTool Info

1.11.5

### Desktop

Window 10

### Additional Context

I used this macro to test.
```
[R: playersThisSession = player.getConnectedPlayers()]<br>
[R: connectedPlayers = json.path.read( playersThisSession,"[*][?(@.role == 'GM' && @.connected == true)].name","ALWAYS_RETURN_LIST,SUPPRESS_EXCEPTIONS")]
```

**Comment by kwvanderlinde** [comment]
There's certainly some inconsistencies here.

The fact that `player.getConnectedPlayers()` returns an empty array seems to be expected behaviour. Per the wiki docs, the `player.*` macro functions relate only to the player database, which to my understanding is only in play if you check the **Use MapTool Password file.** option when starting the server. By not having that option checked, there will be no player database info available.

The weird thing in my view is that `player.getConnectedPlayers()` returns the anonymous user for a personal server, even though the player database isn't in use (e.g., no other players in the database are returned for `player.getPlayers()`). I would expect that `player.getConnectedPlayers()` on a personal server would return an empty array.

In a similar vein, if a server is started with **Use MapTool Password file.** checked, then `player.getConnectedPlayers()` will return info for the local DM. I'm not sure why this would be, as the local DM isn't ncessarily part of the player database. I would expect `player.getConnectedPlayers()` to only return info about players other than the local DM (same for `player.getPlayers()`).

I'm actually not very educated about the player database, but in my opinion if the point of the `player.*` macro functions is to expose the player database, it should only do that and not more (that means no local DM info, for example). Otherwise, it ought to be generalized to show any connected player info, making it useful even without the player database. It's just ripe for confusion otherwise. 

---

As a workaround, in case you really only care about connected players and don't care to use the player database: you can use [`getAllPlayerNames()`](https://wiki.rptools.info/index.php/getAllPlayerNames), and can combine that with `isGM()` to get the "role" of each player. This would give you all the info that `player.getConnectedPlayers()` would give if you were using the player database ("connected" should always be true).

**Comment by aliasmask** [comment]
Thanks. I kind of suspected something like that, but having data with no server running, then no data with a server was a bit confusing.

Yep, I'm aware of how I would normally get the connected players info. I was just following up on another person's question.
https://discord.com/channels/296230822262865920/937409542352961586/937409543896465438

**Comment by Phergus** [comment]
Tested.
1. With personal server, returns the Default Username as connected GM.
2. With server and no database, returns the player name that started the server and any connected players.
3. With server and database, returns the player name that started the server and any connected players.

There is a different issue where disconnecting the server with logged in players leaves them flagged as logged in in the player database.  Will go under separate issue.
