### ISSUE TITLE
[Bug]: json.path's filter expressions cannot compare arrays

### ISSUE THREAD

**Issue by Pmofmalasia** [RPTools/maptool#3358]
### Describe the Bug

According to the [documentation for the json.path functions](https://github.com/json-path/JsonPath/blob/master/README.md#filter-operators), the filter operators for the path are supposed to be able to compare arrays - see the `in`, `nin`, `subsetof`, `anyof`, etc. operators linked. However, rather than correctly filter based on the operators, it only returns an empty array. This is not exclusive to the operators meant for arrays - using `==` to compare one array to another similarly returns a blank array.

It appears that the issue is comparing an array within the json that you are filtering to anything else. For example, see the following code:

```
[H: data = json.append("",
   json.set("{}","key",1,"array",json.append("",2,3)),
   json.set("{}","key",2,"array",json.append("",1,2,3))
)]

[R: json.path.read(data,"[*][?(@.key in [2,3])]")]
[R: json.path.read(data,"[*][?(@.key == 1)]")]
[R: json.path.read(data,"[*][?(@.array == [2,3])]")]
[R: json.path.read(data,"[*][?(@.array anyof [2,3])]")]
```

The first two `json.path.read()` functions work correctly, despite the first using the `[2,3]` array as a comparison. The latter two fail, seemingly because `@.array` is an array. I have considered a potential workaround by using the following to end on an integer instead of an array, but this fails as well:

```[R: json.path.read(data,"[*][?(@.array.* in [2,3])]")]```

I currently do not see a way to get arrays to work correctly within json.path, requiring the use of lists or objects instead.

### To Reproduce

See above

### Expected Behaviour

Proper comparisons of arrays in the path.

### MapTool Info

1.12.2

### Desktop

Windows 10

**Comment by Pmofmalasia** [comment]
Update with corrected info:

It appears that the issue is not entirely with comparing arrays, rather it is with comparing an array within the path to anything. For example, when continuing to use the above code adding `[R: json.path.read(data,"[*][?(@.key in [1,3])]")]` will correctly output `[{"key":1,"array":[2,3]}]`.

**Comment by kwvanderlinde** [comment]
Turns out the JSONPath library is pretty busted with its default providers. Main issue is that it tries to use json-smart to parse the `@.array` values into `java.util.List` objects, but doesn't provide it a way to create instances. So json-smart blows up trying to instantiate the `java.util.List` interface. Interested readers can look at `JsonSmartMappingProvider`  to see what I mean :grimacing: Thankfully we can avoid that by instead switching to a GSON-backed or other mapping provider.

Unfortunately, even if we switch mapping and JSON providers, JSONPath hardcodes the use of json-smart to parse literals in the path :disappointed:. _At least in this case it doesn't try to instantiate `java.util.List`, but it does mean there are discrepancies between parsing user-provided values via GSON and parsing literals vs json-smart. E.g., the GSON provider parses `[1, 2]` as a list of doubles (`[1.0, 2.0]`) while json-smart parses it as a list of ints (`[1, 2]`), and these won't ever compare equal despite being equivalent JSON. This can be worked around by explicitly using decimal points in the literals.

***

Assuming we switch to a GSON mapping provider, this will work to compare array equality:
```
[R: json.path.read(data, "[*][?(@.array == [2.0, 3.0])]")]
```

By shear magic, the other expressions work without needing the decimal points:
```
[R: json.path.read(data, "[*][?(@.array anyof [2,3])]")]
[R: json.path.read(data, "[*][?(@.array size 3)]")]
```

Other mapping providers might be better, I just quickly tried it out the GSON one.

**Comment by aliasmask** [comment]
Having the number conversion would be annoying, but I imagine string comparisons should work fine. I'm glad someone is looking at this. json.path functions are a huge help when trying to do the more advanced stuff and searches. It would just be nice if we can lockdown what works and what doesn't work and go from there. There's always the alternate slow ways of doing things.

**Comment by Pmofmalasia** [comment]
Agreed, this would still be a vast improvement over what we have now. Of course it would be nice if there was another provider that was able to remove this quirk as well, but I think even this should cover everything I do.

Really appreciate you looking into this!

**Comment by aliasmask** [comment]
Sounds like the GSON provider is much better. I would like to be able to use filters currently not working with the current provider. I don't think the comparing ints to reals is a problem.

**Comment by kwvanderlinde** [comment]
For reference, here are a few json-path issues that may be worth following in case they decide to address the hardcoded use of json -smart representation for predicates:
- [608](https://github.com/json-path/JsonPath/issues/608)
- [513](https://github.com/json-path/JsonPath/issues/513)
- [274](https://github.com/json-path/JsonPath/issues/274)
- [252](https://github.com/json-path/JsonPath/issues/252)
