### ISSUE TITLE
[Bug 1.11.5]: Hill blocking layer includes MBL within the area.

### ISSUE THREAD

**Issue by aliasmask** [RPTools/maptool#3369]
### Describe the Bug

When drawing Hill Blocking layer as a solid shape, tokens within shows 0 AI movement within area and the lastPath adds the failure: 1 to path.

### To Reproduce

Draw a Hill only blocking layer, say 10x10 square. Move token in to area. AI movement shows 0 move distance. If you include onTokenMove macro in a lib token and display lastPath() info, it will show failure, for example:
```
path: [{"x":350,"y":150},{"x":350,"y":200,"fail":1}]
```

### Expected Behaviour

Movement in to Hill area should have valid pathing by the AI. If I wanted to include MBL, I would redraw around area an MBL border. 

### Screenshots

![image](https://user-images.githubusercontent.com/43827071/154614997-8b06ba2f-7fd4-4675-8d9c-466d5c5bb17c.png)

### MapTool Info

1.11.5

### Desktop

Window 10

### Additional Context

Additionally, the same behavior is true when navigating inside Pit VBL.

**Comment by kwvanderlinde** [comment]
I'm pretty sure you have the option set for tokens to navigate around VBL. If you don't want them to do so, then disable that option.

**Comment by aliasmask** [comment]
Afaik, Hill blocking layer is not VBL, and it's not blocking vision when inside it. So, it should be able to move into and through it. If I move the token from the street through the building to a spot not seen it will properly go around the building.

If I turn off "navigate around" it ignores all VBL and I don't want that. I would like the fail:1 to appear when moving on to roof, by putting an MBL border around it, but not when I'm navigation in the HBL on the roof.

**Comment by kwvanderlinde** [comment]
> Afaik, Hill blocking layer is not VBL

It _is_ called "Hill VBL" though, not Hill blocking layer, and that was deliberate (and not just because it doesn't block hills!) The fact is that Hill/Pit VBL are just relaxations of VBL with regards to vision. Also my understanding (though admitedly not based on very much) is that blocking movement via VBL is kind of a holdover from times before MBL, rather than a deliberate continuing interaction between pathfinding and vision.

More importantly, though, I'm trying to understand the use case. I.e., why would a token be specifically prevented from pathfinding over Hill VBL while still allowing the token to enter it, move through it, and then leave it again?

**Comment by aliasmask** [comment]
Arguing semantics isn't addressing the issue. HBL was tossed around in the discord as a naming convention to represent this type of VBL. Before separating vision and movement blocking if you couldn't see the spot being moved to, then your movement was blocked, otherwise you are free to move to that position. HBL doesn't block the vision in to it, only through it. And while in it, no vision is blocked.

The bug I referring to is that the HBL includes MBL when I don't think it should other than when trying to move completely through the HBL to the side you can't see.

**Comment by kwvanderlinde** [comment]
> Arguing semantics isn't addressing the issue. HBL was tossed around in the discord as a naming convention to represent this type of VBL.

Do not dismiss me as arguing semantics. HBL doesn't exist, it's a made-up name, and a confusing one at that. It drops the very important "V(ision)" from the real name ("Hill VBL"), which is why I clarified the real name. You can't say "Hill VBL isn't VBL" when "VBL" is right there in the name!

> Before separating vision and movement blocking if you couldn't see the spot being moved to, then your movement was blocked, otherwise you are free to move to that position.

This is only true on a cell-by-cell basis for pathfinding, but nothing larger than that. Whether or not the target position can be seen from the start position has nothing to do with it. For example, tokens can navigate around to the back-side of a wall without being able to see it, the only thing that matters is that there is a path to get there where each step in the path is valid.

> The bug I'm referring to is that the HBL includes MBL when I don't think it should other than when trying to move completely through the HBL to the side you can't see

There's a few things going on here:
1. You want to move unimpeded within Hill VBL.
2. You want to block movement that goes completely through Hill VBL
3. (inferred from an earlier comment) You also want to be able to move into and out of Hill VBL, as long as it's not completely through Hill VBL.

But (2) is incongruent with the others. Moving completely through an area is the same as stepping into the area, moving through it's interior, then stepping out of it. So if a token can step into Hill VBL, and if a token can move freely through Hill VBL, and if a token can step out of Hill VBL, then it should also be able to make a path through Hill VBL in one go because each step is valid.

**Comment by Phergus** [comment]
Kenneth is the one that designed and implemented the VBL changes with input from several folks who took part in the discussions and testing during beta releases.

Hill VBL is worked as designed.

**Comment by aliasmask** [comment]
Go ahead and close issue. I may submit a FREQ at a later time. Thanks for the explanation.

**Comment by adyoungblood** [comment]
I would appreciate pathfinding working exactly with vision, even though it may be working as designed at the moment. I'm drawing a dragon's lair with some complex terrain at the moment, and putting Hill VBL on the raised parts doesn't allow players to walk through them as would be intuitive.
