### ISSUE TITLE
[Bug]: Can't run some rptokens

### ISSUE THREAD

**Issue by agirnob** [RPTools/maptool#3432]
### Describe the Bug

after right click on the token lib_mixer.rptok from discord(https://cdn.discordapp.com/attachments/888378297489174568/979988585753215016/lib_mixer.rptok)
my maptool instance just crashes

### To Reproduce

import the token: https://cdn.discordapp.com/attachments/888378297489174568/979988585753215016/lib_mixer.rptok
right click on it.
when opened from terminal see java run time crashes

### Expected Behaviour

work normally

### MapTool Info

maptool 1.11.5, downloaded from aur

### Desktop

Linux: EndeavourOS

### Additional Context

Downloaded jdk:18.0.1 openjdk liberica

I have the log output if needed i can upload that either

Terminal output:
```

A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007f50fc44541e, pid=20803, tid=20842

JRE version: OpenJDK Runtime Environment Temurin-16.0.2+7 (16.0.2+7) (build 16.0.2+7)
Java VM: OpenJDK 64-Bit Server VM Temurin-16.0.2+7 (16.0.2+7, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
Problematic frame:
C  [libharfbuzz.so+0x4541e]

Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/agirnob/core.20803)

An error report file with more information is saved as:
/home/agirnob/hs_err_pid20803.log

If you would like to submit a bug report, please visit:
  https://github.com/adoptium/adoptium-support/issues
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

Aborted (core dumped)
```

**Comment by kwvanderlinde** [comment]
I tried to reproduce this issue on Linut Mint but was unsuccessful. If you could upload any log files you have, that could be very helpful.

What I did manage to do is some google searching and it seems Arch in particular is being hit by a libharfbuzz SIGSEGV, and I'm seeing plenty of reference to EndeavourOS in particular. I tracked down a [bug report for Arch](https://bugs.openjdk.org/browse/JDK-8255790) (or if you like its [duplicate for EndeavourOS](https://bugs.openjdk.org/browse/JDK-8284986)) which indicates that this issue is fixed in Java 17, with backports to 11, 13, and 15, but not 16. So - assuming this is actually the same issue) MapTool 1.12 should not suffer from this problem when it is released.

I'm not sure if there is an easy way to run the AUR-installed MapTool on a different Java version (no familiarity with Arch myself), but it would be interesting to see if running MapTool 1.11.5 on Java 17 or 18 fixes the problem.

**Comment by agirnob** [comment]
i will try to compile maptool on my system and then try with a newer version of jdk. Because i dont know how to open maptool with a different java version enviroment(even though i know how to change it system wide) variables doesn't change maptools included jre which is on jdk 16 like seen in the crush. I will write if compiling works with a newer version
