### ISSUE TITLE
[Bug]: Unable to join servers with certain tokens present.

### ISSUE THREAD

**Issue by kwvanderlinde** [RPTools/maptool#3436]
### Describe the Bug

After starting a server with certain tokens present, players are unable to join the server and are met with a black screen saying "Loading Campaign".

### To Reproduce

1. Start a first MapTool instance
2. Import this UVTT file: [10x10 Four Rooms with Lights.dd2vtt.zip](https://github.com/RPTools/maptool/files/8855625/10x10.Four.Rooms.with.Lights.dd2vtt.zip)
3. Start a server
4. Start a second MapTool instance
5. Attempt to join the server from the second instance
6. At this point the second instance should be stuck at "Loading Campaign"
 

### Expected Behaviour

Players can join the server regardless of the tokens present.

### MapTool Info

develop (85417f5)

### Desktop

Linux Mint 20.3

### Additional Context

The bug results from an NPE being thrown on server start thanks to the token's shape/type being null while protobuf expects non-null values.

**Comment by thelsing** [comment]
Is the bug token having no shape or protobuf expecting a shape?...

**Comment by Phergus** [comment]
When the light tokens are created/added in the DungeondraftImporter no shape is being set so that's probably one issue.

I also notice that if I just immediately import that particular UVTT map and start a server when the server started message is shown the map display goes black.  I can then select the map from the map selector and get the map display but get an NPE:
![image](https://user-images.githubusercontent.com/34379254/172463297-476a96a0-8448-47a0-b409-e77e81b59ccf.png)

So possibly something else isn't initialized and needs to be.  Don't see this issue with maps that don't have the light tokens created.

**Comment by thelsing** [comment]
I think this is because the server wasn't started properly. (black screen) You probably shouldn't be able to change the map in this case.

**Comment by Phergus** [comment]
PR #3437 appears to have corrected the issue in my testing.
