### ISSUE TITLE
[Feature]: Javascript modules does not appear to work in WebView

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#3513]
### Feature Request

Javascript modules does not appear to work in WebView. 
Getting this to work would make it much easier to reuse code between webpages, while preserving scope. 

### The Solution you'd like

I'd like javascript modules to be working as specified in ES6, which *should* be supported by WebView, but it doesn't appear to be.

**Comment by Tdue21** [comment]
Closed as modules are not really an issue with WebView anyway. The webpage creates a single javascript context anyway, when linking several scripts through `<script src=".."></script>`. 
Add defer to the script and the load order can even be controlled.

**Comment by kwvanderlinde** [comment]
I recently experimented with adding modules on a whim, so thought I would share what I found. It _is_ possible to get top-level inline module scripts working (i.e., `<script type="module">`) by changing how we load pages into the web view. But I have had no luck loading modules using `src="..."` or `import`, due to CORS restrictions, and I haven't been able to figure how to disable or work around CORS.
