### ISSUE TITLE
Version mismatch between 1.5.0 builds

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#358]
Windows Installer build of 1.5.0 reports itself as 1.5.0.0 in the Splash Screen, About Window and on the RPTools.net server list.

JAR only build reports itself as 1.5.0 in the Splash Screen, About Window and on the RPTools.net server list.

As a result the different builds cannot connect to each other and will also have issues with loading files saved with the other build.

Unknown what version numbers are being reported by Mac & Linux builds.

![Screenshot 2019-03-21 10 14 15](https://user-images.githubusercontent.com/34379254/54767117-22bc1180-4bc2-11e9-813f-31b36e06ffb1.png)

**Comment by Phergus** [comment]
This also causes the installer build to report that a new version (1.5.0) is available to download on startup.

**Comment by JamzTheMan** [comment]
@Phergus I'll test this when I get a chance but can you make sure you are running the latest version? Uninstall if you have to?

Because...the "version" check isn't based on "version" at all. It's actually comparing the commit sha that's embedded in the JAR manifest against the commit sha for the "latest version" from the API.

So, even if the version number is incorrect, you shouldn't get a prompt for a newer version unless you are in fact running on a different commit.   If the commit is wrong we need to investigate the build process. (commit should be logged in your maptool log)

**Comment by Phergus** [comment]
@JamzTheMan Verifying now.  Uninstalled and re-downloading the installer..

**Comment by Phergus** [comment]
That was it.  Whew.  I installed into the same directory as a previous dev build and it was a mix or old/new files.  Not sure why/how that happened.  Uninstalling the 1.5 builds and then re-installing has fixed it.  Version is reported the same in both installed and JAR builds and are interoperable.

PEBKAC error.

**Comment by JamzTheMan** [comment]
cool cool :+1: 

I kinda thought we would have a LOT more reports if that really was broken like that. :smile:
