### ISSUE TITLE
[Request] Move macro button instead of copy

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#369]
Current, if one drags a macro button from one group to another, it is copied. This is fine, I am sure. It would be nice though, if it was possible to move it by dragging as well. 
E.g. shift-drag would move and drag would copy as it always has.

**Comment by adyoungblood** [comment]
Resurrecting this issue because I would also love this feature. I've coded up a working prototype, which is in the pull request. I don't believe there are any side effects to this change, but I could be wrong, so testing is probably needed.

**Comment by adyoungblood** [comment]
I've discovered the source of why ACTION_MOVE is the default (see the conversation in the linked pull request). I'm bringing it up here because the reason raises an interesting question, even though it is more code-oriented. To cut a long story short, according to the [DragSourceDragEvent](https://docs.oracle.com/javase/8/docs/api/java/awt/dnd/DragSourceDragEvent.html) documentation, the system chooses the action to apply to a drag event in a pre-determined order, going MOVE -> COPY -> LINK. Modifier keys allow you to pick a specific one, but the default action is not changeable (it is an open bug in Open JDK to be able to do so).

This raises the question of whether moving macros instead of copying them should become the default, if only for the sake of clarity within the codebase. That said, I suspect moving macros is usually what is desired when a user drags a macro around. I'm thinking specifically players trying to rearrange their token's macros, having to delete the old macro each time they move a macro. It is a fairly large change though, so I wouldn't want to sneak it into a small feature request such as this. Something to keep in mind, perhaps?

**Comment by Phergus** [comment]
I've always thought it was weird that the behavior was to copy as 99% of the time I was wanting to move the macro not copy it.  As you say, the current behavior requires a copy and then a delete of the original by the user.

I would prefer it behave much like dragging files under Windows.

- Drag a macro within groups on the same macro panel and it is a Move.
- Drag between panels and it is a Copy.
- Shift-drag would be an explicit Move for any destination.
- Ctrl-drag would be explicit Copy for any destination.

Something to get some feedback from users on before making such a change however.

**Comment by adyoungblood** [comment]
Glad you thought of that, because I certainly wouldn't've. [7e59e08](https://github.com/RPTools/maptool/pull/2404/commits/7e59e08824982d5964c39c6f051dc3023c5bae46) implements your suggestions, as well as fixing the macro deletion code (which I realized was horribly broken). I did a bit of basic testing once I was finished, and everything seemed to be in working order. Obviously subject to change, and I'll begin collecting some feedback.

**Comment by adyoungblood** [comment]
Oh, this may need a _lot_ of testing on other platforms. I'm not entirely sure how that's meant to work (let the bug requests flow, then fix?)

**Comment by Phergus** [comment]
@adyoungblood with Macs involved any time we use modifier keys for mouse actions we have to deal with the oddities there so I suspect it will require some additional updates.

**Comment by Phergus** [comment]
Tested.  Dragging macros working as described.
- Drag a macro within groups on the same macro panel and it is a Move.
- Drag between panels and it is a Copy.
- Shift-drag would be an explicit Move for any destination.
- Ctrl-drag would be explicit Copy for any destination.
