### ISSUE TITLE
[Bug]: Multiple light sources actually darken each other due to their dim light range when the lumens should be, instead, added to overlapping light or at least not darken.

### ISSUE THREAD

**Issue by adventuremagic123** [RPTools/maptool#3755]
### Describe the Bug

The problem here is that the multiple light sources are actually darkening each other due to their dim light range.  Instead, the lumens in their dim range should be added to that provided by the other light source.

![Screenshot 2022-11-27 143954](https://user-images.githubusercontent.com/50708405/204158588-8429629e-41cc-45e2-b385-37b9f8804824.png)

### To Reproduce

1. Create multiple light sources whose light overlaps with each other.
2. Notice how the dim light radius darkens overlapping light sources when the lumens should be added.

### Expected Behaviour

Light should add lumens to other overlapping light.

### Screenshots

See above.

### MapTool Info

1.12.2

### Desktop

Windows 10

**Comment by kwvanderlinde** [comment]
I'd like to clarify the how lights work in MapTool, as lumens and colours are entirely separate systems.

**Lumens** establish the mechanics of light source. They determine which light sources are truly lights and which are darkness. They also determine which areas are lit, with darkness and light competing with each other when they overlap. Lumens do not add or blend together when lights overlap. This is working as intended (though it could be an interesting feature request to have lumens add together :slightly_smiling_face:). Also, each light source only has one lumens value which applies to the entire light source and not to a particular range. So, for example, a torch's bright range and dim range are mechanically identical (sounds like another feature request in the making :thinking:)

**Color** is the aesthetic aspect of lights. They don't modify the behaviour of lights in any way except to control which color is used to draw them onto the map. Light colours intentionally blend with one another, though as this bug report points out the blending tends to darken lights instead of brighten them as we would expect.

---

We actually had additive light blending for a short time when 1.12 first came out, but it was pulled for performance reasons. We do want to bring it back, but that will depend on us finding a way to do it without tanking performance.

**Comment by SherbanWisperwald** [comment]
I have read the change log and seen some light changes, but in my opinion the lighting is now worse than before. Is there a possibility to bring the 1.11.5 behaviour back somehow? It was quite usable for determining which regions are lit, dim lit and so on. See examples (all using standard "Candle 5"):
The 1.11.5 Version:
![with_1 11 5](https://user-images.githubusercontent.com/15799278/204394217-582ecd5d-454f-4051-8992-5166c70ebff0.png)
The 1.12.2 Version:
![with_1 12 2](https://user-images.githubusercontent.com/15799278/204394367-4e72e883-2397-48e0-8c8d-3bc6fb5c01a2.png)

From a gamplay point of view, I do not need more realistic light addition, for me it is completely sufficient to have "lit" and "dim lit" areas. The 1.11.5 Version did exactly what I needed. (And no, I would like to update someday because of the new token VBL/MBL posibilities :-) )

**Comment by kwvanderlinde** [comment]
Just so it's clear before I go off talking about other stuff, I definitely understand the desire for the old lighting. It works quite well in a case like yours and I find it unfortunate that I nullified that use case :slightly_frowning_face: 

That said, there are issues with the old lights as well. E.g., the reason your example looks so good is because the default D20 light sources have uncoloured (aka "bright") inner ranges. It's a good default for that reason! But if we colour the inner range as white (`#ffffff`), we get this instead:
![image](https://user-images.githubusercontent.com/7492219/204406374-f6e0ae0d-9f04-4ca7-a47a-922b90d1a3be.png)
You can see another example in an old [bug report of mine](https://github.com/RPTools/maptool/issues/1550) where I found the old system very confusing.

The old system does work quite well for your case. Really, whenever you only use a mix of uncoloured (aka "bright") lights, and at most one colour of light to represent dim lights, then the results can be pretty good for a game the revolves around the bright/dim/dark delineation. But as soon as you need/want to capture more (e.g., tint darkvision red or something), then the behaviour becomes confusing.

_now I just have to run and figure how to make everything better again while losing nothing anyone wants_

**Comment by FullBleed** [comment]
Out of curiosity... how much of this becomes easier, better, faster, stronger once we have libGDX?

**Comment by adventuremagic123** [comment]
BTW, MapTool 1.10.4 also works much better for light sources -- probably like 1.11.5.  Dim light in 1.10.4 does NOT darken overlapping light sources.

**Comment by adventuremagic123** [comment]
This is how that scene looks in MapTool 1.10.4.  Each of the tables with a light source have a candle and there are torches on the wall.  I did add one torch where one was missing (it's in the middle on the right side of the stage).  This scene is messed up in MapTool 1.12.2 (as shown above).

![Screenshot 2022-12-30 162432](https://user-images.githubusercontent.com/50708405/210115542-0dc16510-37e0-4ff3-ae13-b44619a84b28.jpg)

**Comment by adventuremagic123** [comment]
My settings are as follows:

Auras
----
Aura - Player - 10: aura circle 7.5#0000ff
Aura - Player - 5: aura square 2.5#0000ff
Aura - Owner - 10: aura OWNER circle 7.5#00ff00
Aura - GM - Red - 10: aura GM circle 7.5#ff0000
Aura - Owner - 5: aura OWNER square 2.5#00ff00
Aura - GM - Red - 5: aura GM square 2.5#ff0000

Darkness
----
Lantern, Darklight - 30: circle 32.5 lumens=-20
Spell, Deeper Darkness - 60: circle 62.5 lumens=-130
Spell, Darkness - 20: circle 22.5 lumens=-20

Light Sources
----
Outside, Daylight: square 1,000#000000 lumens=30
Spell, Daylight - 60: circle 62.5 122.5#000000 lumens=30
Lantern, Bullseye (leaks light) - 60: cone arc=60 62.5 122.5#000000 circle 2.5#000000 lumens=20
Lantern, Miner's - 30: cone arc=30 32.5 62.5#000000 lumens=20
Torch - 20: circle 22.5 42.5#000000 lumens=20
Lamp - 15: circle 17.5 32.5#000000 lumens=20
Lantern, Hooded - 30: circle 32.5 62.5#000000 lumens=20
Spell, Light - 20: circle 22.5 42.5#000000 lumens=20
Goggles, Nightvision - 40: cone arc=30 42.5#00e000 lumens=30
Lantern, Bullseye - 60: cone arc=60 62.5 122.5#000000 lumens=20
Candle - 5: circle 7.5 12.5#000000 lumens=10

**Comment by adventuremagic123** [comment]
It's important to fix this because it's a very distracting issue during game play.

**Comment by adventuremagic123** [comment]
I've noticed in Foundry VTT that it's doing what people might be asking for in MapTool -- where lumens are additive between light sources.  I'm not sure this is a good idea.  It actually doesn't look good.  I don't recommend it -- or possibly at least provide an option to turn it off.

Look at this below.  Here's two overlapping light sources.  Everything gets worse if you make them flicker -- looks really annoying.  Kind of an example of just because you can -- should you?  Maybe, not.

![light sources overlap](https://user-images.githubusercontent.com/50708405/224515223-e2388746-8de0-494d-a2f3-132d6183d3e5.jpg)

**Comment by adventuremagic123** [comment]
I've noticed that in Foundry VTT, if you set the illumination value (I think is what it's called) to 0, the above effect is made much less noticeable.  At first, I thought it fixed the problem, but I think the issue is still happening actually.

**Comment by adventuremagic123** [comment]
As far as I can tell, this issue is fixed in MapTool 1.13.0 RC 1 using the test cases I have here.

**Comment by kwvanderlinde** [comment]
I'll consider this done given we have validation from OP that this particular issue is fixed.
