### ISSUE TITLE
[Bug]: maptool freezes when draging an image onto the token property window

### ISSUE THREAD

**Issue by Lector** [RPTools/maptool#3768]
### Describe the Bug

Sometimes, when dragging an image from the file system to maptool the application freezes. The property window, that appears after double clicking a token, has to be open to cause this freeze. The freeze happens in the moment the mouse enters the area of the maptool main window. The freeze is not consistently reproducable and i mentioned that not everyone can reproduce it, even with the same campaign file.

### To Reproduce

1. Doubleclick a token.
2. Goto config tab (not sure if this step is nessecary)
3. Drag an image from the file system onto the token/portrait/handout slot.
4. Repeat step 3 until it freezees.

### Expected Behaviour

I would expect maptool to not freeze.

### MapTool Info

1.12.2

### Desktop

Windows 10

**Comment by kwvanderlinde** [comment]
Likely related to #2781 in terms of the cause.

One of the [bugs I linked](https://bugs.openjdk.org/browse/JDK-8274751) in that issue wasn't fixed until Java 19, though the fix was backported to 17.0.4 (I haven't had a chance to verify that though). MapTool is still on 17.0.1, so we might be seeing that issue and a Java update might fix it.

I'm able to reproduce a similar symptom on Linux Mint. I don't see the whole appliction freeze or crash, I just see MapTool give up on accepting drag-and-drops. This could just be a different symptom on a different platform for the same underlying problem (my gut says it is anyways). Also, it _could_ indicate that there is a weakness in MapTool's drag-and-drop logic beyond any underlying Java issue, but hard to say without more investigation and testing on an updated JDK.

Reproduction steps for the related issue:
1. New campaign, add a token to it.
2. Edit the token. 
3. Drag and hold an image over the token's image. Make sure the cursor indicates that the image can be dropped there.
4. Instead of dropping there, move the cursor over the map (where dropping is not allowed) and drop the image there.
    - Has to be quick enough that the cursor doesn't update to its neutral state that indicates dropping won't be done.
5. Now I'm no longer able to drop an image even places where it is allowed.
    - Can't drop in the token image or portrait boxes.
    - Even after the dialog is closed, can't drop on the map.
    - Can't even drop from the Library panel anymore (though that has an even clearer "not allowed" cursor).

Screenshot for step (3) (note the hand with the plus sign):
![droppable-image](https://user-images.githubusercontent.com/7492219/206311393-322577fc-28c5-4e67-84c6-109cfa33de6f.png)

And for step (4) (note that same cursor as in step 3):
![droppable-image-wrong](https://user-images.githubusercontent.com/7492219/206311448-23eb5df6-a3e3-4a4f-8c5a-95884effac7d.png)

And the result is that new drops aren't accepted (note lack of the plus sign in the cursor):
![droppable-image-not-allowed](https://user-images.githubusercontent.com/7492219/206312300-cd1b8a4f-1d50-440a-84d0-508ee4741035.png)

**Comment by Azhrei** [comment]
It may be worthwhile to update the Java and produce a new build, if, in fact, an updated JDK will fix it.  If nothing else, the OP could test against it (and updating may fix a couple of outstanding JFX issues, among others).  @Phergus ?

**Comment by Phergus** [comment]
@kwvanderlinde did you try testing the current dev branch with 17.0.4?  I'll be out most of tomorrow but will check in on Friday.

**Comment by kwvanderlinde** [comment]
Haven't yet, but I plan to do so within the next couple days. And to try it out on Windows as well.

**Comment by kwvanderlinde** [comment]
I've now tried it out on Windows 10 but unfortunately have not been able to reproduce the problem.

**Comment by Jmr3366** [comment]
When this came up on Discord I attempted to duplicate on two systems, an old win10 laptop and a new win11 desktop.  No matter how hard I tried I could never duplicate this issue (on 1.11.5 nor 1.12.2). 
IIRC One variable was AV software and if disabled the symptom greatly reduced.

**Comment by Lector** [comment]
I remember our discussion on discord. As far as i remember we came to AV at first but i mentioned afterwards that it was still freezing sometimes with disabled AV. Since this happens very inconsistently its hard to give you helpful information on how to reproduce this. All i know is that the freeze never happened to me when dragging an image to the map, without having the config window open. And i did a lot of work with building tokens for my campaign.
If you dont find it, i can still import images on other ways than dragging them in from the file system. Its not as comfortable but thats ok.

**Comment by kwvanderlinde** [comment]
I feel your pain as I've run into my fair share of issues in the same area. Things that are no fault of MapTool's, they're just bugs in the Java runtime that we pay the price for.

I think it's possible to enable debug logs, but I don't know how to do it as an end user. If someone could chime in how to do that (or if I'm totally out to lunch). A detailed log file could prove quite useful in trying to pin this down the next time it happens :crossed_fingers:

**Comment by Azhrei** [comment]
The logs produces by MT won't help.  I know that from experience. :)

In the past, I've connected VisualVM to my instance of MT and tried to log _everything_. That produces a lot of data (obviously) but the one thing that I saw come up multiple times were calls to park() and unpark().  I looked at the Java source code to try to figure out what those functions are for and how they work, but they were buried so deep in the code base that it was all detail and not enough big picture.  (They are used by the Object.wait() method, for example, and are apparently used to put a thread to sleep while waiting on an event.)  Unfortunately, I have nothing more than that. :(

(It looks like VisualVM is not a GitHub project.  It wasn't the last time I used it.)

**Comment by kwvanderlinde** [comment]
Ah, yes, the dreaded park()/unpark() :smile:

Even if that turns out to be the case here, I'm just hoping for anything to try and narrow down the failure point beyond drag-n-drop as a whole. Certainly not expecting to find an easy answer in there, but anything is better to go on than nothing, which is what we have right now ...

Aside from logs, the best bet right now is for us to make a special build of 1.12.2 with an updated JRE that @Lector can try out. We might get lucky and have that fix everything. I can try get that together soonish, unless someone more familiar with producing artifacts wants to jump in ...

**Comment by Lector** [comment]
It's been almost a year since I reported this issue, and I can't recall encountering it recently while using MapTool regularly. I assume it's been fixed, though I'm not sure in which version. If there were still problems in 1.12.2, I would have raised concerns. I always use the latest MapTool version.

**Comment by Lector** [comment]
I use MapTool 1.17.1 and have mentioned this issue several times already. I skipped a few versions since I wasn’t very active on MT lately, so I’m not sure when exactly this bug reappeared.
