### ISSUE TITLE
[Feature]: Add proper html support for token notes.

### ISSUE THREAD

**Issue by thelsing** [RPTools/maptool#3791]
### Feature Request

Currently one can use html tags in token notes, but there is no proper html editor for them. Also the hover display inserts <br> for every linebreak in the notes. One can only work around it by having all html code in one line. 

### The Solution you'd like

I would also like to be able to just copy & paste content from websites into those fields and keep formating.
Best would be a WYSIWYG editor for html with the ability to edit the source code if necessary.

### Alternatives that you've considered.

Only using one line of html text. But I still can't paste HTML this way.

**Comment by thelsing** [comment]
I already have this in my personal use branch. I combined the JFX HtmlEditor control with rsyntaxtextarea.

**Comment by Phergus** [comment]
>  I combined the JFX HtmlEditor control with rsyntaxtextarea

Any potential issues with that?  Likely to break on future Java releases?

**Comment by thelsing** [comment]
Not more likely than our other JavaFX Controls breaking. Its just a JPanel with two tabs. Nothing complicated:
<img width="645" alt="image" src="https://user-images.githubusercontent.com/20617946/209692793-0b0610a8-d328-4cf9-888b-d00066e89cac.png">
<img width="628" alt="image" src="https://user-images.githubusercontent.com/20617946/209692828-daf78db0-454a-42db-ad59-e1b83f05baee.png">

Only issue is that JavaFX controls don't use the flatlaf themes.

**Comment by thelsing** [comment]
I will wait with a PR until #3785 is merged because this change depends on that.

**Comment by Phergus** [comment]
Nice.

**Comment by Phergus** [comment]
Tested.  Better HMTL support in notes.  Seems to add in extra whitespace but the HTML can be edited directly if needed.

**Comment by kwvanderlinde** [comment]
I like this editor, it looks handy.

I'm going to push back on one aspect of these changes though: we should not force notes to be HTML. There are existing campaigns and well-established frameworks that use notes for purposes other than the built-in notes overlay, and which cannot function properly if the notes are modified. E.g., I personally make use of Rod's 5e framework which makes liberal use of markdown, including storing it in notes / GM notes. With the notes being turned into HTML documents, the framework is no longer able to properly render the markdown into HTML fragments that can be inserted into frames, and it breaks the custom roll links built into the framework.

***

And one minor bug I found while testing that out: most stamps will now count as markers since even empty notes and GM notes still store HTML content. So clicking on an object with no notes, GM notes or portrait results in a teeny tiny empty notes overlay:
![image](https://user-images.githubusercontent.com/7492219/225817843-eee5f69a-e3d0-4572-b78f-dfbfd12d95e9.png)

Brand new tokens are exempt until edited.

**Comment by Azhrei** [comment]
> I'm going to push back on one aspect of these changes though: we should not force notes to be HTML.

Agreed.

Do we have control over the tabs at the bottom?  Could a third one for Markdown be added?  IIRC, rsyntaxarea is capable of supporting just about any syntax highlighting if we can find/create our own regexes to handle where each type of highlighting begins and ends.

For upward compatibility...  When loading a campaign, if the first characters (skipping leading whitespace, of course) are `<html` then we can treat the field as HTML.  If any of the first 5-10 lines start with `# ` then treat it as Markdown.  Anything else is plain text.  Might need two new fields in Preferences:  **Fallback text type** (Markdown / Plain text) in case Markdown should be the default when the type cannot be determined, and **Override text type with fallback value** (yes/no) to force the fallback type to always be used for non-HTML notes. (Ugh.  Better ideas are welcome.)

**Comment by thelsing** [comment]
Maybe we should just put the format of the notes into the campaign properties? Not sure if it different token in the same campaign should have different formats of notes.
If this should be possible then we should probably add the noteformat to the token.

**Comment by thelsing** [comment]
> For upward compatibility... When loading a campaign, if the first characters (skipping leading whitespace, of course) are `<html` then we can treat the field as HTML. If any of the first 5-10 lines start with `# ` then treat it as Markdown. Anything else is plain text. Might need two new fields in Preferences: **Fallback text type** (Markdown / Plain text) in case Markdown should be the default when the type cannot be determined, and **Override text type with fallback value** (yes/no) to force the fallback type to always be used for non-HTML notes. (Ugh. Better ideas are welcome.)

IMO we should just add relevant fields to Token or CampaignProperties and check if we are opening an old campaign and ask the use what type of notes he wants. 
Autodetection will cause more harm than good. Who knows what the different frameworks store in the notes. JSON? base64 encoded images?

**Comment by Azhrei** [comment]
Auto detection would always fallback to plain text (unless the user selects otherwise in Preferences).  So only HTML and Markdown formats would be processed (HTML AS IS, while Markdown would be converted to HTML on the fly).  We already auto detect a lot of stuff when reading the campaign and always have; it’s one reason why MT can read campaigns from 15 years ago with minimal impact.

Each token has its own settings, as some on the Object layer may just be informational and used by the GM or players as reference points, while others might have more formatted info in them or even data (as you point out).

**Comment by kwvanderlinde** [comment]
> Maybe we should just put the format of the notes into the campaign properties? Not sure if it different token in the same campaign should have different formats of notes.
> If this should be possible then we should probably add the noteformat to the token.

From my own experience, it is sometimes useful to have different tokens use different formats. E.g., most tokens operate under a framework, but there are other that you do want to use with the built-in notes display. Or by using more than one framework, each with different assumptions.

***

I think we should just aim to have MT be less opinionated about the contents of the notes. This can be done with small tweaks to the current state of things. We also don't need special support for markdown or any other kind data, as long as we leave things alone unless asked to do otherwise (we _could_ have support for others, but it's in no way needed).

Here is an example of how we can preserve existing data while keeping things mostly the same:
- The first thing is to not have the `Token` getters convert to HTML.
- After that, I noticed the **Text** tab does not convert the contents to HTML, while (of course) the **HTML** tab does. So we can prefer showing the **Text** tab rather than the **HTML** tab, and that would leave the data alone. _The highlighting alone is a nice enhancement for those who do want to edit HTML by hand. And it's also not a bad deal for anyone who write markdown by hand, since HTML tags can be embedded in markdown too._
- If desired, the user can switch to the WYSIWYG editor, which will convert to an HTML document now that it's been requested.

And there's plenty of room to do other things on top of that that could improve the user experience. E.g.:
- If the user switches to the **HTML** tab, persist that choice in the `Token` so they don't have to switch tabs for it in the future.
- If the user mistakenly switches to the **HTML**, makes no edits, and then goes back to the **TEXT** tab, we can have the original contents waiting for them. No harm no foul :slightly_smiling_face: 
- Add a campaign property for users to say "I really do want all my token notes to be HTML no matter what".
- Add a syntax highlighting selector similar to that in the token property editor. Optionally try to guess what highlighting to use.

_I'm not actually suggesting or requesting any of these, I only put them there to prove the point._

***

Shifting gears, I was doing more testing and found another quirk, which I guess is what Phergus is referring to as well:
> Seems to add in extra whitespace but the HTML can be edited directly if needed.

There can be quite a bit of extra vertical space added depending on the size of the notes. E.g.,:
![image](https://user-images.githubusercontent.com/7492219/226532678-835ba942-b7a1-46e2-aa0c-38bca8f04f71.png)

This seems to be the result of embedded a complete HTML document (`<html>` and all) inside of a `<table>`. If I instead hack in the contents that would be inside the `<body>`, it looks more natural, and is also in line with previous behaviour:

![image](https://user-images.githubusercontent.com/7492219/226533351-14cc969f-1ff4-43bf-815b-3155613102fd.png)

From this angle, it makes sense to extract the (`<body>`) contents of HTML notes for inclusion in the notes overlay rather than injecting the entire document. Though I say this without considering the ramifications of eliminating the `<head>` or other potential pitfalls.

**Comment by thelsing** [comment]
I'll add a text type for notes and gmnotes for now with text/plain as default. Supported mime type will be text/plain, text/html and text/markdown. I'll reorder the tabs making TXT the first one the HTML tab also works as a (not editable) preview for markdown. 

I'll also only store the content of the body tag from the html editor.
