### ISSUE TITLE
[Bug]: New HTML formatting in token notes removes newlines

### ISSUE THREAD

**Issue by Irarara** [RPTools/maptool#3814]
### Describe the Bug

When a plain text note has HTML formatting applied, the newlines are replaced with spaces. This is mostly an issue when trying to look at notes on older tokens where newlines were used to break up the content. Notes that were readable in earlier versions are now basically unreadable in some cases.

### To Reproduce

1. Open the Edit Token dialog of token, go the Notes (or GM Notes) tab and then go to the TEXT tab beneath the editor and enter the following into the editor:
```
a
b
c
```
2. Go to the HTML tab and then switch back to the TEXT tab and observe the content is now:
```
<html dir="ltr">
 <head></head>
 <body contenteditable="true">
  a b c
 </body>
</html>
```

### Expected Behaviour

Old notes should be readable without needing to be reformatted manually. Newlines should either be preserved (so they're at least present in the plain text view) or replaced with `<br>` (or wrap each line in a div, or something).

### MapTool Info

develop

### Desktop

Windows 10

**Comment by Azhrei** [comment]
I agree that older token notes shouldn't need to be manually updated.  I'm inclined to recommend that `\n\n` be replaced with `\n<p>\n` since entering an empty line is typically regarded as starting a new paragraph, and a newline by itself be replaced with `\n<br/>\n` to indicate a "hard return".

(I don't think a `<div>` is the right way to go as they are not self-closing and might cause other formatting issues.  I'm thinking primarily of the day when user stylesheets are supported or such settings can be associated with a theme.)

**Comment by Irarara** [comment]
> I don't think a <div> is the right way to go as they are not self-closing and might cause other formatting issues

Good point. I only mentioned it because I thought I saw the editor doing that itself, but it turns out I was mistaken and its behavior is to wrap each separate line in `<p>` tags. 

So, you can ignore the remark about divs. My point anyway is I'm not concerned about how it's handled.
