### ISSUE TITLE
[Feature]: Let the DM know when a player finishes loading assets 

### ISSUE THREAD

**Issue by sauliuskarmanovas** [RPTools/maptool#3890]
### Feature Request

Info for the DM know when the player is ready to play.

### The Solution you'd like

A simple message in GMs chat would be enough. Maybe some time down the road actual `ClientMessages` with handlers and events to show in a nice separate panel what zone each player is in and their loading progress. 

### Alternatives that you've considered.

Asking several times every player if they are in yet every time the map changes 🤢

**Comment by sauliuskarmanovas** [comment]
Something like
```
if (MapTool.getConnection() != null) {
  String mesg =
      MessageUtil.getFormattedSystemMsg(
          I18N.getText(
              "msg.info.playerFinishedLoadingZone",
              MapTool.getPlayer().getName(),
              zone.getDisplayName()));
              
  TextMessage msg = TextMessage.gm(null, mesg);
  MapTool.addMessage(msg);
```
with `{0} has finsihed loading into zone {1}.` as a message.
Right here
https://github.com/RPTools/maptool/blob/4144494eefe7f8a52b8de751ef483b08186f65f2/src/main/java/net/rptools/maptool/client/ui/zone/ZoneRenderer.java#L1966

**Comment by kwvanderlinde** [comment]
Tested. The connection indicator shows the number of connected clients (including the one running the server). It typically shows the number of loaded clients as well, though the number can cycle a lot during loading. Interestingly, when I loaded a large campaign, it sometimes showed 0 loaded clients, even after the server client has already loaded. Very minor though, can be addressed separately if it turns out to be a real problem.

It's not clear to me whether the connection indicator gives the expected information in the context of this FR. It does _not_ show the number of clients on the _GM's map_, rather it shows the clients that have _their own current map_ loaded. But this seems good to me as not all games require players to be on the same map, and the **Connections** window can be used for more detailed information if needed.
