### ISSUE TITLE
[REQUEST] Better handling of national characters in macros

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#390]
**Is your feature request related to a problem? Please describe.**
When using national characters e.g. in text that should be outputted, either in a dialog/frame or in the chat, in a macro, it needs to be html encoded. E.g. the danish "æ" must be entered as &aelig; This makes it rather annoying/difficult to read or edit later on. 

The error shown is: line 1:61: expecting '"', found 'Ã'
 
**Describe the solution you'd like**
I would like MT to be able to handle text as proper unicode, especially when it is text that should be outputted for players to read. 
I realise that the issue may be related to whatever html parser MT is using, and thus not necessarily something that is easily fixed, but it would be much appreciated if something was done.

**Comment by Phergus** [comment]
Just for some more context this:
```
Tha mi a ’coiseachd an cù<br>
ßàáâãäåæçèéêëĀö
[dialog("Test"):{Tha mi a ’coiseachd an cù}]
[frame("Test2"):{Det er en mægtig smuk bil.}]
```
In a macro or entered into the chat window directly outputs as expected.

![Screenshot 2019-08-22 20 46 18](https://user-images.githubusercontent.com/34379254/63563350-08de7c00-c51e-11e9-87d9-41c8ac725519.png)

However, this:
`[r: output = "ßàáâãäåæçèéêëĀö"]`
Produces the error:
`line 1:11: unexpected char: 0xC3`
From the chat window or a macro.

@Tdue21  Is this your current findings as well?

**Comment by Azhrei** [comment]
It's been awhile, but if I remember correctly, the issue has to do with the current regard-based parser not being 8-bit clean.  This basically means that it won't accept multibyte characters so anything other than ASCII should use HTML entities instead of the raw character encodings (UTF-8, latin1, or whatever).  My understanding is that the next version of MTscript will have a true lexical tokenizer and parser and will be able to handle such things, but the current code can not be retrofitted in this regard.

#include <stddisclamer.h> // this is from memory, and from a long time ago...

**Comment by Phergus** [comment]
So close or defer to MT 2.0?

**Comment by Azhrei** [comment]
Um, close, I guess.  It’ll be fixed in the next MTscript (who knows which version of MT that will be?  Might be 2.0, but there’s some logic to putting it into 1.6 so that there’s not too much getting put into a single build).
