### ISSUE TITLE
Clean html tags from code completion list

### ISSUE THREAD

**Issue by Tdue21** [RPTools/maptool#391]
**Is your feature request related to a problem? Please describe.**
The list of code complete suggestions are not that big, it should scrub the html tags from the text that is shown. 
Reserve the html for the actual description popup.
This would make it easier in some cases to see the text in the list of suggestions. 

**Describe the solution you'd like**
No html tags in the suggestions list.

![image](https://user-images.githubusercontent.com/2953375/54979367-48229400-4fa3-11e9-8a56-6a8dec713041.png)

**Comment by Azhrei** [comment]
Yes, this is pretty easy to do.  I wasn’t aware it was going to display like that — I was expecting the HTML to be interpreted.  Maybe I just need to add “<html>“ at the front...

**Comment by thelsing** [comment]
Still an issue. @Azhrei do you still plan to work on this?

**Comment by Azhrei** [comment]
> Still an issue. @Azhrei do you still plan to work on this?

Not any time soon. The string being displayed there is the string used as the “tooltip” that shows the entire wiki page. If all HTML tags are removed, the wiki page content will then be unformatted. 😕

There may be a way to create a second string via the API but I didn’t see one when I looked.

if someone else wants to take a crack at it, they definitely should. If it turns out that the properties file needs a new field, I can tweak the Python scripts that generate it.

**Comment by emmebi** [comment]
@Azhrei I was looking into this; I can see that in [MapToolScriptAutoComplete](https://github.com/RPTools/maptool/blob/bf18f0e0aa27e545cb455ef1e67ab321b6014118/src/main/java/net/rptools/maptool/client/ui/syntax/MapToolScriptAutoComplete.java) we create `BasicCompletion` with a short description and a summary. Unless I am mistaken, the shortDesc is used in the suggestion list, and the summary for the actual description of the function. So, if we strip the tags from that, we should be ok. 

If that's the case, feel free to assign the issue to me, I have some code for this (even though I am struggling at writing some tests for it, TBH).

**Comment by Azhrei** [comment]
I'm assigning this one to you, then.

In an ideal world, you'd do the stripping once and cache it somewhere (which is why I suggested we could rebuild the properties file with an additional key rather than do the work at runtime).  Can the popup list simply be displayed as HTML instead of plain text?  That would solve the problem and the formatting in the short description would be visible...

**Comment by emmebi** [comment]
I gave a try in the above PR; unfortunately, I didn't find any way to use HTML in the summary, so I had to go for the strip/cache approach.
