### ISSUE TITLE
[Bug]: Tokens in the Default resources have opacity set to 0%

### ISSUE THREAD

**Issue by emmebi** [RPTools/maptool#3986]
### Describe the Bug

The tokens included in the Default resources have opacity set to 0%, thus they appear invisible when dropped on the map.

### To Reproduce

1. Click on Default -> Tokens from the Library 
2. Drag-an-drop the token of the Troll; it doesn't appear on the map
3. Double-click on the token
4. Check the Opacity from the Config tab

### Expected Behaviour

The token should have 100% opacity.

### MapTool Info

develop (right after 1.13.0-beta-2)

### Desktop

Windows 10

**Comment by Phergus** [comment]
This isn't a problem with the tokens but a problem with the recent changes for token opacity.  Many tokens out there won't have opacity saved in them included the default ones but the code is defaulting to 0%.

**Comment by kwvanderlinde** [comment]
I think we've dodged a bullet here.

The case of a missing opacity used to be handled by the getter `getTokenOpacity()`, where a 0 opacity (the default when missing) was overwritten with 1 instead. Because this check was in the getter instead of in `readResolve()`, there's technically three cases that could be present in existing rptok files:
1. rptok has no opacity field and should be treated as opaque.
2. rptok has an opacity field set to 0 and should be treated as opaque.
3. rptok has a non-zero opacity field that should be used as-is.

Case (2) would be problematic, since we would need a way to distinguish an old token that happens to have zero opacity vs a new token deliberately has zero opacity. The likelihood of this case should be low, though, as any rendering of the token should involve `getTokenOpacity()` which would have overwritten the zero value. So we can _probably_ ignore that case and only consider cases (1) and (3) for backwards compatibility. Which means we can take the easy way out, changing the field to a `Float` instead of a `float`, and handling the `null` case in `readResolve()`.

If we can't ignore case (2), then we have to get creative.

**Comment by Jmr3366** [comment]
Sorry about that and thank you.  I didn't realize the parameter wasn't in the rptok file (and now know to check).

**Comment by kwvanderlinde** [comment]
@emmebi Can you confirm whether you are still seeing this in any 1.13 release?

**Comment by emmebi** [comment]
@kwvanderlinde tested with 1.13.2; the tokens are added properly.

**Comment by kwvanderlinde** [comment]
Thanks @emmebi!
