### ISSUE TITLE
[Bug]: Audio and Sounds is broken.

### ISSUE THREAD

**Issue by PyromanticKing** [RPTools/maptool#4193]
### Describe the Bug

System sound, execFunction, execLink, playClips, and all other forms of audio does not come through. 

Maptools additionally doesn't show up in windows volume mixer.

### To Reproduce

1. Uninstall all previous versions of Maptools
2. Install Maptools
3. Attempt to receive an audio output

### Expected Behaviour

- The audio slider will produce no noise
- Maptools will not appear in windows volume mixer
- Playclips from discord, dropbox, or system files will not work
- Neither execFunction or execLink will produce sound or bring Maptools to volume mixer

### MapTool Info

1.12.2 to 1.13.1 was tested with the same result.

### Desktop

Windows

### Additional Context

==== MapTool Information ====
MapTool Version: 1.13.1
MapTool Home...: C:\Users\snipe\.maptool-rptools
MapTool Install: C:\Users\snipe\AppData\Local\MapTool\app
Max mem avail..: 3 GB
Max mem used...: 104 MB
Custom Property: -DMAPTOOL_LOGDIR=C:\Users\snipe\.maptool-rptools\logs
Custom Property: -DMAPTOOL_DATADIR=.maptool-rptools

==== Java Information ====
Java Home......: C:\Users\snipe\AppData\Local\MapTool\runtime
Java Vendor....: Eclipse Adoptium
Java Version...: 17.0.1
Java Parameters: 
  -Djpackage.app-version=1.0
  -Xss8M
  -Dsun.java2d.d3d=false
  -Dsentry.environment=Production
  -Dfile.encoding=UTF-8
  -Dpolyglot.engine.WarnInterpreterOnly=false
  -XX:+ShowCodeDetailsInExceptionMessages
  --add-opens=java.desktop/java.awt=ALL-UNNAMED
  --add-opens=java.desktop/java.awt.geom=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.geom=ALL-UNNAMED
  --add-opens=java.base/java.util=ALL-UNNAMED
  --add-opens=javafx.web/javafx.scene.web=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit=ALL-UNNAMED
  --add-opens=javafx.web/com.sun.webkit.dom=ALL-UNNAMED
  --add-opens=java.desktop/javax.swing=ALL-UNNAMED
  --add-opens=java.desktop/sun.awt.shell=ALL-UNNAMED
  --add-opens=java.desktop/com.sun.java.swing.plaf.windows=ALL-UNNAMED
  -Djpackage.app-path=C:\Users\snipe\AppData\Local\MapTool\MapTool.exe

==== OS Information ====
OS Name........: Windows 10
OS Version.....: 10.0
OS Architecture: amd64
Processor......: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
PATH...........: C:\Users\snipe\AppData\Local\MapTool;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\snipe\AppData\Local\Microsoft\WindowsApps;;C:\Users\snipe\AppData\Local\MapTool\app;.
Number of Procs: 16

==== User Information ====
User Name: snipe
User Home: C:\Users\snipe
User Dir.: C:\Users\snipe\AppData\Local\MapTool

==== Network Interfaces ====
Display Name..: Software Loopback Interface 1
Interface Name: lo
Address...: 127.0.0.1
Address...: 0:0:0:0:0:0:0:1

Display Name..: LogMeIn Hamachi Virtual Ethernet Adapter
Interface Name: eth2
Address...: 25.5.73.109
Address...: 2620:9b:0:0:0:0:1905:496d
Address...: fe80:0:0:0:e80e:443b:3d13:ab10%eth2

Display Name..: Intel(R) I211 Gigabit Network Connection
Interface Name: eth3
Address...: 192.168.0.13
Address...: 2001:48f8:7049:23f4:0:0:0:3
Address...: 2001:48f8:7049:23f4:20a4:1345:a446:8db3
Address...: fd00:1cab:c09c:6ed1:41db:9d80:8937:65fe
Address...: fd00:1cab:c09c:6ed2:deed:c5b1:8e1e:4eb1
Address...: 2001:48f8:7049:23f4:d03f:48d0:6565:efb
Address...: fd00:1cab:c09c:6ed1:d03f:48d0:6565:efb
Address...: fd00:1cab:c09c:6ed2:d03f:48d0:6565:efb
Address...: fe80:0:0:0:ff2:7f0:80c4:6541%eth3

Host Address...: 25.5.73.109
Default Gateway: 192.168.0.1

==== Locale Information ====
Country.: United States
Language: English
Locale..: English (United States)
Variant.: 

==== Encoding Information ====
Default Locale:   en_US
Default Charset:  UTF-8
file.encoding:    UTF-8
sun.jnu.encoding: Cp1252
Default Encoding: UTF8

==== Display Information ====
Number of Displays: 1
Display 1: 1360x768(32)

==== Internet Gateway Devices ====
	No IGDs Found!

**Comment by Azhrei** [comment]
Thanks for reporting this issue. We want things to work. 🙂

First, [this Q&A](https://superuser.com/questions/965681/windows-10-problems-applications-dont-show-in-volume-mixer) says Windows 10 doesn't list individual applications in the sound mixer (although Win10 Anniversary edition apparently puts it back in?).  Depending on which specific version of Windows you have, you may want to try the program suggested in that post as an alternative.

Also, I see you have Oracle Java installed.  Do you have applications that require it?

If not, try uninstalling Oracle Java and then make sure that there are no leftover entries in your PATH environment variable.  Reboot your machine (it's the only way for users to easily clear DLLs from memory) and open MapTool.  I mention that because your existing PATH looks a little messy.  It has MapTool listed first (which is good), but then a different MapTool directory is listed last as well (which is strange?!).

It's also possible there's an interaction between your sound drivers and Java.  You can try using Craig's [1.14.0-alpha.1 of MapTool](https://github.com/cwisniew/maptool/releases/tag/1.14.0-alpha.1) from his fork of the release code.  Please install it into a different directory than where you have installed MapTool now (most people will use a name like **MapTool-1.14.0-alpha.1** or similar) in order to keep them separate.  (Yes, you can install multiple copies of MapTool as long as you use different directories.)  Then reboot before trying the test from Discord again (the `playClip()` example) in v1.14 (in order to clear all DLLs).  The 1.14 alpha code has updated Java 17 to Java 20, and JavaFX 17 to JavaFX 20.  (If you'll report which sound drivers you're using, maybe a web search can determine if Java has any compatibility issues with those drivers.  If you don't know which sound drivers you have, and don't know how to check them, don't worry about it.  However, if you're curious, [this MS page](https://answers.microsoft.com/en-us/windows/forum/all/no-applications-in-volume-mixer/74fa0fbb-b8ee-448d-a798-5f5fa1bed046) on how to troubleshoot audio problems might be helpful.)

I'm not familiar with the code in MapTool that does audio processing; maybe there's some debugging feature that can be turned on to add additional logging...?  Someone familiar with that code would need to chime in, though.

**Comment by Phergus** [comment]
Azhrei has most likely nailed it.  With Oracle Java installed you've probably lost access to JavaFX media functions which is how MT plays music.  He's also correct that your path is a bit of a mess.

MapTool does show up in the stock Windows sound mixer for both 1.12.2 and 1.13.x as well as previous versions.
![image](https://github.com/RPTools/maptool/assets/34379254/72b54417-a53a-4ba1-9674-488886f73c25)

**Comment by Jmr3366** [comment]
It was posted on the forums the issue has been resolved as it appeared to be a client side problem (so this is a "false positive" and should be closed)
