### ISSUE TITLE
[Feature]: Reference tokens to act as sheets

### ISSUE THREAD

**Issue by StefanoMarina** [RPTools/maptool#4219]
### Describe the Problem

As of now, token are strictly bound to their properties. In game terms, a token **equals** to a character/npc sheet. When handling multiple maps, things are bound to happen - tokens get canceled by mistake, something goes wrong in cutting and pasting tokens from a map to another, etc. 

You can always save your tokens to a file, but that's really impractical especially when playing live.

### The Solution you'd like

Just like libraries and images, you have a token you can access everywhere, maybe with a prefix like `token:` or something. 
When you draw a token on the map from the library and open the properties editor, you get a combo box near pc / npc that allows you to select a `token:` reference token. From that moment, the new token becomes a *pointer* to the reference token, and  *any* changes to the pointer token are applied to the original token and any other pointer token with the same reference.
This way, the sheet tokens are safe somewhere, untouched by users (much like library tokens), and losing or corrupting a pointer token does not damage the original token.

**Comment by Ahnoold** [comment]
This can almost be accomplished already. Let's say there's a token called "PC", and another token called "PC-Ref" on a map called "Reference Map". The values for all of the token's properties are defined/recorded on PC-Ref. The properties on PC all contain the following formula: {getProperty("Property", findToken("PC-Ref", "Reference Map"), "Reference Map")} where "Property" is changed to the name of each property. When playing, I had the "Lock Player Token Editor" option checked, so players could only edit token properties via macros. I wrote macros to modify properties on PC-Ref rather than on PC itself.

There was one problem I ran into that kept me from continuing to use this. On the players' clients (but not on the GM client), the values in the stat sheet that pops up in the lower left corner displayed the formulas rather than the values calculated by the formulas.

I would also like to see this feature implemented, as it would solve the stat sheet display issue, allow games to be run with the player token editor unlocked, and simplify macro writing.

**Comment by FullBleed** [comment]
> As of now, token are strictly bound to their properties. In game terms, a token **equals** to a character/npc sheet. When handling multiple maps, things are bound to happen - tokens get canceled by mistake, something goes wrong in cutting and pasting tokens from a map to another, etc.

For many years I've used a system where character tokens can have a single property on them called "Library" that is the pointer to a library token with all of the Character's actual information.  The Library token itself is never messed with so none of the things you describe can go wrong with it.

So, for example, the value of that "Library" property would be "Lib:John".

And on my "Library" map (where I keep all the Library tokens in my framework) I have a "ghost token" of the character called "Lib:John".  And that's the token where I keep all of the token's actual properties/data that I want to consistent throughout the campaign.

And any time I want to pull a property (like Hit Points) from any "John" token on any map in the campaign I would use something like: 

[h: libraryProp = getProperty("Library", tokenID)]
[h: hitPoints = getLibProperty("HitPoints", libraryProp)]

**Comment by StefanoMarina** [comment]
Hello,
I'm sorry but what I'm requesting is different from issue #208.  in my idea data is **still bound to a token** , what changes it's the token context when setting/getting properties, everything but coordinates and collisions basically.  

I see this as an improvement over the current `Lib:` token technology,  

I'm not thinking about static data, but more similar to @FullBleed 's answer - a token referencing another token for anything but it's coordinates and any collision feature. it's more like *switch token context automatically to token X when using properties, token Y when using collision or movement*. and syncing status/bars/orientation/picture.

It may be as well a synchronization - when tokens refer to a single pointer, everytime a token is changed, change all the others.

The main difference, again, is the scope: I'm proposing a different way of toying with the current data model, not to change it to the core. Of course having global sheet data and referencing to it instead of this would be neat, but as a programmer myself I see how it could be as a giant issue in  a community project, and since the issue is from 2018 and in 2023 there is no progress, I'd say maybe too big for now.
