### ISSUE TITLE
[Feature]: Add Genesys / FFG Starwars dice roller

### ISSUE THREAD

**Issue by cwisniew** [RPTools/maptool#4303]
### Describe the Problem

The Narrative dice system used by FFG Starwars and many other Genesys games are not supported by MapTool and should be.	

### The Solution you'd like

Support the dice rollers above.

### Alternatives that you've considered.

People have made macros to do these dice, but they are complicated.

**Comment by kwvanderlinde** [comment]
Took this for a spin. As far as I can tell, results align with expectations, though an expert in the system would be better equipped to decide that. I also did not try out every possibility yet.

The PR claims that `gs.lastRoll.light` and `gs.lastRoll.dark` are not set when using `gs!` rolls. But I found these variables are set the just return 0. Otherwise the variables seem to be aligning with expectations, including that `sw.*` are only set when rolling with `sw!`, and `gs.*` are only set when rolling with `gs!`.
