### ISSUE TITLE
"Well that Got Toxic Quick"

### ISSUE THREAD

**Issue by Lovewyrm** [RPTools/maptool#566]
And we must be professional and all that?

In regards to:
https://github.com/RPTools/maptool/issues/543

Where I was, admittedly, mostly a frustrated 'dumb' end user, but a certain blue genie, an "academic" and "enterprise customer pleaser, led me around by the leash, demanding that I could only make a case against Java if I delivered bullet point lists of flaws and shortcomings that would be unmistakable proof that Java creates more problems (and in my initial argument was mostly aimed at end users for having to deal with JREs and so forth).

All smug and smarmy. Shamelessly exploiting my ignorance, my layman level of Java (and one doesn't need to be a chef to not like a dish, mind you) to dismiss my concerns and letting me stew in my frustration.
To make himself and the language selection of choice look more grand.

Which is not exactly nice on its own, but then I also realized in bed that..hey.
That "other" program than the gurps character charsheet that is also written in Java, that had me have to use TWO different versions of Java, which was an intense PITA.
Was Maptool!

Because Maptool is lagging behind the Java release curve!

WHILE THAT SMUG BLUE BASTARD IS GRILLING MY RIGHTFULLY FRUSTRATED LAYMAN ASS EXTOLLING THE VIRTUES OF JAVA AND GLORIFYING HIMSELF AS AN ACADEMIC AND PLEASING ENTERPRISE CUSTOMERS.

Well, then, Genie(us) of Blue.
You...who apparently are NOT the toxic one for this RAT BASTARD of a move. Dimissing me as some sort of bumbling yokel because I couldn't satisfying some arbitary gauntlet of bullet points of your PERFECT baby of a language.

WHY, and I want a bullet list of intricate detail.
Are you not taking advantage of the bounties of AWESOME IMPROVEMENTS Java offers in its NEWER iterations, even thought Java solves more problems than it creates?
Both for end user and developers?

Getting toxic quick.
Now, bro, you and the other guy, you're alright, you know. You know, Jamz and Phergus, you're good in my book.
Jamz, you're a total workhorse and have all the right to defend Java, you also weren't a smug bastard a single time. And you're also a good colleague and I'm not mad at you at all that you had to lock the previous issue.
Phergus seemed to just have to want to get over with things, like "Screw this, I'm out" after what, one comment, and then closing the issue, fair enough.

But Mr Blueberry? Azhrei? 
Buddy.
Screw yourself. The moment you have delivered the bullet point list that describes  why y'all are not using the latest and greatest of Java, in technical detail that would satisfy a professional academic in the enterprise environment.
Never talk to me again. Even in passing.

**Comment by cwisniew** [comment]
Honestly it's not beholden of anyone here to defend why we should not change to the language you prefer, but if you need justification

1. There is a large amount of code that already works well, could it be better sure things could always be better, but the choice of language is not the problem here. There is a huge downside to changing to another language.
2. There are several contributors who are comfortable with Java what benefit do we get from losing those contributors?
3. You assumptions about performance are not well informed and we would gain no real benefit here.
4. We would just be trading one set of problems we are either working with or have worked around for a completely new set based on the new language while starting from scratch.

Point 1 should be both immediately obvious and justification enough.


As for your behavior @Lovewyrm, I wonder what contributions you have made to any of the RPTools suite that qualify you to look down on the quantity of contributions that others have made, and what insight you have into non coding contributions that a person has made might be...

Actually let me restate that for the benefit of everyone reading this. Even if you had made contributions no amount would make it acceptable for you to look down on the amount of contributions others have made or carry on like you have. We happily accept and encourage people who want to contribute either a little or a lot to do so. 

What we are not so happy to either accept or encourage is the kind of behaviour that you are displaying here. You don't like java that's fine it's your prerogative but it's no reason to resort to name calling and the attitude exhibited in your posts. Really the closing of the previous issue and comment on closing should have been enough of a wake up call for you. Please either refrain from such behaviour when dealing with the RPTools team or community in the future or refrain from dealing with us at all.

**Comment by Lovewyrm** [comment]
My behavior is impeccable and completely warranted, and I nailed all of my core complaints with absolute accuracy, my technical ignorance notwithstanding, however.

I accurately assessed Java as a pain in the ass. The fact that Maptool lags behind the release curve because the framework, the very fabric the program is made up from, breaks it and substantial refactoring would be required to port it over. So much for easier.

My assessment about Azhrei was also impeccable and accurate. I called him a smug and smarmy energy vampire bully, and that is exactly what he is, as outlined by my "namecalling".

My only regret about the whole deal is the accusations of my words being toxic, since I don't actually have the ability to cause poisoning in Azhrei, an ability I would very much welcome in my repertoire.

But yeah, again, everything important about my conduct has been stated by me.
There is absolutely no need for a wakeup call for me. I am quite awake.
I will never refrain from harassing and calling out scumsucking shitwhistles like Azhrei that waste everyones time.

Hence the energy vampirism. He made a big blustering display about nothing.
Java is shit, it is actively impairing your project at the moment and fouls the computers of the users by shipping the runtime it has to cling to.

Anyway, that said. I will be awaiting the bullet list with bated breath.
Justkidding, I know it's not gonna happen, because I correctly assessed the nature of such a demand, too.
Like pulling teeth and nobody wants to jump around a flutesong like that.

That said, my ongoing loathing of that smarmy bastard is purely due to his conduct, not the language, which, granted, remains trapped in a cyst of BS, but bad code can be fixed.

Smiling snake in the grass energy vampires like Azhrei, can not, not if his sardonic smiling "polite" conduct (which was actually full of blustering shit) emerged this quickly.

I am not polite, no, not anymore, but I am also not an Azhrei. A fact I cherish deeply and thoroughly.
I can be polite.
Can Azhrei be not an Azhrei?

**Comment by JamzTheMan** [comment]
Sigh. We get it you don't like Java, that's fine. And you hate one of the founding members. But this has to stop. Spamming GitHub issues with your hatred and language is not winning you any points.

We have a clearly defined [Code of Conduct]( https://github.com/RPTools/maptool/blob/master/CODE_OF_CONDUCT.md) which you are violating. If you insist using profanity and toxic speech targeting this community, I will report this. This is your last warning.


Regarding the project, I could counter several points regarding Java, share our road map and future plans, why some choices were made and what we plan on doing about said choices, but you clearly have your mind set on Not Java, which is fine. Everyone is free to fork (or not) to do anything short of commercialize off of the 14+ years of work past contributors have done to maintain a free VTT for the community to use.

**Comment by Merudo** [comment]
A wise man once told me, "don't feed the trolls".
