### ISSUE TITLE
License Update and Conflicts?

### ISSUE THREAD

**Issue by joshsziegler** [RPTools/maptool#59]
1. The following looks like it needs to be filled out: https://github.com/RPTools/maptool/blob/master/doc/LICENSE#L30
2. The LICENSE talks about using the GPL moving forward (along with the LGPL), but shows the AGPL. If we are using the AGPL, we should probably fix the references to the GPL (for example: https://github.com/RPTools/maptool/blob/master/doc/LICENSE#L7 )

**Comment by Azhrei** [comment]
Hm.  The vagueness here is my fault. :(

The Apache License shown in the file is an *example* of what the Apache License looks like.  The paragraph/sentence immediately above it says that the individual readme files (for each 3rd party library) should be consulted for the actual copyright owner; this file is merely an overview of how the license has changed and is not a license file in itself.  In fact, the example Apache License should probably be removed entirely and the references to the readme files of each library should be more ... explicit.

You are correct that references to "GPL" should be changed to "GNU AGPL", since there is (apparently) another license -- separate from the GNU license -- which goes by the same name.  This is explained further at the linked page, but either way this overview should be updated.

I will clean this up and submit a patch.  After it's been discussed (if necessary), I or Craig will merge it.  I don't have NetBeans fully configured on this laptop yet, but I'll work on it tomorrow.

(This brings up another issue, but I'll open a separate ticket for that.)

**Comment by joshsziegler** [comment]
That makes sense.

While you're making changes to the license files, it might be a good idea to add a license section to the root's README. Maybe include the updated history and then link to each full license file?

**Comment by JamzTheMan** [comment]
Hey AZ, in the 1.4.1.0 branch there is a spotless.license.java in the root project. If you want, you can add the default license text there as well and spotless can update all the Java class headers with it. I commented it out in the gradle build for now until that is ready.

**Comment by JamzTheMan** [comment]
Master branch license is updated and spotless is updating headers
