### ISSUE TITLE
Expected Behavior: PC vs NPC?

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#655]
**Describe your question**
What are the expected differences for a PC vs NPC token?

Should PC/NPC have any effect beside Vision & FoW?

Should an owned NPC token reveal FoW? What about an unowned PC token in non-iFoW view?

**Comment by dorpond** [comment]
A little history: 

Back in the day, things were simpler; PC’s were player owned tokens that could “see things”, and NPC’s were only for the DM. There was no need for a DM to see things because the DM already sees the whole map and is “all knowing” anyway.

My mind is a bit fuzzy on specifics since this was a heated discussion long ago, but I think it went like this: 

Others insisted that NPC’s should work the same way as PC’s because players may control an NPC at times. They argued that ownership should determine who should have control over the token, not the NPC/PC switch, and that the NPC/PC switch should be more of a label on what the token is. 

Some argued (including me) and said “if you want to control an NPC, then just change that it to a PC then”, but that logic was shot down by counter logic, and in the end the code was changed to give NPC’s the same/similar abilities as PC’s 

Some battles are worth fighting and others are not; It didn’t effect me, because I don’t autoexpose, nor use iFOW, plus I don’t turn on ‘has vision’ for NPC tokens, so when I expose FOW, I still only do so on the PC’s I select, and if a player wants to control an NPC for a session, I still just change that token to a PC, even if I don’t have to, because in my simplified mind, NPC’s are still DM owned tokens, not players.

But your question will open a passionate can of worms amongst the viewing audience, so be prepared! Lol 

So you ask you how it should work? Honestly, I don’t know anymore because everyone uses MT differently. This will be an interesting discussion to watch.

**Comment by JamzTheMan** [comment]
I had planned to add a new server option to control if npc token auto reveals FoW so it can be turned off, apparently it really bothers some people. :)

Whether a player or a GM controls the NPC is a mute point. As a GM I prefer my NPC token to have the same vision/FoW/history just like a PC token so that I can make informed decisions on what a NPC token can see.

**Comment by Merudo** [comment]
@JamzTheMan, I have a question for you. If PCs & NPCs have the same vision mechanics, why distinguish between PCs and NPCs at all?

**Comment by dorpond** [comment]
I don’t think it bothers people now, as it did at the time. The nice thing is that the changes made allows a GM to use MT in a whole new way, without really messing up the people who wish to still use it their way.
 
That’s a win in my eyes.

**Comment by JamzTheMan** [comment]
Seems like a loaded question. :)  (Why in the context of MapTool code or why in the context of using MapTool?)

I'll start off with saying, I think it's an antiquated system and should be removed in favor of a more fluid/encompassing system as MapTool can be used for more than traditional RPG's that may not need these designations or could use more designations. I proposed a new Tag system that could replace States along with other "flags" like NPC/PC which could then be used to control various systems within MapTool.

If you want to elaborate on the question, honestly, not sure if your "why" means just for vision or more broadly.

In my framework, I use the designation of PC/NPC for other things like how Death is handled and XP is awarded. I have macros that cycle through PC tokens only.  I roll init for NPC but prompt for PC tokens. In Pathfinder, a Summoner may have a Eidolon which is with him all the time. I designate that as a NPC (mainly so it's not awarded XP but for other reasons). But that Eidolon needs to reveal vision just like a PC token would. On the flip side, lets say I have a horse, I need it to have vision so the player can move it around the map in the darkness (but not into darkness) because a PC is riding it. But, unless the rider can speak with animal, the player shouldn't be able to see what the horse can see really #metagaming. (Hence the buttons that can show PC FoW vs NPC FoW vs All token FoW)

As @dorpond said, I felt that it does give more flexibility to how you use MapTool and not less.

**Comment by Merudo** [comment]
Thanks for the answer, @JamzTheMan.

I would tentatively summarize it this way: the PC/NPC tag should not have any built-in Maptool effects, but can be used for the GM's convenience.

Is that what you are saying?

**Comment by Phergus** [comment]
@dorpond 
> @JamzTheMan, I don’t think it bothers people now, as it did at the time.
Actually it does that's why there is an open issue on it and a thread in the forum.

All the way thru 1.4.0.5, NPC tokens with vision did not expose FoW but still allowed GMs to have vision enabled so that they could see what the NPC could see.

**Comment by dorpond** [comment]
@Phergus 

I get it, man, in my simplistic approach of MT, NPC means GM, and I don’t know why I would want that to be able to oppose FOW as an NPC, but now with individual views as well as individual FOW, maybe some DM’s wish to keep track of where their NPC’s are going and where they have been, in a place they've never been? *Shrug*

I’m trying to keep an open mind here. Every user has their own style of game play when using MT.

If we can support all modes of play, without completely confusing the heck out of the user, then there is no fight from me.

**Comment by rkathey** [comment]
> I had planned to add a new server option to control if npc token auto reveals FoW so it can be turned off, apparently it really bothers some people. :)

Seems like a good plan.

**Comment by JamzTheMan** [comment]
I think the best summary is that PC/NPC designations really should not be locked into a strict definition of rules within MapTool (be it how they move, see, interact, etc). By stating "all NPC tokens should do xyz" you immediately lock in a viewpoint.

But for the short term, we can add the server option, that should allow people to use MT "as it was in <1.4.0.5" (while at the same time fixing a certain bug I introduced)

In the long term, I think we should remove such terms. (FYI my plan with tags was to create some "default" tags that would ship with MT, so PC, NPC, Ally, etc may ship by default but also would store with the campaign/framework so they could be expanded/removed/etc)

**Comment by Phergus** [comment]
> I get it, man, in my simplistic approach of MT, NPC means GM, and I don’t know why I would want that to be able to expose FOW as an NPC, but now with individual views as well as individual FOW, maybe some DM’s wish to keep track of where their NPC’s are going and where they have been, in a place they've never been? _Shrug_
> 
I'm sure that with IV and IFoW there are scenarios where having the GM tokens expose make sense but probably as you say where it is used not as vision (what can they see) but instead is tracking where have they been.

By and large the vision/FoW system was meant to be used for depicting what the _player_ controlled tokens can see and have seen.  However, it is important, for a lot of GMs, to be able to see (not expose) the vision limits of the GM controlled tokens opposing the players to avoid "cheating" and the only way to do that is if those tokens have vision enabled.

@JamzTheMan comments above outline the best plan going forward for me.

**Comment by dorpond** [comment]
The way @Phergus outlines it is the way I’ve always seen MT also. 

But I also see your side too @Jamz, so as @rkathey stated, “that setting seems like a good plan” (to the server setting). 

I do cringe though that by adding more server settings means even more modes of play to test. I can’t keep up with all those setting anymore. :p

Anyone else I can @ tag? Lol.
