### ISSUE TITLE
Add 'Ignore Terrain' to a Token

### ISSUE THREAD

**Issue by rkathey** [RPTools/maptool#728]
**Is your feature request related to a problem? Please describe.**
With the new terrain feature, there is no way to tell MapTool to ignore the movement penalty for a token when passing over a terrain modifier token.

**Describe the solution you'd like**
Add a checkbox (or other control) to the edit token panel->config tab as well as macros to turn on and off terrain modifier considerations on token movement.

**Describe alternatives you've considered**
None.

**Additional context**
This could affect #634 and #459

**Comment by dorpond** [comment]
Great idea, since there are classes, features, and spells, which allow passing through such things. 

The right mouse button token menu is getting large as it is though; is it best to have it there, or in token properties? 

How often would you be turning on and off such a feature for the token? I suppose it all comes down to whether it is an always on feature or a temporary one. 

But even so, vision is in token properties, and when someone suddenly gains darkvision for example, we go there to change it. (Just curious, can it be changed via macro?)

Hmmm, I just fear the right mouse menu getting unwieldy; in the early days, Trevor and I always tried to kept that me I’ll I as clean as possible - we wanted token menus to be simple and easy to find stuff. If you were to ask me, it is already too unwieldy as it is. Sometimes it takes me forever in a day to find what I am looking for during session, or I accidentally click the wrong one (like that one that always makes tokens visible).

I love the idea though - we certainly want an override switch for certain classes, features or spells. (Thinking druids and rangers)

**Comment by JamzTheMan** [comment]
I think a quick hit right now would be to add a button to turn off all terrain mod tokens next to the AI button. That way you can still use AI if you want for movement. Should be easy to do.

Longer term, how about this:

In campaign properties we add a new tab Tags (can be the start of new advanced states option)

You create tags of a type terrain mod with a value and a Affects list of tags (with a system defat tag of All)

On tokens, you add tags to one of 3 columns, Ignore, Affected, Have?

Ok those are terrible names but basically either you ignore other tokens with tag x, always affected by tag x, or you have tag x.

Now you set up your tokens. Giving tokens various tags like Ice, Rocks, Ooze, Clouds (this one doesn't have an All tag but instead a Fly tag)

Now PC with Boots of winter, they get to put Ice tag under ignore.
PC with Freedom of Movement, he gets to add all 3 to ignore.
PC that is flying? Well he gets to add Ice and Rocks to Ignore but is affected by Clouds because he has the Fly tag.

This is why I haven't done terrain fully yet because I'd like to do it right.

As you can see, Tags could be very useful elsewhere as a token filter system. Instead of terrain mod value, tags could start have other mods as well like Can See and Range, then you can start to add a full Invisibility vs See Invisibility vs Invisibility Purge.

Add some other mods like Remove, Add, Suppress, Temp (opposite of Suppress?) So tokens with these tags affect other tokens with range with certain tags.

Anyhow, we could start with Terrain Mod but I'd like it to have a strong foundation to take on and replace States. (Yes, give tags the ability to add image to token just like States and you then replace states once implemented)

**Comment by rkathey** [comment]
I'm not a huge fan of disabling the AI for everything so one token can move. I guess you would have to check states, spells, effect, etc. in an onTokenMove and disable AI for the duration of the move then turn it back on again once the token was released.

I'd rather set it on the Token-based on character sheet interaction or other factors and have it ignore AI from there. But, I see your argument for doing it right the first time.

**Comment by JamzTheMan** [comment]
Yes, because as soon as you add the ability to turn terrain mod on/off for a token, the next request is to do it for "some tokens". And then it's "turn off for difficult terrain but not greater difficult terrain"

Adding the button at the top would let you temp turn it off at least and you can go old school and do what you use to do (manual effort).

Now, adding the terrain mod to lastPath will also help and you can use all the custom logic you want using properties and such.  And a toggleTerrainMod(1|0, [tokenId|gm|all]) could be useful as well to just toggle a global ignore of terrain mods for that token, for the GM, or for all tokens (which would toggle the TM button on/off)

**Comment by Phergus** [comment]
So a two-step initial approach for now and then a more advanced tags system for 2.0?

MT 1.5.*
1. Add TM toggle button - affects all tokens on that client
2. A `toggleTerrainMod(1|0, [tokenId|gm|all])` function. 

Or maybe setIgnoreTerrainMod and a corresponding getIgnoreTerrainMod?

MT 2.0 -> tags system

**Comment by JamzTheMan** [comment]
Ya, probably but tags doesn't necessarily depend on a version, its just a larger story.

And ya, get/set method names are probably better.

**Comment by Azhrei** [comment]
> 1. Add TM toggle button - affects all tokens on that client

Keep in mind that the network communication with the server will need to change.

Right now, when you drag a token, the mouse coordinates are sent to the server and relayed to the other clients.  Since they haven't turned off their toggle button, those other systems will continue to route the token the old way.  The GM will therefore see a route different than what the Player sees.

Either the toggle button needs to become part of the data packet or the server needs to keep track of the state of the buttons on each client.  The former seems much more manageable, at lest in the short term.

I don't remember if the server is sent a "start drag" packet; if so, the state of the toggle button can be put there and the increase in network traffic would be negligible.  It also means that all rendering functions will need to query that state on a per-token basis (can't just use the global state of the current client from AppPreferences, for example).

This is likely to touch a lot of code.  Of course, the new field added to Token can be `transient` so it won't change the XML in the exported object.  That's one saving grace, at least.

**Comment by JamzTheMan** [comment]
Hmmm... I probably didn't take that into account for the AI button, it's client only. Is that what is happening today? Player sees a direct route but the GM sees the A* path? (not at home so can't test)

**Comment by Phergus** [comment]
Actually, apparently you did?  Sort of.

If I turn off AI on the server, the player movement acts as if AI is off.  Can drag right through VBL.

Turn it on for the Server and off for the Player and same thing **but** on the other player clients with AI enabled, the movement stops at the VBL.

Weirder is that turning it off on Player 2 causes Player 1 movement to not use AI even though it looks that way on Player 2!

**Comment by JamzTheMan** [comment]
oh oh, may have a bug there... I toyed with make it a GM only button and disable it for players, so when the GM toggled it, it toggled it for all clients.  Perhaps that is what we should do for both buttons?

Because really, the GM should have final say if a player can "ignore" vbl and terrain or not...

**Comment by Phergus** [comment]
Yeah.  I would think GM should have control over this.

Which then suggests that any macro functions for toggling this be protected functions.

**Comment by JamzTheMan** [comment]
Absolutely.

I originally didn't make it GM only to make sure people didn't freak out because their token moved all funky now.

But seems like the burn in is ok and it's working ok for the most part.

**Comment by Phergus** [comment]
And folks can always use waypoints to move in exactly the path they want to use.

**Comment by Phergus** [comment]
Reminder - Capture discussion of AI buttons and move to a new issue.

**Comment by Phergus** [comment]
PR #1068 implements terrain modifier types and adds the ability for tokens to ignore those types.  Tested.  Appears to meet the requirements of the request.
