### ISSUE TITLE
Stale connections on server when client loses connection

### ISSUE THREAD

**Issue by mechalas** [RPTools/maptool#774]
In MapTool 1.5.5, when a client connection drops (rather than gracefully disconnects) their session on the server persists. This prevents the same player from reconnecting, and they get the error "Someone else is using that user name." The client session must be manually booted from the server.

The player having this issue is using the Linux client. The issue can be reproduced if they suspend the system while connected to the server. Previously when the system was resumed their client would reconnect with no issues, but since upgrading to 1.5.5 they get the above error, and restarting the client does not clear it. They also note that 'netstat' shows no connections to the server port, so this does appear to be a bug on the server side.

The server in this case is running on Ubuntu 16.04.4 LTS. In case it matters, connections are direct via IP address.

**Comment by Azhrei** [comment]
There's likely nothing we can do about it short-term.

One option would be to turn on Keep Alive packets so that the server's network stack shuts down the TCP session sooner, but then a few dropped packets and players are disconnected when they shouldn't be.  We've always considered it better to require the GM to "boot" the player than to disconnect prematurely.  (Keep alive packets don't make it to the application layer, but we could implement our own keep alive pings in the application and then provide a Preference setting that says how many missed pings are allowed before the player is dropped.  But what are you going to set the timeout to?  Ten seconds?  Twenty seconds?  Your player is still going to wait that time before they can reconnect, so isn't an immediate boot by the GM quicker?)

You might be better off determining why the player disconnects so frequently in the first place.  Are they dropping a lot of packets?  Are the packets sent but never arrive?  Why isn't TCP's guarantee of delivery being met?  Those are questions that a novice/layman will likely have difficulty answering, unfortunately.  (Heck, I'd have a hard time with it and I mostly know what I'm doing.  Mostly.)

**Comment by mechalas** [comment]
> Are they dropping a lot of packets? Are the packets sent but never arrive? Why isn't TCP's guarantee of delivery being met? Those are questions that a novice/layman will likely have difficulty answering, unfortunately.

Good news! Neither of us are laymen. But, per the but report, the trigger is that the Linux system running the client is being suspended/put to sleep while the client is still active. So the server is probably ending up with a half-open connection.

MapTool in this case is being used to manage the maps for a PbP game, so these aren't real-time game sessions. I recognize that is not the typical usage model, though it is interesting that the 1.5.4 server did not exhibit this behavior while 1.5.5 does.

**Comment by mechalas** [comment]
A couple of things that come to mind here:

1. Previously, MapTool may have been explicitly closing the connection when the system was suspended. Are there power event hooks in MapTool or the underlying framework?

2. The half-open connection behavior may have been there all along, but the perhaps server used to allow the client from the same IP to connect as the same user.

**Comment by Phergus** [comment]
1) Nope.
2) Nope.

AFAIK, Windows clients have never reconnected after having "slept".  Within a minute or so of the Windows client going to sleep the server reports that the client has disconnected.  The client reports the same thing once it comes back up from sleep and a new connection must be made.

**Comment by Azhrei** [comment]
@mechalas No, the client doesn't do any special TCP handling when going to sleep.  Whether the OS does (either the core kernel or the drivers themselves), I can't speak to, although I don't believe they do.  (Because if you open the laptop within a reasonably short period of time, the connection is still alive.)

There were nothing related to networking that I can think of that changed from 154 to 155.  Did anything else change between client and server?  Maybe a firmware update on a router so that the router killed the connection differently (earlier, for example)?  Were there any OS updates between the switch from 154 to 155?  Have you gone back to 154 to ensure that 154 still operates the way you remember?  (It's possible something else changed and going back to 154 might indicate that if it operates the same way as 155 in your current environment.)

There are no "power event" hooks in MapTool, although I suppose there may be some in the JVM?  I'm trying to think of anything like that, but nothing comes to mind.  (I'm not sure there are any application-level hooks into the NetworkInterface classes at all.  Just because an application can't access them, doesn't mean the JVM isn't using them.  I'll have to Google this.)

If the server held the port open for that client, a new session request from the client _could_ work — it would simply create a new session.  But then the player would get an error because their name was already in use at the MapTool (i.e. application) layer.

Or maybe this is all overthinking the problem.  When the laptop goes to sleep, the network card powers down.  This means a wired connection causes the router to notice the disconnect and the router may forward that information along automatically.  Even in wireless cards, there may be a last packet sent to the router that the router could use to notify the other end.  (The router is keeping track of connections that run through it, so it could know the IP address of the other end.)

Since nothing has changed in MT and since we haven't changed the version of Java being used, I'd be inclined to check other potential sources first...

**Comment by mechalas** [comment]
OK. I think the best thing to do at this point is run tcpdump on the server end and see if I can find any clues in the traffic between it and the player experiencing the issue.

**Comment by Azhrei** [comment]
Sounds good.  If you don't find anything, you're welcome to attach the pcap file here...
