### ISSUE TITLE
Player Clients show the last loaded Campaign Name in Title Bar when connected to server

### ISSUE THREAD

**Issue by Phergus** [RPTools/maptool#788]
**Describe the bug**
The title bar of a Player Client keeps the name of the currently loaded campaign file when connecting to a server.  When disconnecting from the server the player client then prompts to save the current campaign and clicking on Yes will overwrite the previously loaded campaign with an empty one.

**To Reproduce**
1. Start two MapTool instances.
2. Load a different campaign file in each. (Have backups.)
3. Start server on one instance and then connect with the second.
4. Note that both instances show the previously loaded campaigns for the particular client.
5. Disconnect with second client.
6. Close second client through File menu or close gadget.
7. User is prompted to Save campaign file.  Clicking on Yes overwrites the existing campaign file with an empty campaign.

**Expected behavior**
1. Player clients should show the Campaign Name of the server when connected.
2. Player clients upon disconnect should revert to Default campaign.
3. Save dialog should probably show campaign name.

**Screenshots**
Server and Player clients connected
![Screenshot 2019-10-10 10 32 13](https://user-images.githubusercontent.com/34379254/66590654-7c7c2d00-eb4e-11e9-9de9-db6da45e6cfb.png)
Player client upon shutdown.
![Screenshot 2019-10-10 10 33 40](https://user-images.githubusercontent.com/34379254/66590667-83a33b00-eb4e-11e9-8379-b1e3553b1aa1.png)

**MapTool Info**
- Version: Probably all but at tested with 1.4.0.5 & 1.5.6
- Install: Any

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by Merudo** [comment]
The problem is that the title name is obtained from the `campaignFile` instead of from the `campaign` itself.

Since the campaign file is not sent to clients, they see the file name from their own `campaignFile`.

**Comment by Azhrei** [comment]
That should be easy to fix, right?  We add the filename to the `campaign` object as a transient field after the campaign is loaded.  Because it’s transient, it’s not written to the output file (and thus maintains compatibility), but it _will_ be sent to the client for display purposes...

Anyone see any issues with that?

**Comment by Merudo** [comment]
It's a little tricky because the host can save the campaign file as another name. This doesn't change the campaign itself but changes the title. But I think I got the details almost nailed down. 

Also I noticed a bug, if you export a campaign and don't put the extension, the displayed name in the title is truncated.

**Comment by Merudo** [comment]
PR #827 fixes the reported bug.

**Comment by Phergus** [comment]
Tested and working as expected.
