### ISSUE TITLE
TokenID and Map Name parameter added to getTokenStates  macro

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#801]
**Is your feature request related to a problem? Please describe.**
Often I'd like to see the list of all enabled states on a token.

Sadly the only way to do it is to use `getTokenStates`, iterate through the whole list and add those that are enabled to the list.

**Describe the solution you'd like**
A function `getAllStates` that returns a list / json array with the names of the enabled states.

**Comment by cwisniew** [comment]
If the function is only returning the enabled states then it should be named something more appropriate then getAllStates, that implies all states regardless of if they are on or off will be returned.

**Comment by Phergus** [comment]
Perhaps just adding a Token Name/ID parameter to getTokenStates would be the right way.  Or change this to getActiveStates or getCurrentStates.

**Comment by JamzTheMan** [comment]
I really like Phergus's idea on adding a token ID parm to getTokenStates. I always lean to less function names if possible. And it tracks well, either get all states from campaign or states on a token....

**Comment by Merudo** [comment]
PR #809 implements the change to getTokenStates

**Comment by Phergus** [comment]
Testing PR #809 revealed a bug.  If states on a token are set via the Edit Token Dialog then `getTokenStates()` returns a list of all states instead of the states on the token.  I believe that setting states via the dialog adds all states to the token and `getTokenStates()` isn't checking whether it is true/false.   Setting a state on a token via the right-click menu or `setState()` only adds the specific state so the returned list has the correct states in that case.

Checking each state individually with `state.name` or `getState()` does return the correct status of the specific state.

**Comment by Merudo** [comment]
Thank you @Phergus . PR #812 fixes this bug.

**Comment by Merudo** [comment]
Documentation updated: https://lmwcs.com/rptools/wiki/getTokenStates

**Comment by Phergus** [comment]
Tested with new change and is now working as expected.  Closing.
