### ISSUE TITLE
Add mapName parameter to TokenLocationFunctions, check nb of parameters

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#938]
The parameter `mapName` could be added to functions `getTokenX`, `getTokenY`, and `getTokenDrawOrder`.

Additionally, the functions in TokenLocationFunctions do not return an error message if the number of parameters is too high but less than 7. A proper error message should be added.

**Comment by Merudo** [comment]
PR #940 implements this. Documentation updated.

**Comment by Phergus** [comment]
Tested new map parameter:
- getTokenX
- getTokenY
- getTokenDrawOrder
- setTokenDrawOrder

Tested parameter # check:
- getTokenX
- getTokenY
- getTokenDrawOrder
- getDistance
- moveToken
- goto
- getDistanceToXY
- setTokenDrawOrder
- moveTokenToMap
- moveTokenFromMap

Note - `moveTokenFromMap()` outputs the same string as `moveTokenToMap()`:

> Moved Token "Wolf" to map "Arid"

Should say:

> Moved Token "Wolf" **from** map "Arid"

This is a pre-existing bug.  @Merudo  If you want to throw in a quick fix on this ticket that would be fine.  Otherwise I'll open a new ticket for it.

All changes tested and working as expected.

**Comment by Merudo** [comment]
PR #954 fixes the bug you found.

**Comment by Phergus** [comment]
Closing.
