### ISSUE TITLE
Add HTML5 support through WebView

### ISSUE THREAD

**Issue by Merudo** [RPTools/maptool#972]
**Is your feature request related to a problem? Please describe.**
Java Swing only supports HTML 3.2, which is antiquated to say the least. Being able to display HTML 5 would result in a much better looking MapTool.

**Describe the solution you'd like**
HTML 5 support through the JavaFX WebView class. The webview could be displayed in a manner similar to `dialog()` and `frame`, with something like

```
[frame5(frameName, properties): {
  HTML
}]
```
EDIT:

**Implementation**: 

Currently the frame/dialog windows flow this way:

```HTMLFrameFactory -> HTMLDialog/HTMLFrame (extends JDialog/DockableFrame) -> HTMLPanel (extends JPanel) -> HTMLPane (extends JEditorPane) -> HTMLPaneEditorKit (extends HTMLEditorKit)```

with `JEditorPane` doing most of the heavy lifting related to the HTML content.

To accommodate HTML5, HTMLFrameFactory and HTMLDialog can be modified slightly to hold both html3.2 and html5 dialog/frame. New components are requires for the rest of the chain, which should look like

 ```HTMLFrameFactory -> HTMLDialog/HTMLFrame (extends JDialog/DockableFrame) -> HTMLJFXPanel (extends JFXPanel) -> WebView```

The JFXPanel is used to hold JavaFX components, and WebView deals with the HTML5 content.

Other factors to consider:

**"link" tags (for CSS  & onChangeSelection)** :  can be dealt after the html is loaded but before it is read, via the org.w3c.dom.Document class. Some will require callbacks.

**"a" tags (for macroLinks)**: can be dealt by adding an `addEventListener` to the elements of org.w3c.dom.Document.

**"input" tags**: most of the input types are the same as in 3.2, although there might be some new properties to account for. Implementing the existing ones should be easy by using an eventListener on the Submit button and then creating the json from the input fields.

EDIT2: List of features implemented:

- src: external sources blocked 
- src: external javascripts blocked before loading
- href: external sources blocked
- href: macroLinks executed
- href: external hyperlinks launched in browser
- title tag: window title changed
- meta tag: input, closebutton, width, height, temporary, working
- link tag: css sheets loaded from macros
- link tag: onChangeSelection and other events launched
- javascript: alert and confirm boxes displayed when called
- form: macro executed and data passed on form submission

**Comment by cwisniew** [comment]
I dont think this should be called webView as people will be expecting it to display web pages.

Also since form submittal works completely different in webview to the swing HTML frame I think this needs to be well thought out and documented before starting so its forwards compatible with MT Script 2.

**Comment by Azhrei** [comment]
> I think this needs to be well thought out and documented before starting

Definitely!

Threading issues may occur as well.

The HTML viewer in JFX supports animation (of GIFs) which I assume use a separate thread for each animated image (just an assumption on my part; a quick Google search was inconclusive).  If true, the MapTool stack size for threads could be prohibitive (although `javafx.concurrent` may allow setting the stack size on a per `Executor` basis, but I have no experience with that package).

I'm also not sure that the URLStreamHandler for `asset://` is thread-safe, so there's a potential concurrency problem for assets used in JFX.  (But the `asset://` URI can only be used to read the asset, so I wouldn't expect any problems unless an asset is referenced that is only partially loaded and I _believe_ the existing ImageManager and AssetManager classes already handle that, so this is probably not an issue.)

**Comment by Merudo** [comment]
> I dont think this should be called webView as people will be expecting it to display web pages.

What name would you recommend, then?

> Also since form submittal works completely different in webview to the swing HTML frame I think this needs to be well thought out and documented

I suggest we implement limited HTML 5 first, without support for form submission. Once a working model is implemented it will be easier to discuss how exactly implement form submission, which will indeed require careful thinking.

>  before starting so its forwards compatible with MT Script 2. (or at least completely distinct so that it wont confuse matters)

Where can I find the documentation for MT Script 2? I've looked on github and no one is assigned to work on the parser, and I couldn't find a discussion about it on the Developer Notes forum.

**Comment by cwisniew** [comment]
> I suggest we implement limited HTML 5 first, without support for form submission. Once a working model is implemented it will be easier to discuss how exactly implement form submission, which will indeed require careful thinking.

I would want to see the plan first before any work started as currently more an more is being hacked on without thought being put into it.

**Comment by Merudo** [comment]
> I would want to see the plan first before any work started as currently more and more is being hacked on without thought being put into how it works with other code.

I'm not sure what features or bug fixes you are referring to. I know you'd have preferred things done differently with `json.path` but I disagree that a lack of thought went into it. Many people gave their suggestions for the implementation, including @Azhrei, @JamzTheMan, @aliasmask, and @Phergus.

If you are unsatisfied with recent changes, I suggest you open new issues on github.

**Comment by cwisniew** [comment]
No I am suggesting a plan for this one that can be discussed before the changes are started

**Comment by Merudo** [comment]
> No I am suggesting a plan for this one that can be discussed before the changes are started.

I agree that a plan is great and needed, and that the feature should be discussed thoroughly before any PR is merged.

I'm just not sure why concurrently working on a prototype is undesirable to you? Having a basic working prototype can be illuminating, and can help us make a better plan.

**Comment by cwisniew** [comment]
Because since many people have ideas of what they want then if you implement what you want and submit a PR and its not what others want then it gets rejected, and we are back to needing a plan to discuss how it is to be achieved. Not everyone will review the PR and asking them to do so is not practical. 

I honestly dont think its too onerous for us to ask for a plan of how it is to be achieved/implemented for a major feature before hand so that it can be discussed. 

I know you want to get your feature in, but on the other end there are other people who would like to get features in too and having a plan rather than having to go back and forth over a PR will take up less of their time as well

**Comment by Merudo** [comment]
I understand your concern. I don't intend to open a PR for the prototype, so there will not be any back and forth over PRs. At most I'll share a link to my fork.

Honestly the prototype is mostly for my own understanding, I don't feel I'd be able to make a good plan until I worked with the code.

**Comment by Phergus** [comment]
My two cents:
- definitely can't be called `webView`.   So far everything I've come up is pretty terrible but some ideas: `dialog5/frame5`, `dialogPlus`,  `dialogH5`, `dialogJFX`
- from the start it needs to be able to handle forms.  Users will expect to use it for character sheets immediately so that needs to be dealt with.
- can WebView be stuck inside of dockable frame?  Users will likely expect that.

**Comment by Merudo** [comment]
I like `dialog5` / `frame5`.

WebView can be put into a `jfxPanel` which I believe can be put inside a dockable frame, but I'm not sure.

**Comment by Merudo** [comment]
I've added an outline of the WebView implementation in the first post.

**Comment by Azhrei** [comment]
I agree with Craig about outlining a plan, but I see no harm in doing as you say and coding up a proof of concept to see if/how it works, particularly in regards to the JIDE docking framework.  Once you have your POC, you can recap here the things you've learned (and update your plan in the first post) and we can discuss some more.

My only other input would be to keep testing in mind.  Lots of dependency injection so that mock objects can be used in testing.  (Not necessarily for your POC, but for the resulting implementation.)  Once this gets close to being merged, there's going to be a LOT of scrutiny because of how intrusive it will be for users; I'd hate to see you get too far into it only to find some killer objection late in the process. 🤔

**Comment by Merudo** [comment]
I've made a proof of concept here: https://github.com/Merudo/maptool/commit/38eb41188f1af9dba42589a63332d2aa1ac4909d

The new functions `dialog5` and `frame5` work quite similarly to `dialog` and `frame` but support HTML5.

The `frame5`  uses the same JIDE framework as `frame` and the compatibility appears good :).

I've tested it with my existing Call of Cthulhu framework, and it seems to work pretty well.

I've not types the new HTML input types (email, range, search, etc) or javascript, though.

**Comment by cwisniew** [comment]
I had a quick look, in AssetURLStreamHandler.java you shouldn't be creating a new key just because there is a sizing modifier to the passed in asset ID. If possible you should retain exactly the same behaviour as before with regards to asset IDs.

**Comment by cwisniew** [comment]
> I've not types the new HTML input types (email, range, search, etc) or javascript, though.

JavaScript (and proper CSS) support will have to wait until we have somewhere to store JavaScript and CSS in the campaign structure (hint its not in token properties)...

**Comment by Azhrei** [comment]
I understand you to mean no CSS or JS from within MT, but there’s nothing to prevent CSS and JS being referenced using an external URL, is there?  Assuming the HTTP handler isn’t being blocked...?

**Comment by Merudo** [comment]
> JavaScript (and proper CSS) support will have to wait until we have somewhere to store JavaScript and CSS in the campaign structure (hint its not in token properties)...

I'm not sure what you mean by that. WebView should support CSS and JavaScript out of the box.

**Comment by cwisniew** [comment]
> I understand you to mean no CSS or JS from within MT, but there’s nothing to prevent CSS and JS being referenced using an external URL, is there? Assuming the HTTP handler isn’t being blocked...?

There are certainly very good reasons to not allow that.
These will be used for character sheets, macro tools etc in frameworks people distribute and use. These things should not be reliant on a third party site being available to function.

**Comment by cwisniew** [comment]
> > JavaScript (and proper CSS) support will have to wait until we have somewhere to store JavaScript and CSS in the campaign structure (hint its not in token properties)...
> 
> I'm not sure what you mean by that. WebView should support CSS and JavaScript out of the box.

and where does the JS or CSS come from? it has to be stored somewhere, and as per my just added comment above, 3rd party website is not acceptable. (infact this should be specifically blocked by the solution)

**Comment by Merudo** [comment]
> and where does the JS or CSS come from? it has to be stored somewhere

JS is defined in the HTML page just like any HTML element with the `<script>` tag, and CSS is already accessible from macros (check this: https://www.lmwcs.com/rptools/wiki/Introduction_to_Dialogs_and_Frames#Now_for_a_dash_of_CSS)

**Comment by Azhrei** [comment]
I agree that in an ideal world, the campaign should be entirely self-contained.  But we already have repos that rely on third party sites.  IMO, it’s actually less of an issue to rely on a third party CDN for CSS and/or JS in terms of reliability.

However, I would support the enable/disable option that Jamz added for his REST functions being used to similarly control access to external resources for the web view component; I’m definitely concerned about DOS attacks and other attack vectors that allowing JS would open up.

(I’m also a bit concerned that the enable/disable option is in Preferences instead of campaign properties, but not _that_ concerned.  Seems like maybe it should be in both places with a logical AND operation.  But that’s a separate discussion.)

**Comment by cwisniew** [comment]
> > and where does the JS or CSS come from? it has to be stored somewhere
> 
> JS is defined in the HTML page just like any HTML element with the `<script>` tag, and CSS is already accessible from macros (check this: https://www.lmwcs.com/rptools/wiki/Introduction_to_Dialogs_and_Frames#Now_for_a_dash_of_CSS)

I know this I wrote the code (and documentation) for dialogs and frames. But I also did say proper support :) I consider this to be a hack (although a necessary one). I also know that JS is available in a <script> tag but to be honest thats really messy (and not really reusable) so its also not what I would consider "proper" full support.

What really needs to happen at some stage is for the campaign to be expanded to contain a file system, in which html, css, javascript, etc files can be added)

**Comment by cwisniew** [comment]
> I agree that in an ideal world, the campaign should be entirely self-contained. But we already have repos that rely on third party sites. IMO, it’s actually less of an issue to rely on a third party CDN for CSS and/or JS in terms of reliability.
> 

How many frame works are still usable even though the current creator is not around? Many, some may need tweaks.
How many would be usable if they had to load CSS/JS from creator's website and they are no longer around and hosting?
A Lot less. 

You have only considered a small small part of the issue.

The implementation MUST not be just whats convenient, but the stability of frameworks (and also perceived stability of MapTool I guess) has to be taken into account. 

"My stuff will be ok" is not an excuse for not doing something the correct way.

**Comment by JamzTheMan** [comment]
To back things up "just a bit" and regards to naming/new functions and all.

I know the "goal" is to support HTML5 via webview, but can we state for what purpose? I assume this is not for chat and so only via a new "frame".

To throw a curve ball in, is this new "macro function" only to pop up a new frame that accepts HTML5/CSS (inline) content? And what's everyone's thought on supporting markdown as well? HTML5 is awesome but SO many people just want to do some simple formatting and even HTML is a "barrier" to that end.

So Markdown support (via this new webview) would be nice (and can come later) but maybe also the WYSIWYG editor as well? FX has a built in HTML editor that could be used?

Anyhoo, just bringing this in in case the "name" of the functions may need to be generic enough and the method signatures are forward thinking to support some possible future "stuff".

I'm not a fan of frame5 or dialog5.  Although I don't have a better name off the top of my head yet.

Another question, can the new "webView" not display current frame/dialog content? Do we need new macro's for other reasons (like method signature changes?)

Lastly, I'll leave you with this sample of how Markdown with themes produces some really quick and nice pages, imagine that in MT?: https://homebrewery.naturalcrit.com/

**Comment by Phergus** [comment]
Certainly if a webView frame/dialog was 100% compatible with the existing functions then a new set of macros wouldn't be needed.

To bring in the JFX HTML editor would be a whole new dialog and not actually part of the macro dialog/frame.  Right?  Would it need to be in a dockable frame?

To do any more with dialogs/frames than what we have now but bringing it up to HTML 5 would require significantly more work and support such as the filesystem internal to the campaign that @cwisniew mentioned.

**Comment by JamzTheMan** [comment]
Agreed. Figured I would spark some convo and ideas to make sure things are at least thought about. :smile: 

The HTML editor would/could be its own dialog. Although, ideally it would be merged/used with the macro editor somehow. I assume most frame HTML dev would be while doing macro coding. Maybe that's a 2.0 thing then...

**Comment by Merudo** [comment]
> The HTML viewer in JFX supports animation (of GIFs) which I assume use a separate thread for each animated image (just an assumption on my part; a quick Google search was inconclusive). If true, the MapTool stack size for threads could be prohibitive (although `javafx.concurrent` may allow setting the stack size on a per `Executor` basis, but I have no experience with that package).

It does support gif, and in fact I was able to easily display an animated gif from asset ID using the new dialog5/frame5 functions.

I would expect WebView to be relatively efficient and not use one thread per gif. But even if this is the case, I'm don't expect this to be an issue: I believe java can handle 6500+ threads, enough to display thousands of gifs at the same time.

**Comment by Merudo** [comment]
> So Markdown support (via this new webview) would be nice (and can come later) but maybe also the WYSIWYG editor as well? FX has a built in HTML editor that could be used?

I'm all for Markdown support (it looks awesome) but I don't think it would be easy to do in webview.

For Markdown we could use javafx.scene.web.HTMLEditor instead, or one of the many other libraries available.

**Comment by Azhrei** [comment]
> I would expect WebView to be relatively efficient and not use one thread per gif. But even if this is the case, I'm don't expect this to be an issue: I believe java can handle 6500+ threads, enough to display thousands of gifs at the same time.

Heh, I don’t expect webview or any other components to be efficient at all — there’s less surprises that way. 😉

Let’s see, 6500 threads at 8M each is 5GB+.  You still think that’s not a problem?  (Reminder:  physical RAM plus swap/paging is the limit of virtual memory for a system.)

Most OSes have limits well below your 6500 number, anyway.  The point is not “what are the limits”, but “what are the ramifications”.

But none of this is important right now as you explore your proof of concept. 🙂

**Comment by Merudo** [comment]
> I also know that JS is available in a <script> tag but to be honest thats really messy (and not really reusable) so its also not what I would consider "proper" full support.

Actually JS can be contained in a lib token (just like any text can) and then can be inserted in the HTML with the usual methods:

`<script>[r: getLibProperty(scriptName, lib)]</script>`

**Comment by Merudo** [comment]
> But none of this is important right now as you explore your proof of concept. 🙂

At this point I consider it past this stage :).

I've implemented all the features described in my plan (top post) and more:

- The tags `<input>`, `<button>`, `<meta>`, `<a>`, `<link>`, `<img>` have all been implemented.
- MacroLinks work fine.
- The events onChangeSelection, onChangeImpersonated & onChangeToken work.
- The Java Script functions `alert` and `confirm` are supported.

At this point I think the functions are pretty solid.

What more should I do before I open a PR?

**Comment by Azhrei** [comment]
Is the development part of your WebView branch in your repo?  I'll try to grab it tonight and play around a bit to stress test it, but ideally we'd be able to get @aliasmask and Wolph42 and other scripters to bang on it a bit.  They might need a binary build though, as they likely don't have a development environment installed.

**Comment by Merudo** [comment]
Yep it's on https://github.com/Merudo/maptool/tree/WebView

I built a JAR of my fork, available here: https://mega.nz/#!nQQ0UCxa!eMTIFp_nWqhGWu-ey4PzStCPEliseCWcWfkgM4IMx0M

**Comment by Azhrei** [comment]
I grabbed the JAR and did a DNA transplant into a download of MapTool-1.5.7 (I opened the macOS .app and replaced the JAR with yours).  This new gene-spliced version will run, but various Swing components don't react.  For example, toolbar buttons can be clicked and will react, but the asset library JTree doesn't respond to mouse events.  This might be something in my configuration, though; I need to try this as another user.  Something in my primary user account's configuration messes up the JRE...

**Comment by JamzTheMan** [comment]
I can create a branch off of develop to merge this too and we can build binaries from that. Also everyone can do a code review and a somewhat safer merge as we test this out further?

**Comment by Azhrei** [comment]
Merging it to a separate branch seems like a good idea; it might be easier for folks to test.

**Comment by Phergus** [comment]
Seems to be working here but then I have no frames that actually do anything other than a macroLink and onChangeToken.  I'm clearly going to have to go in and change a number of attributes that were valid under 3.2 but aren't under 5.0 so that various formatting settings work again.

**Comment by Phergus** [comment]
A curious layout issue.  Note the scrollbar on the HTML5 frame stops before getting to the bottom of the window. 
**HTML 5 Frame**
![Screenshot 2019-12-10 15 56 04](https://user-images.githubusercontent.com/34379254/70576438-22a3dd80-1b66-11ea-9cb2-128b1cc40dd5.png)

**MT 1.5.8 Frame**
![Screenshot 2019-12-10 15 56 09](https://user-images.githubusercontent.com/34379254/70576464-38b19e00-1b66-11ea-9cc7-9099cacc0ddb.png)

**Comment by Azhrei** [comment]
Looks like the content is inside an element that isn't full height.  But the `body` element of any page should automatically be full height...  I'd have to see the HTML to diagnose why the scroll bar isn't top to bottom.  It might have something to do with being inside a JIDE container as well.

There's an interesting font color change as well, or did you do that yourself?

**Comment by Azhrei** [comment]
Btw, someone with a lot of HTML frames and/or dialogs might be able to simply create a UDF for `dialog` that is turned into `dialog5`for ease of testing...

**Comment by Phergus** [comment]
The font color change is some bad HTML that apparently worked in the Swing HTML renderer but not in webView.  lol

Webview does some interesting automatic changes and additions to the HTML you pass it.
[SwingHTML.txt](https://github.com/RPTools/maptool/files/3947782/SwingHTML.txt)
[JFXHTML.txt](https://github.com/RPTools/maptool/files/3947783/JFXHTML.txt)

**Comment by Merudo** [comment]
The JAR should be launched by itself, you don't need to splice it into a download of another MapTool version.

**Comment by cwisniew** [comment]
> > I also know that JS is available in a <script> tag but to be honest thats really messy (and not really reusable) so its also not what I would consider "proper" full support.
> 
> Actually JS can be contained in a lib token (just like any text can) and then can be inserted in the HTML with the usual methods:
> 
> `<script>[r: getLibProperty(scriptName, lib)]</script>`


Just to be clear we wont be using this to back door JS macros in (i.e. manipulating tokens etc), the JS should only be able to affect the DOM. Because we dont want a macro language that is only executable in a web view.

**Comment by Merudo** [comment]
> > > I also know that JS is available in a <script> tag but to be honest thats really messy (and not really reusable) so its also not what I would consider "proper" full support.
> > 
> > 
> > Actually JS can be contained in a lib token (just like any text can) and then can be inserted in the HTML with the usual methods:
> > `<script>[r: getLibProperty(scriptName, lib)]</script>`
> 
> Just to be clear we wont be using this to back door JS macros in (i.e. manipulating tokens etc), the JS should only be able to affect the DOM. Because we dont want a macro language that is only executable in a web view.
> 
> anything beyond standard DOM manipulation will require a well thought out / documented API before hand.

Agreed!

**Comment by Phergus** [comment]
Should this work?
```
[frame("MyFrame"):{
<!DOCTYPE html>
<html>
<body>
<h2>What Can JavaScript Do?</h2>
<p id="demo">JavaScript can change HTML content.</p>
<button type="button" onclick='document.getElementById("demo").innerHTML = "Hello JavaScript!"'>Click Me!</button>
</body>
</html>
}]
```

**Comment by Merudo** [comment]
> Should this work?
> 
> ```
> [frame("MyFrame"):{
> <!DOCTYPE html>
> <html>
> <body>
> <h2>What Can JavaScript Do?</h2>
> <p id="demo">JavaScript can change HTML content.</p>
> <button type="button" onclick='document.getElementById("demo").innerHTML = "Hello JavaScript!"'>Click Me!</button>
> </body>
> </html>
> }]
> ```

It works if you change `frame` to `frame5`.

I don't see a problem with this use of JS.

**Comment by JamzTheMan** [comment]
Can we still use the same trick on the frame to copy and view the generated HTML? Asking for a friend.

**Comment by aliasmask** [comment]
It would only copy the displayed HTML and not hidden, I assume. And no JS. 

I'm looking forward to fancier forms assuming css for buttons aren't locked like it is for the current html. I've also like having collapsing menus and highlighting when moused over type events. Will there be the ability to have java libraries like JQuery?

**Comment by Merudo** [comment]
> I'm looking forward to fancier forms assuming css for buttons aren't locked like it is for the current html. 

Yep, the `<button>` is highly customizable.

>I also like having collapsing menus and highlighting when moused over type events. Will there be the ability to have java libraries like JQuery?

JQuery is supported; I don't know about other java libraries.

Example: 
```html
[frame5("myframe"):{
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
[r: "\$(document).ready(function(){\$(" + '"p"' + ").click(function(){\$(this).hide();});});"]
</script>
</head>
<body>

<p>If you click on me, I will disappear.</p>
<p>Click me away!</p>
<p>Click me too!</p>

</body>
</html>
}]
```

**Comment by Azhrei** [comment]
(Heh, I can see the backslashes are going to be just as bad or worse than using them in regex calls in MTscript!)

A few things to keep in mind for anyone who wants to play with this.

External URL access is likely to be limited by the GM overall or by the Player on their system.  Allowing remote code to execute locally is a _really bad idea_, in general.  There will probably be a bunch of different limitations (like only trusted functions being allowed to open panels with external access, or limits on the ability to run JS, or so on).

Next, because of that, in the long term there will be some way to store CSS/JS locally and refer to it without requiring an external connection.  It _might_ take a form similar to our `asset://` URL or it might not.  While playing with a proof of concept this isn't a big deal, but plan to be _very_ modular with anything developed using this approach as it will minimize any ripple effects when things change.  (Notice I didn't say "if things change". 😉)  For example, putting the JS into a variable and then using `[r: jsVAR]` to interpolate it into the HTML is probably a good technique (that anyone serious about frameworks is likely already using).

And last... there's no telling how this entire integration is going to work out long-term.  It's a great idea for scripters like you, Chris, to play with this stuff and "stress test" it, so to speak, but there could be weird interactions between JFX, the JS engine, the JIDE panels, and Swing.  I guess what I'm saying is, it may or may not work — your mileage will vary.

Having said all that, bang away at it and see if you can break it.  That's the point, after all.  We want to learn what is easy to do and what is hard to do, and what bumps you find along the way. 🙂  (I'm particularly interested in debugging approaches.  Build it in a web browser with access to devtools and the like, then port it into MT?  That's probably what I'd do...)

**Comment by JamzTheMan** [comment]
Linking to external sites like d20pfsrd would be nice so a character sheet could just like feats and spells to an off-site but display in MT.

Of course you we be rehashing the whole external access issues again though.

Sadly I would like to display HLO in a webviee in MT to minimize switch (screen scape would even be nice) but my last test showed HLO failed to load in a webview a month or so ago.

**Comment by cwisniew** [comment]
> Linking to external sites like d20pfsrd would be nice so a character sheet could just like feats and spells to an off-site but display in MT.
> 
> Of course you we be rehashing the whole external access issues again though.
> 
For something like this a "bultin" dedicated browser internal window would be a better option. Not trying to reuse frame5 for such a thing.

**Comment by cwisniew** [comment]
> > I'm looking forward to fancier forms assuming css for buttons aren't locked like it is for the current html.
> 
> Yep, the `<button>` is highly customizable. Example:
> 
> ![button](https://user-images.githubusercontent.com/7371085/70661153-4a0fae80-1c29-11ea-92e4-d0da80571789.png)
> 
> ```
> [frame5("buttonFrame"):{
> <style>
> [r: '
> .styled {
>     border: 0;
>     line-height: 2.5;
>     padding: 0 20px;
>     font-size: 1rem;
>     text-align: center;
>     color: #fff;
>     text-shadow: 1px 1px 1px #000;
>     border-radius: 10px;
>     background-color: rgba(220, 0, 0, 1);
>     background-image: linear-gradient(to top left,
>                                       rgba(0, 0, 0, .2),
>                                       rgba(0, 0, 0, .2) 30%,
>                                       rgba(0, 0, 0, 0));
>     box-shadow: inset 2px 2px 3px rgba(255, 255, 255, .6),
>                 inset -2px -2px 3px rgba(0, 0, 0, .6);
> }
> 
> .styled:hover {
>     background-color: rgba(255, 0, 0, 1);
> }
> 
> .styled:active {
>     box-shadow: inset -2px -2px 3px rgba(255, 255, 255, .6),
>                 inset 2px 2px 3px rgba(0, 0, 0, .6);
> }
> ']
> </style>
> <button class="favorite styled" type="button">
> Cool Button
> </button>
> 
> }]
> ```
> 
> > I also like having collapsing menus and highlighting when moused over type events. Will there be the ability to have java libraries like JQuery?
> 
> JQuery is supported; I don't know about other java libraries.
> 
> Example ([from here](https://www.w3schools.com/jquery/)):
> 
> ```
> [frame5("myframe"):{
> <html>
> <head>
> <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
> <script>
> [r: '\$(document).ready(function(){\$("p").click(function(){\$(this).hide();});});']
> </script>
> </head>
> <body>
> 
> <p>If you click on me, I will disappear.</p>
> <p>Click me away!</p>
> <p>Click me too!</p>
> 
> </body>
> </html>
> }]
> ```

**Comment by cwisniew** [comment]
Just to reiterate NO EXTERNAL ACCESS!

**Comment by Merudo** [comment]
> Just to reiterate in general there should be _**NO EXTERNAL LINKS/REFERENCES/ETC (including scripts, css)!**_

The existing functions dialog/frame (HTML 3.2) have been supporting external CSS for quite a while  now.

For example, this code fetches an online CSS and applies it:

```
[dialog("dialog"):{
<html>
<head>
<link rel='stylesheet' type='text/css' href='https://dl.dropboxusercontent.com/s/y5efhlrt87ppeam/style.css'></link>
</head>
This is purple, because of the online CSS sheet.
</html>
}]
```

**Comment by cwisniew** [comment]
> > Just to reiterate in general there should be _**NO EXTERNAL LINKS/REFERENCES/ETC (including scripts, css)!**_
> 
> The existing functions dialog/frame (HTML 3.2) have been supporting external CSS for quite a while now.
> 
> For example, this code fetches an online CSS and applies it:
> 
> ```
> [dialog("dialog"):{
>    <html>
>    <head>
>    <link rel='stylesheet' type='text/css' href='https://dl.dropboxusercontent.com/s/y5efhlrt87ppeam/style.css'></link>
>    </head>
> This is purple, because of the online CSS sheet.
>    </html>
> }]
> ```

Yeah I consider this a mistake that we are stuck with, and don't want to repeat it. With newer CSS and JS this would go from "I can't load the CSS so its ugly" to "I cant load CSS/JS so its completely unusable"

**Comment by JamzTheMan** [comment]
> Another option if you REALLY have to have external access,someone volunteers to track all publicly available campaigns and maintains all versions of scripts they reference somewhere else, and is also willing to update the campaigns when any scripts go missing. Although this means people who play off line/limited access face to face (it happens) are still screwed if the lastest framework uses a site they can't get to it in the middle of their game

That seems aggressive.  Why should anyone else care how and what I am doing in my campaign? I would suspect by far most people do not share their work (but several people do!)

Are you suggesting one of the reasons to disallow external access is to prevent shared campaigns from no longer working after they are no longer maintained?

FWIW I'm not specifically advocating external access is required (it would be nice but so is just having HTML5 support!)

**Comment by cwisniew** [comment]
> Are you suggesting one of the reasons to disallow external access is to prevent shared campaigns from no longer working after they are no longer maintained?
> 
Yes, I said so earlier in the comments. 

Because what will annoy users, drive them away from MapTool faster than a campaign they started (this includes frameworks) no longer working after they have put a great many hours into playing it. 

I agree having all the things would be nice, but that also goes back to my previous comment...
"My stuff will be ok" is not an excuse for not doing something the correct way. Which is adding a way to add these things to the campaign.

**Comment by JamzTheMan** [comment]
I would argue that giving framework authors the ability to create rich content driven frameworks would boost MapTool's image as a clunky old 90's app and bring in more users.

But since we are in opinion territory (as we can only assume what may or may not happen to drive user base too/from MapTool) we'll just have to agree to disagree on this one.

I'm also completely fine with starting out with no external support. It's far easier to add it in later with proper thought and support than it is to put the genie back into the bottle.

**Comment by cwisniew** [comment]
> I would argue that giving framework authors the ability to create rich content driven frameworks would boost MapTool's image from a clunky old 90's app to something a little more modern and bring in more users.
> 
But I am not arguing against giving them this ability, in fact I want to encourage it AND encourage people to share frameworks, but really to do both it needs a way where people who share campaigns/frameworks make them in such a way that when they no longer are interested/or accidently break something it doesn't just stop working for other people. 

Imagine the scenario, you play maybe once a month, you start up the game ready to play and your character sheets, hand outs, notes etc just dont work because the website disappeared, or author is in middle of making/testing some changes and doesn't version things. You have lost this gaming session (and maybe more until you can fix it).

I am open to other ways of solving the issue (This still sucks for people playing offline, but I guess framework developers would have to spell this out).
Like maybe white listing some urls ajax.googleapis.com/* would be a good one.
Maybe github for CSS/Script and come up with a template/instructions for how to host your campaign, create a release and refer to the correct release in your framework. (but again this also requires work to do).
I am pretty sure that if either of the above websites disappear people are going to have larger problems to deal with.

But what I really dont like is "I will just dump it on dropbox/some website I currently have access to" for the above stated reasons.

**Comment by JamzTheMan** [comment]
Maybe a dependency management approach following gradle/maven practices and cache the external libs needed. How that is best implemented would need to be worked out. 

Obviously some things would cache better than other things.

Ultimately it will be up to the framework dev to code them in such a way that external dependency reliance doesn't cripple the framework.  We can lead them to the stream but...

**Comment by melek** [comment]
Just to add another opinion (hooray), I support keeping out external references. I have a lot of reasons. Most of my reasons are predictions, but I think they aren't unrealistic.

1. Despite warnings from developers, external JS will become popular among MapTool creators and lead to easy inclusion of irresponsibly external large payloads. Especially as people add on to eachother's work.. yikes. JQuery, anyone?
2. Despite  warnings from MapTool creators, users will download and use shiny new things with external JS.
3. Down the road as frameworks and plugins (library tokens) break, users will be disappointed and frustrated because their games are breaking.
4. As disappointed and frustrated users cry for help, the community will have a new support and documentation challenge that will become a MapTool 'thing' people have to deal with - fixing and replacing missing external resources from user campaigns and plugins.
5. The users most likely to use the feature are the users most likely to share their work with the community, so any problems from external resources are sure to make their way into average users' games and proliferate from there. Maybe CSS never became popular to host elsewhere, but JavaScript - and the temptation to say either "Oh that library is cool I'll just link it in!", or "Oh NEAT I could fix this plugin for everyone who ever downloads it centrally!" would be, I think, too great to pass up for some creators.
6. External resources disrupt offline access, make DIY tinkering harder, and I feel erodes the 'Millenium Falcon' feeling of MapTool. 
 
To add a bit of narrative, I recently revised the Frameworks wiki page and report that many of those older framework download links were broken. If any of those frameworks depended on scripts hosted by their creators, they would also be broken, and many games based on them now would not exist because they too would be broken. 

I think there is a lot of wisdom in keeping things internal by design. For the official fork I definitely agree with @cwisniew.

**Comment by Merudo** [comment]
> Just to reiterate in general there should be _**NO EXTERNAL LINKS/REFERENCES/ETC (including scripts, css)!**_
> The frame5/dialog5 should block it completely.

Newest version of my fork blocks external css,  javascripts, images, and others.

Basically anything with a `src` or `href` is blocked.

Exceptions: macroLinks, hyperlinks (link to anchor), asset ids are untouched, and external urls are redirected to the system's browser.

**Comment by JamzTheMan** [comment]
I created a branch feature-html5-frame so when you think you are feature complete and ready for official POC submit a PR against that branch.

@RPTools/coredevs It looks like there are no objections to the current approach @Merudo has going now.  But once the PR is submitted I'll add everyone as a reviewer as an official sign-off for testing (on a side branch only)

If there is still "things" needed, I suggest we edit the issue at the top using checkboxes or such so we can track them. The issue is getting long.

**Comment by Merudo** [comment]
I think the functions are ready for review! As far as I can tell everything works as it should.

**Comment by Phergus** [comment]
Hopefully enough testing has been done with the Alpha releases to consider this part complete.

Further bug fixes or additional features can go on new tickets.
